### ISSUE TITLE
VideoWriter correct recording

### ISSUE THREAD

**Issue by NBarile** [ultralytics/yolov5#9449]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey,

I have a little question
I want to record my video detection with 240fps camera (with detect.py) and after that, when I look at the videowriter result (in run/exp*) the video is really fast.

For exemple, I record a 20sec video, and the result is a video of 2sec..

Semone knows I can i correctly save the video ?

Thanks !

**Comment by glenn-jocher** [comment]
@NBarile you may need to customize the dataloader and videowriter to your custom requirements. See detect.py and utils/dataloaders.py

**Comment by glenn-jocher** [comment]
@NBarile you can also create a fully custom python inference workflow using YOLOv5 PyTorch Hub. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by NBarile** [comment]
> @NBarile you may need to customize the dataloader and videowriter to your custom requirements. See detect.py and utils/dataloaders.py

This is what I tried
But I have this error : 
![image](https://user-images.githubusercontent.com/48790575/190720211-287abb70-9d40-430f-b864-0d4a808642f8.png)
when I tried this
![image](https://user-images.githubusercontent.com/48790575/190720357-237c4e0b-dace-4dd5-b8a9-574167bdab26.png)

And I already use the small model.

**Comment by glenn-jocher** [comment]
vid_cap is `None` in your example, there's nothing to set.

**Comment by NBarile** [comment]
oh .... 
My bad XD
Thanks @glenn-jocher 

I already change the utils/dataloaders.py to set the correct setting of my camera here : #9402

I will try how many detection per second the program make, I think it's the problem's here.
I think videowriter take 240frame per 240frame and put it into 1 second.

If you have any idea or suggestion to help me, 
feel free to send me ^^

**Comment by glenn-jocher** [comment]
@NBarile glad you found the solution! 🎉 You might want to check if the videowriter is correctly handling the frames or consider adjusting the handling of frame rates or time intervals in the videowriter. Good luck with testing the detection per second, and feel free to ask if you need further assistance!
