### ISSUE TITLE
Reversing anchor order 

### ISSUE THREAD

**Issue by learncrazy** [ultralytics/yolov5#945]
## ❔Question

excuse me! I would like to ask, what does Reversing anchor order stand for? This problem appeared when I modified the network structure and ran yolo.py. But it seems to be able to train normally. Does it have any impact?

**Comment by learncrazy** [comment]
![image](https://user-images.githubusercontent.com/50286586/92842707-79e91e00-f416-11ea-8e50-1cb3c06e0f2a.png)
The first epoch was normal at the beginning, but it seemed that at the end, the size of his feature map did not match and the training could not be continued.

**Comment by yinyuhangi** [comment]
I met the same problem, have you solved it ? @learncrazy

**Comment by glenn-jocher** [comment]
Anchor order is automatically handled. No action is needed on the user's part.

**Comment by learncrazy** [comment]
I've solved this problem. The reason for this problem is an error in the configuration file. You can check whether the three layers of the detect function are correct or whether concat is correct.



At 2020-11-17 18:28:52, "yinyuhangi" <notifications@github.com> wrote:

I met the same problem, have you solved it ? @learncrazy
