### ISSUE TITLE
updated a files some error show builld model

### ISSUE THREAD

**Issue by suyogbargule** [ultralytics/yolov5#9457]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

`!python train.py --img 640 --batch 32 --epochs 50 --data data/data.yaml --cfg models/custom_yolov5s.yaml --weights yolov5s.pt --name yolov5s_results --cache`

**TypeError**: conv2d() received an invalid combination of arguments - got (Tensor, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:

- (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
   didn't match because some of the arguments have invalid types: (Tensor, Parameter, NoneType, tuple, tuple, tuple, int)

- (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
   didn't match because some of the arguments have invalid types: (Tensor, Parameter, NoneType, tuple, tuple, tuple, int)

### Additional

_updated  train.py file and yolo.py file and mode then start to this error_

**Comment by glenn-jocher** [comment]
@suyogbargule training with official yamls works correclty, but if you have a customized yaml you might need to update the Conv() inputs after a recent PR https://github.com/ultralytics/yolov5/pull/9347
