### ISSUE TITLE
Where are the yamls compatible to these weights?

### ISSUE THREAD

**Issue by ZeKunZhang1998** [ultralytics/yolov5#946]
## ❔Question
in this web
https://github.com/ultralytics/yolov5/releases/tag/v1.0
## Additional context

Traceback (most recent call last):
  File "train.py", line 406, in <module>
    train(hyp)
  File "train.py", line 123, in train
    raise KeyError(s) from e
KeyError: "weights/yolov5l.pt is not compatible with /kaggle/input/aaaaaa/datasets_828506_1428584_yolov5_models_yolov5l.yaml. Specify --weights '' or specify a --cfg compatible with weights/yolov5l.pt."

**Comment by glenn-jocher** [comment]
v1.0 release contains all v1.0 files
https://github.com/ultralytics/yolov5/releases/tag/v1.0

**Comment by ZeKunZhang1998** [comment]
hello，why yolov5x.pt is170m in my memory



---Original---
