### ISSUE TITLE
Multi Class 

### ISSUE THREAD

**Issue by Crazoro** [ultralytics/yolov5#9460]
My dataset has 6 classes but training result shows only 1 class as attachment below.
![class](https://user-images.githubusercontent.com/61926365/190879030-509779c3-78f0-4dee-8aed-90bbea443a2b.png)
<data.yaml>  
train: E:\ML\yolov5-master\BNDataset\train
val: E:\ML\yolov5-master\BNDataset\valid
nc: 6
names: ['BN1', 'BN2', 'BN3', 'BN4', 'BN5', 'BN6']

I put all the images of the classes together with 1 folder now.
What should I have to get result for all of the 6 classes after training?

**Comment by barney2074** [comment]
can you post your training command i.e something like:
`classify/train.py --model yolov5s.pt --data '../classify'`
or
`train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt`
It is not clear if you have a classification (first sample) or object detection (second sample) model
If the latter- a sample of a annotation label file would help

**Comment by Crazoro** [comment]
> can you post your training command i.e something like: `classify/train.py --model yolov5s.pt --data '../classify'` or `train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt` It is not clear if you have a classification (first sample) or object detection (second sample) model If the latter- a sample of a annotation label file would help

python train.py --img 1280 --batch 2 --epochs 5 --data BNDataset/data.yaml --cfg ./models/yolov5s.yaml --optimizer Adam --weights yolov5s.pt --name BN5

**Comment by barney2074** [comment]
o.k, so it is object detection

to check the annotations & classes- the easiest method is to upload to Ultralytics HUB, or Roboflow, which will display the classes & bounding boxes like this:
![image](https://user-images.githubusercontent.com/25944617/190880733-ac269b26-807f-4130-9c7e-74de13b44bc2.png)

Also check in your label files that the first digit corresponds to the class names in your YAML file
`3 0.484375 0.476042 0.374969 0.264542`
So 3 corresponds to the 'roller' class in my example

Andrew

**Comment by Crazoro** [comment]
Many thanks Mr. Andrew. You saved my day! I found that all of my labels have same class as '0'.

**Comment by glenn-jocher** [comment]
@Crazoro you're welcome! Glad to hear you found the issue. Consistent labels are key. Don't hesitate to ask if you have more questions. Good luck with your training!
