### ISSUE TITLE
image total count and each classes count is same, is this ok?

### ISSUE THREAD

**Issue by Crazoro** [ultralytics/yolov5#9463]
![image](https://user-images.githubusercontent.com/61926365/190894330-82d85777-0884-4986-8d26-d8d0e2598642.png)

Is this case is ok? I think each classes image count should be separated as the count of labels.
What can I do to separate images?

**Comment by glenn-jocher** [comment]
@Crazoro this is normal, all images are counted.

**Comment by Crazoro** [comment]
> @Crazoro this is normal, all images are counted.

I got it. Thanks a lot.
