### ISSUE TITLE
Android device Support

### ISSUE THREAD

**Issue by Katana-O** [ultralytics/yolov5#9468]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description
Is it possible that android screen data as an input for yoloV5? Live stream Ofc, not a pic.
Can you make smthing like " python detect.py --source android-screen" happen? It is a significant feature for people who don't want to deploy yolo on android.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Katana-O are you saying something that streams a mobile camera to a python environment for inference?

We don't have anything like that out of the box, but you might be able to create a similar effect if you can find an app that streams your mobile camera to an IP address, and then pass the camera address as the --source

**Comment by glenn-jocher** [comment]
@Katana-O BTW you can also train and deploy YOLOv5 models to Android with https://hub.ultralytics.com/

**Comment by glenn-jocher** [comment]
@Katana-O YOLOv5 uses cv2 for streams, so you should verify your address works with cv2 first, i.e.
https://stackoverflow.com/questions/70805012/cv2-videocapture-html-live-stream
