### ISSUE TITLE
yolo5 segmentation color and area 

### ISSUE THREAD

**Issue by lordfarquad3211** [ultralytics/yolov5#9474]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to change the color of the segmentized area and how to find the exact coordinates of the mask (no the bounding box)

**Comment by glenn-jocher** [comment]
@lordfarquad3211 Ultralytics color palette is used for all annotations, you can customize here:

https://github.com/ultralytics/yolov5/blob/92b52424d468feb48c51c3dde173d5d2c606a44b/utils/plots.py#L34-L50\

We don't have a mask to segmentation coordinate output function currently, if you'd like to contribute one that would help a lot!

@AyushExel @Laughing-q
