### ISSUE TITLE
try to run parallel thread in processing but get an error

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/yolov5#9476]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello I run this command as instructed in google colab pro. But I got an error.
"cp: cannot stat 'runs': No such file or directory",   where can I find this file? 

Based on this, google colab pro provide 4 GPU.
https://stackoverflow.com/questions/60180673/number-of-active-sessions-google-colab-pro

!python -m torch.distributed.run --nproc_per_node 2 train.py --img 512 --batch 128 --data data.yaml --weights yolov5m.pt --cache  --nosave  --device 0,1 
----------------------------------
Traceback (most recent call last):
  File "train.py", line 630, in <module>
    main(opt)
  File "train.py", line 512, in main
    device = select_device(opt.device, batch_size=opt.batch_size)
  File "/content/yolov5/utils/torch_utils.py", line 118, in select_device
    f"Invalid CUDA '--device {device}' requested, use '--device cpu' or pass valid CUDA device(s)"
AssertionError: Invalid CUDA '--device 0,1' requested, use '--device cpu' or pass valid CUDA device(s)
train: weights=yolov5m.pt, cfg=, data=data.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=300, batch_size=128, imgsz=512, rect=False, resume=False, nosave=True, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=ram, image_weights=False, device=0,1, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 ✅
Traceback (most recent call last):
  File "train.py", line 630, in <module>
    main(opt)
  File "train.py", line 512, in main
    device = select_device(opt.device, batch_size=opt.batch_size)
  File "/content/yolov5/utils/torch_utils.py", line 118, in select_device
    f"Invalid CUDA '--device {device}' requested, use '--device cpu' or pass valid CUDA device(s)"
AssertionError: Invalid CUDA '--device 0,1' requested, use '--device cpu' or pass valid CUDA device(s)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 614) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-09-18_14:53:55
  host      : cd045c9b9a39
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 615)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-09-18_14:53:55
  host      : cd045c9b9a39
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 614)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
cp: cannot stat 'runs': No such file or directory

**Comment by glenn-jocher** [comment]
@frabob2017 user error. Colab instances never provide more than a single GPU, yet you've requested 2. Just follow the default examples in the official notebook:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

**Comment by frabob2017** [comment]
> @frabob2017 user error. Colab instances never provide more than a single GPU, yet you've requested 2. Just follow the default examples in the official notebook: https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

Good to know that.  If cannot use parallel processing in Colab, how can increase speed significantly in google colab?

**Comment by glenn-jocher** [comment]
@frabob2017 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by frabob2017** [comment]
> @frabob2017 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:
> 
> * Increase `--batch-size`
> * Reduce `--img-size`
> * Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
> * Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
> * Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
> * Train on faster GPUs, i.e.: P100 -> V100 -> A100
> * Train on free GPU backends with up to 16GB of CUDA memory: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> 
> Good luck 🍀 and let us know if you have any other questions!

yesterday, I tried cache memory, it is too much memory consuming. Let me try cache disk.   Thank you for your great suggestions.

**Comment by pderrenger** [comment]
You're welcome! If you encounter any issues with disk caching or have further questions, feel free to ask.
