### ISSUE TITLE
Variables/options modification using yaml file

### ISSUE THREAD

**Issue by hardikdava** [ultralytics/yolov5#9477]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello yoloV5 creators, I want to know what parameters are possible to change using yaml file. It would be great to know the possible list of parameter which can be change using yaml fields in order to optimize architecture for different deployment. For an example parameters like activation function, numbers of input image channel, etc.

**Comment by glenn-jocher** [comment]
@hardikdava the model yamls accept two additional fields that are left off by default:

```yaml
activation: nn.SiLU()
channels: 3
```

You can modify these to customize a model, and of course you can can also modify the existing fields like the scaling constants and architecture to create your own custom models.

**Comment by hardikdava** [comment]
Thanks for the reply @glenn-jocher

**Comment by glenn-jocher** [comment]
You're welcome, @hardikdava! If you have any more questions or need further assistance, feel free to ask. Our community is here to help!
