### ISSUE TITLE
How to convert model output to training data?

### ISSUE THREAD

**Issue by kirvix** [ultralytics/yolov5#9483]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Was wondering how I could convert model output data:

```
        xmin       ymin       xmax       ymax  confidence  class name
0  21.934017  20.296589  96.526718  92.874222    0.348322      1  bus
```

Into training data

### Additional

Couldn't seem to find a solution anywhere, so I figured I'd ask here!

**Comment by glenn-jocher** [comment]
@kirvix you can use --save-txt when predicting or validating.

**Comment by kirvix** [comment]
@glenn-jocher Hello, thanks for your response however, I am running a custom model

**Comment by glenn-jocher** [comment]
@kirvix the model is irrelevant to --save-txt, it works on any model.

**Comment by kirvix** [comment]
My apologies, let me specify, I want to use pytorchs hub load with a custom model.

```
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5n - yolov5x6, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
```

**Comment by glenn-jocher** [comment]
@kirvix then handle results however you want. See results.xywhn

**Comment by kirvix** [comment]
Got it, thanks very much!

**Comment by glenn-jocher** [comment]
@kirvix you're welcome! If you have any more questions, feel free to ask. Good luck with your project!
