### ISSUE TITLE
Fine-tuning Faster-RCNN model on yolov5

### ISSUE THREAD

**Issue by bzha5848** [ultralytics/yolov5#9486]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there,

As I notice that the current yolov5 version did fine-tuning job of Resnet and efficientnet on yolov5, is that possible for me to fine-tuning weight like faster-rcnn on yolov5 and see the structure as well?

Thanks so much!!

**Comment by AyushExel** [comment]
No currently only you can only finetune official yolov5 models for detection and segmentation. For classification you can finetune on yolov5-cls models or any models available on torch hub
