### ISSUE TITLE
Module Not Found Error: No module named 'models'

### ISSUE THREAD

**Issue by deepaks11** [ultralytics/yolov5#9490]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Integrations

### Bug

![image](https://user-images.githubusercontent.com/113359279/190987022-63e8289b-415f-46a6-a204-69dc26a19168.png)

I have an issue with my model's folder, if try to change my model's folder name I am getting the following error  (No module named 'models') in Yolov5

If I keep the folder as a name model then only it loads the Yolo.pt file.
![image](https://user-images.githubusercontent.com/113359279/190990271-1b536a09-dfe8-4da3-995c-122a5a392db5.png)

### Environment

-YOLO : Yolov5s
-OS : Windows 10 64 bit
-PYTHON : Python 3.7

### Minimal Reproducible Example

return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'

### Additional

Can I use multiple yolov5s detection codes like (object_detection, Emotion_detection, and Person_count)  to integrate as one project?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
User error. See https://docs.python.org/3/reference/import.html

**Comment by deepaks11** [comment]
Hi glenn,
          The import process is perfect. In emotion, the detection module contains the model's folder. if I renamed the models into emotion_models. After changing the name of the folder the source is not executed, its throws ModuleNotFoundError: No module named 'models'.I am not referring that the model's folder but the torch will automatically load that folder, where I can change that folder name in yolov5

**Comment by deepaks11** [comment]
> User error. See https://docs.python.org/3/reference/import.html
Hi glenn,
The import process is perfect. In emotion, the detection module contains the model's folder. if I renamed the models into emotion_models. After changing the name of the folder the source is not executed, its throws ModuleNotFoundError: No module named 'models'.I am not referring that the model's folder but the torch will automatically load that folder, where I can change that folder name in yolov5

**Comment by glenn-jocher** [comment]
@deepaks11 as a rule you can't rename directories arbitrarily in python, as this will break all imports that use functions inside those directories and files. 

If you rename any directory, every instance that refers to that directory in your entire codebase must also be updated.

**Comment by deepaks11** [comment]
I know that process. In our project, I load all the models globally. Initially, I load object detection with yolov5s(it detect all objects) then I load the emotion detection module, but here yolov5s(it detect only person faces) will default load that objects detection yolo file. how can I load both separately

**Comment by glenn-jocher** [comment]
@deepaks11 you can load multiple models easily with PyTorch Hub:


YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model1 = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
model2 = torch.hub.load('ultralytics/yolov5', 'yolov5m')  # yolov5n - yolov5x6 official model
model3 = torch.hub.load('ultralytics/yolov5', 'yolov5l')  # yolov5n - yolov5x6 official model
...
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model1(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by zhoujian-z** [comment]
@glenn-jocher hello!  Can I use torch.save(model.state_dict()) the method to save the trained model?

**Comment by glenn-jocher** [comment]
@zhoujian-z for example model saving code see train.py:
https://github.com/ultralytics/yolov5/blob/f8b74631e50bcac1bef8a52283102a5feb7217a6/train.py#L369-L381

**Comment by zhoujian-z** [comment]
@deepaks11 did you solve the problem?

**Comment by deepaks11** [comment]
File "D:\Try\Footwears_yolo_v5\footwear_main.py", line 16, in <module>
    model = DetectMultiBackend(weights, device=device, dnn=False, data=data, fp16=False)
  File "D:\Try\Footwears_yolo_v5\m\common.py", line 340, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "D:\Try\Footwears_yolo_v5\m\experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "C:\Users\deepak.s\Anaconda3\envs\yolo_v5\lib\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\deepak.s\Anaconda3\envs\yolo_v5\lib\site-packages\torch\serialization.py", line 1049, in _load
    result = unpickler.load()
  File "C:\Users\deepak.s\Anaconda3\envs\yolo_v5\lib\site-packages\torch\serialization.py", line 1042, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'

Does anyone solve this error?

**Comment by JeremyCraigMartinez** [comment]
@deepaks11 I think your best bet (or only option) is to simply save the weights, not the model. Then use [torch.hub.load](https://pytorch.org/docs/stable/hub.html#torch.hub.load). I'm seeing that same stack trace issue on my end and this is my path forward to getting a portable model (or equivalent)

**Comment by sivaji123256** [comment]
@deepaks11 ,I am facing the same problem while loading the yolov5 weights. Have you solved it ?

**Comment by Tlaloc-Es** [comment]
@sivaji123256 I solved this developing a library

https://github.com/Tlaloc-Es/aipose

You only need to install with

`pip install aipose`

and use this code

```
from aipose.model import YoloV7Pose
import cv2
model = YoloV7Pose()
img = cv2.imread('person.jpg')
keypoints = model(img)
print(keypoints)
```

**Comment by devpko** [comment]
@deepaks11 I'm facing the same problem.

It seems that the error occurs on data.pkl (you can see this file by unzipping the .pt file) while loading it. 
And this caused by the file structure at the time of training.
The .pt file you are using is trained on the file structure that says models.common, but there is no models.common in the changed file structure, so the error is occurring.

You can check details on below url.
https://pytorch.org/tutorials/beginner/saving_loading_models.html
> This save/load process uses the most intuitive syntax and involves the least amount of code. Saving a model in this way will save the entire module using Python’s [pickle](https://docs.python.org/3/library/pickle.html) module. The disadvantage of this approach is that the serialized data is bound to the specific classes and the exact directory structure used when the model is saved. The reason for this is because pickle does not save the model class itself. Rather, it saves a path to the file containing the class, which is used during load time. Because of this, your code can break in various ways when used in other projects or after refactors.

So if you want "Emotion_detection" as directory name, I think you have to re-train with your file structure and get new .pt file.
