### ISSUE TITLE
CUDA AssertionError with yolov5 in ROS Noetic

### ISSUE THREAD

**Issue by TDVL** [ultralytics/yolov5#9495]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I have cloned the yolov5 ROS Noetic repo on Ubuntu 20.04 VBox VM.https://github.com/mats-robotics/yolov5_ros
I have checked few time the requirements, and everything is satisfied (pip install -r requirements.txt).
Also, CUDA is installed too, however, I use yolov5 on VBox Ubuntu VM in Python without any problems on old laptop without CUDA and GPU.
![Screenshot from 2022-09-19 12-42-40](https://user-images.githubusercontent.com/47524135/191009041-694edb39-8746-4ba5-8e0b-a988c5a96d6d.png)
When I run the package, a CUDA AssetionError is on and the process dies.
What could be the problem, the screenshot is attached.
![Screenshot from 2022-09-19 12-32-40](https://user-images.githubusercontent.com/47524135/191009279-39374065-8144-41b4-b45f-b66d6f8aa106.png)
Is it possible to avoid this error, I don't need the GPU and CUDA in VM.

**Comment by glenn-jocher** [comment]
@TDVL use --device cpu

**Comment by TDVL** [comment]
Thank you Glenn.
Where should I setup this option? Which file should I change?

**Comment by glenn-jocher** [comment]
python detect.py --device cpu

**Comment by TDVL** [comment]
This is when I run it in Python, is it? But how can I use this setting when I use the roslaunch option?

**Comment by TDVL** [comment]
Thanks, I have solved this cpu error, but I have another error: AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/home/osboxes/catkin_ws/src/yolov5_ros/src/yolov5/models/yolo.py'>
![Screenshot from 2022-09-19 16-06-13](https://user-images.githubusercontent.com/47524135/191036827-c3af0f48-e57b-4f97-8439-08aea112225e.png)
What could be the problem now?

**Comment by glenn-jocher** [comment]
@TDVL DetectionModel classes were introduced a few weeks ago, your code or your model may be out of date.

**Comment by TDVL** [comment]
I have replaced the yolo.py file, now it works. I will test it further.
Thank you.

**Comment by glenn-jocher** [comment]
@TDVL you're welcome! Glad to hear that it's working now. If you have any other questions or issues, feel free to ask. Good luck with your testing!
