### ISSUE TITLE
Segmentation data format

### ISSUE THREAD

**Issue by vladoossss** [ultralytics/yolov5#9496]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

1. When we solved the detection problem, we provided coordinates that are associated with boxes. When solving segmentation, do we feed masks in the COCO format? Do we only serve masks or with boxes?
2. When solving segmentation (segment/predict.py), we also get boxes at the output. Are this box coordinates trained along with masks?

Thank you!

**Comment by glenn-jocher** [comment]
@vladoossss yes segmentation models are trained on and output both boxes and masks. See segment/train.py for usage examples:
https://github.com/ultralytics/yolov5/blob/11640698977724daf7982c9da398c2ee2f2b6e91/segment/train.py#L1-L17

**Comment by paradigmn** [comment]
@glenn-jocher can you tell us how the output tensors for the segmentation models are interpreted? For the detection models we had one output tensor with the following encoding for each detection:
| box_x | box_y | box_w | box_h | obj. | p(0) | p(1) | ... | p(79) |
|-------|-------|-------|-------|------|------|------|-----|-------|

Meaning center coordinates, box size, objectiveness and class likelihoods. Giving a length of 85 for 80 COCO classes.

The segmentation models have two output tensors, where the first has a length of 117 per detection and the second is dependent on the input size. How are boxes, masks  and likelihoods encoded in this format? I tried to derive it from the DetectMultiBackend and the helper functions in detect.py, but it is quite hard to reverse engineer.

**Comment by glenn-jocher** [comment]
@paradigmn masks are constructed by matrix multiplications of the first and second outputs for detections above confidence threshold only as it's an expensive operation. You can follow the steps in segment/predict.py
