### ISSUE TITLE
test bug

### ISSUE THREAD

**Issue by zidanexu** [ultralytics/yolov5#95]
I running this command python test.py --img 736 --conf 0.001 --weight yolov5s.pt --device '1,2,3,4'
get the error 
![image](https://user-images.githubusercontent.com/54395639/84771122-6ee74300-b00b-11ea-9391-ef5ef0a0075e.png)
[ Tesla P40]
[Centos]

**Comment by glenn-jocher** [comment]
@zidanexu this is a `thop` dependency causing this problem. If you have it installed you need to uninstall it.

**Comment by glenn-jocher** [comment]
@zidanexu I've disabled multi-gpu on test.py, as it was causing problems with half precision inference.

**Comment by zidanexu** [comment]
it is done . thanks
