### ISSUE TITLE
Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

### ISSUE THREAD

**Issue by WuPedin** [ultralytics/yolov5#950]
## ❔Question
Hi,
I currently tried to run yolov5 + deepsort.
When I trained yolov5 by using MOT16 datasets, I got this error.
Looks like something happened when evaluating validation data.
I can't figured out what happened. (I've checked that the bboxes are normalized to 0,1)
Could you give me some suggestions?
Thanks a lot!

![image](https://user-images.githubusercontent.com/31273808/92896077-a15bdd00-f44e-11ea-8f74-521b22e66c29.png)
![image](https://user-images.githubusercontent.com/31273808/92895979-8e490d00-f44e-11ea-855d-e06ad616c160.png)

**Comment by chinesejunzai12** [comment]
> ## ❔Question
> Hi, I currently tried to run yolov5 + deepsort. When I trained yolov5 by using MOT16 datasets, I got this error. Looks like something happened when evaluating validation data. I can't figured out what happened. (I've checked that the bboxes are normalized to 0,1) Could you give me some suggestions? Thanks a lot!
> 
> ![image](https://user-images.githubusercontent.com/31273808/92896077-a15bdd00-f44e-11ea-8f74-521b22e66c29.png) ![image](https://user-images.githubusercontent.com/31273808/92895979-8e490d00-f44e-11ea-855d-e06ad616c160.png)

你好, 这个问题您解决了么?
我也遇到了同样的问题

**Comment by glenn-jocher** [comment]
Hello,

Thank you for reaching out and providing detailed information about your issue. To assist you effectively, could you please provide a minimum reproducible code example? This will help us understand the context and reproduce the bug on our end. You can refer to our guide on creating a minimum reproducible example here: [Ultralytics Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and the YOLOv5 repository. You can update your packages using the following commands:

```bash
pip install --upgrade torch
git pull https://github.com/ultralytics/yolov5
```

From the error message, it seems like there might be an issue with the bounding box indices during the evaluation phase. Double-check that your bounding boxes are correctly formatted and within the expected range. If the issue persists, providing the code and specific steps you followed will be crucial for further investigation.

Looking forward to your response so we can help you resolve this issue.
