### ISSUE TITLE
Can I set the confidence for each label individually？

### ISSUE THREAD

**Issue by l0ngjx** [ultralytics/yolov5#9508]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Now the conf-thres parameter of yolov5 is applicable to all tags, but I want to set a conf-thres for each different tag. Is this requirement easy to implement? Or can only one conf-thres be passed in?

**Comment by glenn-jocher** [comment]
@l0ngjx you can customize NMS for this here on L822 but it is not available by default:
https://github.com/ultralytics/yolov5/blob/f8b74631e50bcac1bef8a52283102a5feb7217a6/utils/general.py#L800-L823
