### ISSUE TITLE
Albumentations for segmentation

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#9510]
Albumentations not working with segmentation, masks do not rotate.

`A.Rotate(p=0.25, limit=(90, 90))`

**Comment by Laughing-q** [comment]
@DonkeySmall we just support some simple augmentations by albumentations for now, so yes if you add some other augmentations like `Rotate`, then the albumentations won't work with masks. Maybe we'll support more augmentations from albumentation later sometimes, but it'll be appreciated if you can submit a PR for this. :)

**Comment by glenn-jocher** [comment]
@DonkeySmall you should be able to modify the `degrees` hyp here for rotation. This does not use albumentations:
https://github.com/ultralytics/yolov5/blob/f8b74631e50bcac1bef8a52283102a5feb7217a6/data/hyps/hyp.scratch-low.yaml#L25

**Comment by DonkeySmall** [comment]
Oh thank you, I completely forgot about it

**Comment by glenn-jocher** [comment]
@DonkeySmall you're welcome! Don't hesitate to ask if you have any more questions. Really appreciate your understanding.
