### ISSUE TITLE
Different output data shape between pytorch model and onnx model

### ISSUE THREAD

**Issue by zhujun5164** [ultralytics/yolov5#952]
## ❔Question
I have exported the model to ONNX successfully. But when i test the onnx model return data and try to deal the model predit, i find the ONNX model output size is with 5 dimension, such as (1, 3, 80, 64, 85) return by 1 * 3 * 640 * 512 input.
And i check the detect.py's output, the model output data is 3 dimension (1, 20160, 85) for the same image.

How can i deal with the ONNX model output and get the yolov5 predict.

## Additional context
![image](https://user-images.githubusercontent.com/49580602/92904741-aff9c280-f455-11ea-8c2f-9de724d02cb0.png)
![image](https://user-images.githubusercontent.com/49580602/92904976-df103400-f455-11ea-8060-edb35513cd98.png)

**Comment by nobody-cheng** [comment]
i have problem，you fix?
