### ISSUE TITLE
I want to overwrite and save the analysis results

### ISSUE THREAD

**Issue by Heartful-echo** [ultralytics/yolov5#9522]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi

Analysis results are stored in the exp folder of the run folder, but the exp folder increases each time analysis is performed. For example exp1⇨exp2.

Is it possible to fix this exp folder and always overwrite the analysis results?

**Comment by barney2074** [comment]
I'm not sure if using the --name argument with detect.py will overwrite previous results (of the same name)
It looks like the increment_path function in general.py will create a new folder..?
You could modify this

For this issue- rather than writing to text files, I log the infererence results to a time-series database (I used Influx)

**Comment by glenn-jocher** [comment]
You can use —exist-ok to overwrite existing logging directory

**Comment by kazuya-uchida** [comment]
Thank you everybody.

I'm not using detect.py. I'm using the code below in my original.

**### model = torch.hub.load('xxxxxxx')
model.classes = [0]
model.conf = 0.25

imgs = ['./image.jpg']
results = model(imgs, size=640)
results.save()**

When you execute results.save(), the exp folder will increase.
Exp, exp1, exp2, etc. will increase each time it is executed.
I want exp only. I would like to overwrite the result.

Isn't there an option like "model.classes = [0]"?

**Comment by glenn-jocher** [comment]
@kazuya-uchida 
```
results.save(save_dir='path/to/save_dir')
```

**Comment by kazuya-uchida** [comment]
@glenn-jocher 

Thank you for your advice.

I tried.
**results.save(save_dir='runs/detect/exp')**
However, exp2, exp3, exp4 and new directories were generated as shown in the attached image.
I always want the result to be overwritten and stored inside the exp directory.
What is causing this?
![キャプチャ](https://user-images.githubusercontent.com/56055010/192399787-c9df577a-b77b-43e0-959c-a3b43ad5d977.PNG)

**Comment by glenn-jocher** [comment]
@kazuya-uchida good news 😃! Your original issue may now be fixed ✅ in PR #9617. Now you can pass `exist_ok=True` to save results to the same directory.


To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by kazuya-uchida** [comment]
@glenn-jocher 
Thanks for the very good news.
Today will be a good day.

**Comment by glenn-jocher** [comment]
@Heartful-echo i'm glad to hear that it's working as expected for you! 😊 If you have any more questions or need further assistance, feel free to ask. Happy coding and have a great day! 🚀
