### ISSUE TITLE
yolov5 raspberry pi to laptop streaming

### ISSUE THREAD

**Issue by oes5756** [ultralytics/yolov5#9523]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I installed a camera on Raspberry Pie
Real-time object recognition.
The command is 
python detect.py --source 0 --save-txt --save-conf 
result is success

But I think the Raspberry Camera can detect it in real time
I'd like to send the live video to my laptop.
I need help with how to solve it.

**Comment by Wuder6** [comment]
Hi，
       if I didn't understand wrong. What you need is how to save the video obtained by the Raspberry Pi camera locally and on the remote computer. Recommend you another project from github. It can fully achieve your requirements. Currently I'm trying to achieve real-time detection via streaming, but when I run ‘python detect.py --source http://192.168.xx.xx:8000/index.html’, yolov5 can't open this website.

**Comment by Wuder6** [comment]
12 days have passed, if you have achieved your goal, can you share your plan. Thank you

**Comment by Wuder6** [comment]
https://github.com/Ruud14/SecurityCamera/blob/master/README.md

**Comment by oes5756** [comment]
@Wuder6 
Does it work on Raspberry pi4 64bit?

As far as I know, 64 bits are not supported for real-time streaming using "mjpg"
It doesn't work when I actually tried it

**Comment by oes5756** [comment]
@gustavozantut
I want to stream YOLOv5 videos through Raspberry Pie's camera.
I need your help.

**Comment by gustavozantut** [comment]
> @gustavozantut
> I want to stream YOLOv5 videos through Raspberry Pie's camera.
> I need your help.

I have my repo where I explain the steps to make it run live with pi+windows+wsl+docker : https://github.com/gustavozantut/yolov5_live_results
If it's confusing or you want to understand it better we can talk!

**Comment by oes5756** [comment]
@gustavozantut 
There is a problem in progress according to your guide.
I'm currently working at Raspberry Environment

"sudo docker run --ipc=host --gpus all -it ultralytics/yolov5:latest"
this command 
The result of executing this command in the path of the a folder is "yolov5_live_results-master" 
error called "sudo : docker : command not found"

**Comment by gustavozantut** [comment]
> @gustavozantut 
> There is a problem in progress according to your guide.
> I'm currently working at Raspberry Environment
> 
> "sudo docker run --ipc=host --gpus all -it ultralytics/yolov5:latest"
> this command 
> The result of executing this command in the path of the a folder is "yolov5_live_results-master" 
> error called "sudo : docker : command not found" 

Right, Try without sudo, check if you have docker installed o raspi . In my architecture e just use the raspi to stream the video and do everything on windows with WSL, in your case you should install docker on pi, try run without sudo and your video source will be your pi cam

**Comment by oes5756** [comment]
@gustavozantut 
I don't understand the order of your guide.
I need your help I'm sorry.

First, I downloaded the yolov5 file you uploaded to raspberry pi and run detect.py to check that frames are saved.

I have to start streaming now
I installed the docker first as you explained.

The next thing I need to do is
"export DISPLAY=<display IP>:<display port> (usually <host ip>:0)"

Is this the right place?
If so, is this command for pc or raspberry pi?
Also, what are the numbers for ip and port?

**Comment by gustavozantut** [comment]
> @gustavozantut 
> I don't understand the order of your guide.
> I need your help I'm sorry.
> 
> First, I downloaded the yolov5 file you uploaded to raspberry pi and run detect.py to check that frames are saved.
> 
> I have to start streaming now
> I installed the docker first as you explained.
> 
> The next thing I need to do is
> "export DISPLAY=<display IP>:<display port> (usually <host ip>:0)"
> 
> Is this the right place?
> If so, is this command for pc or raspberry pi?
> Also, what are the numbers for ip and port?
> 
> 

Sorry it's somehow confusing but when I wrote made sense....I swear!

1- from the server(where you want to process the image)

Docker run --ipc=host --gpus all -it guhzantut/yolov5_live_gst:latest

2-inside the container previously started 

export DISPLAY=<display IP>:<display port> (usually <host ip>:0)

The IP must be the IP from where you want to display the live results,  in your case, the raspi IP.

Eg: export DISPLAY=192.168.0.2:0 


2-start the stream 

3-inside the docker container

python detect.py --source rtsp://<rtspServerIP>:<rtspServerPort>/stream --save-frame

The --save-frame arg will save every frame with the detection box inside the project folder(/usr/src/app/runs/detect/exp/frames/)

4- from inside the container start streaming frames.

gst-launch-1.0 -e multifilesrc location="/usr/src/app/runs/detect/exp/frames/video%d.png" index=2 caps="image/png,framerate=10/1,width=640,height=480" ! pngdec ! autovideosink sync=false.

I'm not sure raspi will take such a load but it's this. If you are in doubt on how to use yolo flags or docker volumes we can talk more, reach me at gustavo_zantut@hotmail.com or whatsapp +5511912501025

**Comment by oes5756** [comment]
@gustavozantut 
This is the part I don't understand.
"asas"

When you run the above command on raspi, you download a lot of things.
I already downloaded all the files you uploaded and saved them in Raspi
Should I enter the above command to download it again?
There is not enough storage space for raspi.

Also, when you do --save-frames, the frame is
/home/pi/yolov5_live_results-master/runs/detect/exp/frames is saved here.

**Comment by oes5756** [comment]
@gustavozantut 
Do I have to install gstreamer on the raspberry pi?

**Comment by gustavozantut** [comment]
> @gustavozantut 
> This is the part I don't understand.
> "Docker run --ipc=host --gpus all -it guhzantut/yolov5_live_gst:latest"
> 
> When you run the above command on raspi, you download a lot of things.
> I already downloaded all the files you uploaded and saved them in Raspi
> Should I enter the above command to download it again?
> There is not enough storage space for raspi.
> 
> Also, when you do --save-frames, the frame is
> /home/pi/yolov5_live_results-master/runs/detect/exp/frames is saved here.

Okay so when we execute

"Docker run --ipc=host --gpus all -it guhzantut/yolov5_live_gst:latest"

We are creating a "virtual machine" where  the docker image is downloaded with all the o.s., libs and packs that yolov5 needs to run.(nothing installed on your computer/raspi, everything is already inside the docker image, gst, pytorch, python, opencv, everything comes with the docker image)

With the docker image downloaded (20GB) and the container running you should enter the container and do all the steps from inside the container.

BUT if you don't wanna use docker, you can download my GitHub code, cd to the folder and try to start from the "python detect ..." Step. But you will need to install everything manually

**Comment by oes5756** [comment]
@gustavozantut 
I ran yolov5 on the raspberry pi and installed it on the raspberry pi
Run real-time object recognition through the pi camera.

I want to send the video to the PC through streaming, but I don't think --view-img works.

**Comment by gustavozantut** [comment]
> @gustavozantut 
> I ran yolov5 on the raspberry pi and installed it on the raspberry pi
> Run real-time object recognition through the pi camera.
> 
> I want to send the video to the PC through streaming, but I don't think --view-img works.

So you you have to change some part from the command:

gst-launch-1.0 -e multifilesrc location="/usr/src/app/runs/detect/exp/frames/video%d.png" index=2 caps="image/png,framerate=10/1,width=640,height=480" ! pngdec ! autovideosink sync=false

This is the part I know less but maybe changing autovideosink to tdp ou udp will create a tdp stream.

**Comment by gustavozantut** [comment]
> @gustavozantut 
> I ran yolov5 on the raspberry pi and installed it on the raspberry pi
> Run real-time object recognition through the pi camera.
> 
> I want to send the video to the PC through streaming, but I don't think --view-img works.

So you you have to change some part from the command:

gst-launch-1.0 -e multifilesrc location="/usr/src/app/runs/detect/exp/frames/video%d.png" index=2 caps="image/png,framerate=10/1,width=640,height=480" ! pngdec ! autovideosink sync=false

This is the part I know less but maybe changing autovideosink to tdp ou udp will create a tdp stream.

**Comment by gustavozantut** [comment]
> @gustavozantut 
> I ran yolov5 on the raspberry pi and installed it on the raspberry pi
> Run real-time object recognition through the pi camera.
> 
> I want to send the video to the PC through streaming, but I don't think --view-img works.

So you you have to change some part from the command:

gst-launch-1.0 -e multifilesrc location="/usr/src/app/runs/detect/exp/frames/video%d.png" index=2 caps="image/png,framerate=10/1,width=640,height=480" ! pngdec ! autovideosink sync=false

This is the part I know less but maybe changing autovideosink to tdp ou udp will create a tdp stream.

**Comment by oes5756** [comment]
@gustavozantut 
Look at the order I ordered

1. yolov5_live_results-master floder installed my raspi /home/pi
2. my raspi terminal command start
3. cd yolov5_live_results-master
4. python detect.py --source 0
5. Then should I run the "gst-launch-1.0 -e multifilesrc location="/usr/src/app/runs/detect/exp/frames/video%d.png" index=2 caps="image/png,framerate=10/1,width=640,height=480" ! pngdec ! autovideosink sync=false" you gave me?

**Comment by oes5756** [comment]
@muhk01
I succeeded in recognizing objects using yolov5 on rasberry pi.
Through Rasberry pi's camera, i can recognize things in real time
Do it.

I'm going to use Raspi's object recognition camera screen on the PC
I'd like to send it out.
I need your help.

I tried to execute the flask code you uploaded in raspi, but it failed.

**Comment by gustavozantut** [comment]
> @gustavozantut Look at the order I ordered
> 
>     1. yolov5_live_results-master floder installed my raspi /home/pi
> 
>     2. my raspi terminal command start
> 
>     3. cd yolov5_live_results-master
> 
>     4. python detect.py --source 0
> 
>     5. Then should I run the "gst-launch-1.0 -e multifilesrc location="/usr/src/app/runs/detect/exp/frames/video%d.png" index=2 caps="image/png,framerate=10/1,width=640,height=480" ! pngdec ! autovideosink sync=false" you gave me?
 You should run

4. python detect.py --source 0 --save-frame

the --save-frame option will save the frames on ROOT /runs/detect/exp/frames/, it might be on /home/pi/yolov5_live_results-master/runs/detect/exp/frames/

 *Each time you run detect.py it creates a new "exp" folder (exp, exp1, exp2...) so check if you are poiting to the directory that the saved frames are actualy being saved, can be :

 /home/pi/yolov5_live_results-master/runs/detect/exp/frames/
 /home/pi/yolov5_live_results-master/runs/detect/exp1/frames/
 /home/pi/yolov5_live_results-master/runs/detect/exp2/frames/
 /home/pi/yolov5_live_results-master/runs/detect/exp3/frames/
                                          .
                                          . 
                                          .
 /home/pi/yolov5_live_results-master/runs/detect/expn/frames/

then put this directory on

5. gst-launch-1.0 -e multifilesrc location="FRAMES DIRECTORY HERE/video%d.png" index=2 caps="image/png,framerate=10/1,width=640,height=480" ! pngdec ! autovideosink sync=false

The last and mostly unkown for me is the stream to the client, but i had some search and got it working very poorly with:

5. gst-launch-1.0 -e multifilesrc location="{FRAMES_DIR}/video%d.png" index=2 caps="image/png,framerate=10/1,width=640,height=480" ! pngdec ! rtpvrawpay ! udpsink host={STREAM_RECEIVER_IP} port=5000

And FINALLY in the device you want to receive and display the stream (RECEIVER)

6. gst-launch-1.0 udpsrc port=5000 ! application/x-rtp, clock-rate=90000,payload=96  ! rtpvrawdepay ! videoconvert ! xvimagesink

Image is some way green but i could see the stream, the gst streams are complex and not my speciality so take a look at the docs(https://gstreamer.freedesktop.org/documentation/index.html?gi-language=c) to refine this video pipeline but there is your skeleton!

**Comment by AnooshaArshad356** [comment]
I'm working on raspberry pi 4 model b 2gb ram and the is on it is Ubuntu 64bit. The issue I'm facing is that detection is not occuring when I run the yolov5 model on pi. It just gives me an answer
No detection
No error was discovered but it's not detecting the objects.
Can someone suggest me what is the possible solution I can try?

**Comment by glenn-jocher** [comment]
@AnooshaArshad356 one possible solution to try is checking the dataset and annotations used to train the model. Make sure they are representative of the objects you are trying to detect in your images. It is also possible to try fine-tuning the model on your own dataset, with your own classes and annotations.

Another possible solution to try is to adjust the model's hyperparameters, such as the input size, batch size, and training epochs. You may need to experiment with different values to achieve optimal performance on your specific use case.

Finally, make sure you are using the latest version of YOLOv5 and properly configuring the inference code for running on a Raspberry Pi, such as setting the correct source for the input data.

For more information and support, you can refer to the [YOLOv5 documentation](https://docs.ultralytics.com) and GitHub [Issues](https://github.com/ultralytics/yolov5/issues) page.
