### ISSUE TITLE
How to make webcame stream image black with only bounding boxes over it?

### ISSUE THREAD

**Issue by ToobaW** [ultralytics/yolov5#9526]
I want to edit the code in detect.py to make the webcam stream on the screen all black, with only the detection boxes showing in the stream output. Can anyone guide me on where can I edit the output stream parameters for making the pixels (other than the bounding boxes) all black and also change the size and orientation of the output webcam stream? @glenn-jocher

**Comment by glenn-jocher** [comment]
@ToobaW to make the webcam stream all black with only the detection boxes showing, you can edit the `visualize.py` file in the YOLOv5 repository. Specifically, you can modify the `plot_one_box()` function to draw the bounding boxes on a black background and adjust their size and orientation. For changing the size and orientation of the output webcam stream, you can modify the parameters in the `cv2.imshow()` function. For more detailed guidance, refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.

Let me know if you need further assistance!
