### ISSUE TITLE
V100 b1 vs V100 b32 meaning

### ISSUE THREAD

**Issue by Camilochiang** [ultralytics/yolov5#9527]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

My apologies. Basic question. I would appreciate if someone can answer as I didn’t find any information about it 

What does b1 and b32 stand for in the checkpoint table? I guess that v100 mean that the test were conducted in a Tesla v100. Is it b1 , 1 gb of gpu ram and b2, 32 gb of gpu ram?

**Comment by glenn-jocher** [comment]
batch-size 1, batch-size 32
