### ISSUE TITLE
Yolo model post export has incorrect outputs - XCODE-MLMODEL

### ISSUE THREAD

**Issue by iris-technology-inc** [ultralytics/yolov5#953]
## ❔I trained a YOLOv5 custom object detector via the code below, and the model does not output any detections. Why? 

`python train.py --img 224 --batch 16 --epochs 2 --data ./data/Autono.yaml --cfg ./models/yolov5s.yaml --weights ''`

Post training I exported the model for use in Xcode using this: 

`cd yolov5`

`export PYTHONPATH="$PWD”`

`python models/export.py --weights models/iristest22.pt --img 224 --batch 1`

It successfully exports a ml model, but the models outputs when opened seem incorrect see below: 

![Screen Shot 2020-09-11 at 11 18 00 AM](https://user-images.githubusercontent.com/60715661/92944758-6348c400-f422-11ea-8468-68ef382f0e93.png)

It should look like this. Is there something wrong with my detect.py file or a config issue? 

![Screen Shot 2020-09-11 at 11 32 19 AM](https://user-images.githubusercontent.com/60715661/92945006-b28ef480-f422-11ea-84fa-808f8ad539fe.png)

**Comment by iris-technology-inc** [comment]
BUMP

**Comment by foochuanyue** [comment]
did you manage to solve it? Having the same issue
