### ISSUE TITLE
How to choose the values of epochs and evolve in hyperparameter evolution?

### ISSUE THREAD

**Issue by chengzihencai** [ultralytics/yolov5#9537]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained my model before （80 epochs），now I need hyperparameter evolution.  How to choose the values of epochs and evolve in hyperparameter evolution? --epochs 80 --evolve 300 or --epochs 10 --evolve 1000?

**Comment by glenn-jocher** [comment]
@chengzihencai your base scenario (including --weights and number of --epochs) is up to you and depends on your use case.

Evolution will optimize hyperparameters specifically for your base scenario.
