### ISSUE TITLE
Pruning/Sparsity Tutorial Question

### ISSUE THREAD

**Issue by MinjeongKim03** [ultralytics/yolov5#9538]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In the results we can observe that we have achieved a sparsity of 30% in our model after pruning, which means that 30% of the model's weight parameters in nn.Conv2d

How do you know on the terminal that 30% of the model's weight parameters in the nn.Convd2 layer are equal to zero?

**Comment by glenn-jocher** [comment]
@MinjeongKim03 you can step through all the parameters and measure the sparsity rate, i.e.
```python
for p in model.parameters():
    print((p == 0).mean())
```
