### ISSUE TITLE
Get label mask segmentation from detect.py?

### ISSUE THREAD

**Issue by MinhThanghus** [ultralytics/yolov5#9539]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I training model yolov5s-seg.
I run detect.py and  use save-txt but output label bbox is not mask.
How to get label mask?
Thank  @glenn-jocher

**Comment by glenn-jocher** [comment]
@MinhThanghus thanks for asking! We don't have a mask image to mask segments function, but if you'd like to contribute a PR for one that would be great!

@AyushExel @Laughing-q

**Comment by iscyy** [comment]
@MinhThanghus Hi, do you need to save the pixels of the label mask to txt?

**Comment by MinhThanghus** [comment]
@iscyy I really need it, can you show me how to do it?
thank you

**Comment by JoeNan1** [comment]
@iscyy Do you have a way to convert the mask. png or. json information in the partition to. txt？If such data format conversion can be achieved, it will greatly increase the inclusiveness of Yolov5 in data set format.

**Comment by JonasMArnold** [comment]
May I ask what your solution to the issue is? Been searching for a similar approach - but wasn't able to find anything usable @MinhThanghus

**Comment by MinhThanghus** [comment]
@JonasMArnold the source code is support, if you use "--save-txt" default=True
