### ISSUE TITLE
How to adjust the labelling for results.render

### ISSUE THREAD

**Issue by TheRedAppl** [ultralytics/yolov5#9546]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

This is the section I used to predict in my program
``` python
model = torch.hub.load('yolov5','custom', path='yolov5/runs/train/exp3/weights/best.pt', source= 'local', force_reload=True)
results = model(img_path)
%matplotlib inline
plt.imshow(np.squeeze(results.render()))
plt.show()
```
This results expectedly in a result like this
![bus](https://user-images.githubusercontent.com/112451579/191719595-6828ef7c-2606-44be-9ae3-fe3f36e016d3.jpg)

However, I wanted to  make some adjustments to the location of the text and what is shown in the label. So, by searching I realized I a lot of these adjustments could be done in the detect.py file. While it does change the value if I run directly on detect.py.
![bus](https://user-images.githubusercontent.com/112451579/191732991-7d1ba77d-d017-424b-a2a5-25994d518126.jpg)
These changes do not affect results.render() . Are they not related and if so how do I make such adjustments?

Test change to detect.py line 166
``` python
label = None if hide_labels else (names[c] if hide_conf else f'{names[c]} {conf:.2f} HELLO')
```

### Additional

The main program is done on jupyter notebook

**Comment by glenn-jocher** [comment]
See Detections class in utils.common
