### ISSUE TITLE
An open source program for labeling in segmentation?

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#9549]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 

is there some open source program for labeling the images in the new segmenation models?

is there some documentation or common name for normalize these annotations?

**Comment by glenn-jocher** [comment]
@hdnh2006 segmentation annotations are `class x1 y1 x2 y2 x3 y3, ...` compared to box annotations `class x y w h`.

You can see an example of these annotations in COCO128-seg:
https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128-segments.zip

And also train on quickly with
```
python segment/train.py --data COCO128-seg.yaml
```

Note that these labels were produce by https://github.com/ultralytics/JSON2YOLO starting from COCO JSON format segmentation labels.

**Comment by barney2074** [comment]
> is there some open source program for labeling the images

take a look at fiftyone/label studio/CVAT
https://voxel51.com/docs/fiftyone/integrations/labelstudio.html
https://voxel51.com/docs/fiftyone/integrations/cvat.html

Fiftone is quite sophisticated & there is a bit of a learning curve, but it is good for reviewing images & annotations, or importing/exporting data. Label Studio or CVAT by themselves are fairly straightforward.

**Comment by JoeNan1** [comment]
@glenn-jocher  How to convert mask. png to data in the form of. json or. txt? At present, there are a large number of data sets whose labels are mask. png.Thanks

**Comment by hdnh2006** [comment]
Thanks @glenn-jocher , you are always awesome.

**Comment by glenn-jocher** [comment]
@JoeNan1 not sure. We don't have one ourselves for segment predictions yet, but I'm sure cv2 or numpy or maybe scikit have a binary mask to segment outline function. Other users haves asked for the same, i.e. for --save-txt labels on segmentation predictions.

**Comment by glenn-jocher** [comment]
@JoeNan1 not sure. We don't have one ourselves for segment predictions yet, but I'm sure cv2 or numpy or maybe scikit have a binary mask to segment outline function. Other users haves asked for the same, i.e. for --save-txt labels on segmentation predictions.

**Comment by glenn-jocher** [comment]
@JoeNan1 maybe something like this:
https://scikit-image.org/docs/stable/api/skimage.segmentation.html#skimage.segmentation.find_boundaries

**Comment by glenn-jocher** [comment]
Or https://docs.opencv.org/4.1.1/d3/dc0/group__imgproc__shape.html#gadf1ad6a0b82947fa1fe3c3d497f260e0

**Comment by ryouchinsa** [comment]
You can convert the mask png file to polygons.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/mask2polygons.py

You can use Labelme to label polygons, convert to the COCO format,  and convert to the YOLO format.
https://github.com/wkentaro/labelme
https://github.com/ultralytics/JSON2YOLO

[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel, you can read/write/export the YOLO segmentation format.
```
class_index x1 y1 x2 y2 x3 y3 ...
0 0.180027 0.287930 0.181324 0.280698 0.183726 0.270573 ...
```

![yolo_polygon](https://user-images.githubusercontent.com/1954306/209943066-4d59c46c-2fb6-4a03-b023-f7ff340a3a32.jpg)

**Comment by glenn-jocher** [comment]
Thank you for sharing these resources, @ryouchinsa! This will definitely be helpful for users looking to convert mask png files to polygons for segmentation labeling. Your contributions are invaluable to the YOLO community!
