### ISSUE TITLE
I need copy from old version of Yolo v5

### ISSUE THREAD

**Issue by malareeqi** [ultralytics/yolov5#9553]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear sir, i need to get copy from old version (September 2021) of Yolov5,specifically the files models folder (common ,yolo,yolov5s),thank you so much

**Comment by glenn-jocher** [comment]
You can checkout any commit or release after got clone with the git checkout command
