### ISSUE TITLE
Do you have result map：50 of voc07+12？

### ISSUE THREAD

**Issue by wch243294382** [ultralytics/yolov5#9557]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Do you have result map：50 of voc07+12？

**Comment by glenn-jocher** [comment]
See https://wandb.ai/glenn-jocher/YOLOv5_VOC_official for VOC training results
