### ISSUE TITLE
thanks for your working when i see mixcond in experimental.py . i want to use it in yolov5. so how can i use it. 

### ISSUE THREAD

**Issue by Alex-afka** [ultralytics/yolov5#956]

**Comment by glenn-jocher** [comment]
MixConv() is just a type of conv layer like any other, you can swap any existing Conv() layers etc with MixConv() layers.

**Comment by Alex-afka** [comment]
I set [-1,1,mixconv,[32,[1,3],1] i dont know how to set K value because it is different about dwconv or ghostconv . can you give me a example for mixconv

**Comment by Alex-afka** [comment]
> MixConv（）只是任何其他conv图层的一种，您可以将任何现有的Conv（）图层等与MixConv（）图层交换。

**Comment by glenn-jocher** [comment]
See mixconv publication: https://arxiv.org/pdf/1907.09595.pdf

**Comment by Alex-afka** [comment]
I set [-1,1,mixconv,[32,[1,3],1] i dont know how to set K value because it is different about dwconv or conv .so can you give me a example for mixconv . thank you for your working .
