### ISSUE TITLE
How can I find the original fasret_R_CNN code in GOOGLE COLAB?

### ISSUE THREAD

**Issue by soleymany** [ultralytics/yolov5#9561]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone, I used GOOGLE COLAB for YOLOV5 and used the link below..
( https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb ,
https://github.com/ultralytics/yolov5 )
According to the training of this network, I trained the network according to the data of the main YOLO network. Only the test data was from me and I gave the test data and got the output from Yolo. Now for FASTER R_CNN, I want to train and test the FASTER R_CNN network in my COLAB, but unfortunately I cannot find the link of this FASTER R_CNN program in COLAB. please guide me.

### Additional

NO

**Comment by glenn-jocher** [comment]
@soleymany hi there! YOLOv5 focuses on the YOLO (You Only Look Once) object detection algorithm, not Faster R-CNN. For Faster R-CNN, I recommend checking out the original implementation on GitHub or looking for resources that specifically cater to Faster R-CNN. If you have any YOLOv5-related questions or need assistance, feel free to ask! Good luck with your Faster R-CNN endeavors.
