### ISSUE TITLE
How can I see top 5 predictions?

### ISSUE THREAD

**Issue by selimdizer** [ultralytics/yolov5#9564]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I use torch.hub.load("ultralytics/yolov5", 'custom', 'yolov5s.pt') but it only gives the best class name for the result of this model(results.pandas().xyxy[0]). I want to see best 5 class name. How can I do ?

**Comment by glenn-jocher** [comment]
@selimdizer you'd have to customize the code starting from NMS onward, not available off the shelf.

**Comment by davidamacey** [comment]
@selimdizer and @glenn-jocher  I submitted a [PR](https://github.com/ultralytics/yolov5/pull/9582) for a potential solution to this question.

Hopefully this is helpful for your project!

**Comment by selimdizer** [comment]
@glenn-jocher thank you for answering.

**Comment by selimdizer** [comment]
@davidamacey thank you very much for your help,I am grateful.

**Comment by davidamacey** [comment]
@selimdizer You are welcome.  Good luck with your project!
