### ISSUE TITLE
Training speed issue

### ISSUE THREAD

**Issue by Katana-O** [ultralytics/yolov5#9568]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/79778115/192092423-a81b01dd-0681-464c-b927-f6b7b8cfb9bf.png)
![image](https://user-images.githubusercontent.com/79778115/192092452-41378b4e-bf58-4134-9f5e-77ae072137c4.png)
![image](https://user-images.githubusercontent.com/79778115/192092468-e89e84f2-699e-4680-93a6-02ee4083c627.png)
![image](https://user-images.githubusercontent.com/79778115/192092598-b207ffbd-cb9e-4b52-bf96-4b7d6d3a5d94.png)

Hi dev at YoloV5, these 4 pictures tell you about some details about my environment.
GPU: NVIDIA GeForce GTX 1080 Ti, 11175MiB
OS: Ubuntu 20
Number of Images need to be train: 9
Number of Class: 1
Pretrained Model: No

In my circumstance, I can tell it would take more than an hour to finish the training procedure. I have two questions.
1: I'm very new to this project, so I am wondering is it possible to reduce time consuming by tinkering some argument? 
2: What is your estimated time of training if you have 9 images and 1 class.

**Comment by glenn-jocher** [comment]
@Katana-O it pretty clearly shows you have 1169 validation images, so 9 training images is irrelevant to your time if you have 1000 validation images.

**Comment by glenn-jocher** [comment]
@Katana-O for standard train times on a common dataset see Colab:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

<img width="1442" alt="Screenshot 2022-09-24 at 20 03 16" src="https://user-images.githubusercontent.com/26833433/192112320-509d1011-757d-4a83-bc57-7f71b281d98d.png">
