### ISSUE TITLE
Why `anchors` in VOC.yaml is not int?

### ISSUE THREAD

**Issue by Nioolek** [ultralytics/yolov5#9575]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I think the para `anchors` means number of anchors per layer. I think it must should be int. BUT, in VOC.yaml it is 3.412, and it is rounded in `yolo.py`. I hope i can know the reason.

**Comment by glenn-jocher** [comment]
@Nioolek evolution VOC hyp yaml shows anchor as a float rather than an int because evolution treats all values as floats. When used for anchor numbers it is rounded though, so the hyp will generate 3 anchors per output grid.
