### ISSUE TITLE
What are the cls and obj hyperparameters  

### ISSUE THREAD

**Issue by ZePinto99** [ultralytics/yolov5#9592]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was comparing the hyperparameters on the hyp.scratch-low.yaml and hyp.scratch-high.yaml and noticed that the following hyperparameters change between files.

hyp.scratch-low.yaml:                                                        
cls: 0.5  # cls loss gain  					               
obj: 1.0  # obj loss gain (scale with pixels)

hyp.scratch-high.yaml:
cls: 0.3  # cls loss gain
obj: 0.7  # obj loss gain (scale with pixels)		       

What is definition of this hyperparameters and why do they change between low and high augmentation?

**Comment by glenn-jocher** [comment]
@ZePinto99 these are classification and objectness loss gains. They are reduced for larger models to improve performance.
