### ISSUE TITLE
model = torch.hub.load('ultralytics/yolov5', 'yolov5s-seg')

### ISSUE THREAD

**Issue by mohamed-29** [ultralytics/yolov5#9593]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

is there yolov5 segmentation model ?

**Comment by glenn-jocher** [comment]
@mohamed-29 yes, segmentation models were recently introduced. You can load one with the code below, but they are not yet fully supported for PyTorch Hub inference, so I'd recommend using the usage examples in segment/predict.py:
https://github.com/ultralytics/yolov5/blob/master/segment/predict.py

```
import torch

model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s-seg.pt')
````

**Comment by mohamed-29** [comment]
KeyError                                  Traceback (most recent call last)
Input In [11], in <cell line: 6>()
      1 results = model(img)
      3 #results.show()
      4 
      5 # Results
----> 6 results.show()

File ~/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:776, in Detections.show(self, labels)
    775 def show(self, labels=True):
--> 776     self._run(show=True, labels=labels)

File ~/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:737, in Detections._run(self, pprint, show, save, crop, render, labels, save_dir)
    735 for c in pred[:, -1].unique():
    736     n = (pred[:, -1] == c).sum()  # detections per class
--> 737     s += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "  # add to string
    738 s = s.rstrip(', ')
    739 if show or save or render or crop:

KeyError: 94

**Comment by glenn-jocher** [comment]
@mohamed-29 SegmentationModel and ClassificationModel types are not yet supported by YOLOv5 PyTorch Hub AutoShape models. I will add a warning to notify users.

**Comment by glenn-jocher** [comment]
@mohamed-29 good news 😃! Your original issue may now be improved ✅ in PR #9632. This PR adds a warning to users to notify them that SegmentationModels are not yet fully supported.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by rusvagzur** [comment]
Hi @glenn-jocher , do you an estimation on when segmentation inference will be supported for pytorch hub? Thanks!

**Comment by glenn-jocher** [comment]
@rusvagzur no, I'm sorry. If you'd like to contribute a PR for this that would be great!  

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
