### ISSUE TITLE
How to draw multiline text on detected object?

### ISSUE THREAD

**Issue by be-nice-do-better** [ultralytics/yolov5#9594]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I see `Annotator.box_label` function draws one line text, how to draw multiline text?
For example, instead of drawing text "_person 0.98_" in one line,, how to draw the text in multiline start from the top left corner of the detected object, i.e.,:
_person
0.98_

one line text:
![image](https://user-images.githubusercontent.com/12386794/192180260-362261ab-2e95-4182-be56-0812b226fcac.png)

would like to draw text as the below multiline format:
![image](https://user-images.githubusercontent.com/12386794/192180661-f3dbf122-0d1c-4f0f-82c6-4cc8f1ea1621.png)

**Comment by glenn-jocher** [comment]
@wujoho see classify/predict.py for an example of multi-line annotation:
```
python classify/predict.py
```

**Comment by wujoho** [comment]
@glenn-jocher  thank you, it works 👍

**Comment by glenn-jocher** [comment]
![image](https://user-images.githubusercontent.com/26833433/192242686-8a3e7267-8e91-44c1-9848-f2fceea7fa53.png)
