### ISSUE TITLE
Multiple detections when using mps

### ISSUE THREAD

**Issue by lightonthefloor** [ultralytics/yolov5#9601]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

When running on --source 0, there are multiple detections.
![Uploading 截屏2022-09-26 20.48.03.png…]()

### Environment

- python 3.10.4
- torch-1.13.0.dev20220926 MPS
- command is PYTORCH_ENABLE_MPS_FALLBACK=1 python detect.py --device mps --source 0 --weights yolov5m6.pt

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lightonthefloor** [comment]
<img width="1505" alt="截屏2022-09-26 20 48 03" src="https://user-images.githubusercontent.com/34955669/192280783-e5c66e72-d462-4a09-af94-e81801141b2d.png">

**Comment by lightonthefloor** [comment]
Oops, and my detections of demo is right.
![bus](https://user-images.githubusercontent.com/34955669/192282241-ea225855-e5f4-4746-b85b-856f903046cf.jpg)

**Comment by glenn-jocher** [comment]
@lightonthefloor are you sure? I get incorrect results on MPS, even though MPS inference runs without error.

<img width="1346" alt="Screenshot 2022-09-26 at 15 02 42" src="https://user-images.githubusercontent.com/26833433/192283525-99b85fc5-ef5e-4d01-9ab4-2c7405b2dbcc.png">

**Comment by lightonthefloor** [comment]
Sorry, I check again. I get the correct answer when I run on cpu.

**Comment by ehallein** [comment]
FYI another detector [https://github.com/microsoft/CameraTraps](https://github.com/microsoft/CameraTraps) which uses YOLOv5 works on MPS with GPU acceleration with no issues, so it appears detect.py may be the issue, not PyTorch.

**Comment by jgoo9410** [comment]
Also having this issue, was any progress made in finding the cause @lightonthefloor?
