### ISSUE TITLE
How to disable caching completely on a custom dataset

### ISSUE THREAD

**Issue by AndreiBarsan** [ultralytics/yolov5#9602]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I am training YOLO on a custom 40k image dataset for a personal project. I noticed that the training tool wants to cache the dataset in RAM. I only have 64GB so this does not work (a ~30k one fit just barely). 

However, it seems that the only option is disk caching, i.e., I can’t disable it. If I don't pass any `--cache` argument, RAM caching is used and my training goes OOM. If I specify `disk`, it's slow and wastes disk space. If I pass `None` or gibberish to `--cache`, it still tries to cache in RAM and I OOM.

My dataset consists of JPEG images at 90% quality. The caching stores them at numpy bitmaps, taking up nearly 10x the space. Thus using the cache for IO is very likely slower than just decoding the original JPEGs since decoding JPEGs is fast and they require less time to read from the disk.

How can I force YOLO to disable all caching?

Thank you!

**Comment by glenn-jocher** [comment]
Caching is not enabled by default. You’ve enabled it by using the —cache argument.

**Comment by AndreiBarsan** [comment]
Thank you for the quick response. The root cause of this was my training going OOM even before specifying `--cache` at all, which led me to think RAM caching was on by default, which is an incorrect assumption.

My solution was to make sure old Python processes had been killed so that they don't hog memory. I regenerated my dataset and the problem no longer happens, so it was probably a transient issue. I also [increased my swap size to 64G](https://linuxhint.com/increase-swap-space-linux/) for good measure, but that's probably overkill.

Thanks again for the reply. Really like working with the YOLO code base!!

**Comment by glenn-jocher** [comment]
@AndreiBarsan glad to hear that the issue is resolved! If you have any more questions or run into any other issues, feel free to ask for help. Also, any praise should go to the YOLO community and the Ultralytics team for their hard work. Happy coding!
