### ISSUE TITLE
Using a segmentation model with OpenVINO?

### ISSUE THREAD

**Issue by GiovanniNova** [ultralytics/yolov5#9605]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Trying to load a segmentation model with OpenVINO throws

`    ppp.output().tensor().set_element_type(Type.f32)
RuntimeError: Check 'm_impl->m_outputs.size() == 1' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\src\preprocess\pre_post_process.cpp:125:
PrePostProcessor::output() - Model must have exactly one output, got 2`

I know segmentation in Yolo is relatively new, but is it expected to work on OpenVINO? if so how?

I'm using the code available at https://github.com/dacquaviva/yolov5-openvino-cpp-python/tree/main/python

### Additional

I coudn't get any of my models to work on ONNX

**Comment by glenn-jocher** [comment]
@GiovanniNova SegmentationModel types export correctly to OpenVINO and all other formats, and are validated every 24 hours and on every commit via YOLOv5 CI benchmarks:

https://github.com/ultralytics/yolov5/actions/runs/3124263935/jobs/5067458928
<img width="1026" alt="Screenshot 2022-09-26 at 17 04 17" src="https://user-images.githubusercontent.com/26833433/192312365-1f2f6da9-8fab-4c03-a914-023721ef3da7.png">

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by GiovanniNova** [comment]
Thank you for answering, yes the model exports correctly, but the example provided on running inference fails, I'm not using segmentation anymore but it would be interesting to know how to get it working with the code at https://github.com/dacquaviva/yolov5-openvino-cpp-python/tree/main/python

**Comment by glenn-jocher** [comment]
@GiovanniNova the code you are pointing to is not by Ultralytics and is outside the scope of our support. I'd recommend asking the code author. 

To run YOLOv5 OpenVINO models using this repo see the Usage examples provided upon export, i.e.:
<img width="812" alt="Screenshot 2022-09-26 at 18 48 54" src="https://user-images.githubusercontent.com/26833433/192334890-43eda743-e997-4300-8a34-fc73d9c91cc2.png">
