### ISSUE TITLE
setting a different mAP threshold during val

### ISSUE THREAD

**Issue by GNuzzarello** [ultralytics/yolov5#9606]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I would like to know if it is possible to set a different mAP threshold using val.py. 
In particular, I want that an example is considered as a true positive even if the intersection is minimal (ideally even 0.1). Thanks

**Comment by glenn-jocher** [comment]
@GNuzzarello yes this is the point of the different IoU thresholds use for mAP50 and mAP50-95. These ten IoU thresholds are defined here:
https://github.com/ultralytics/yolov5/blob/c4c0ee8fc35937cfa940fdaaaf6b9660f5b355f5/val.py#L162

**Comment by Taoudi** [comment]
The proposed solution does not seem to work when evolving. After changing k to 0.75 my validation metrics reflect those of mAP@0.5 during evolution.
