### ISSUE TITLE
Why can not use video to detection?

### ISSUE THREAD

**Issue by Yolobeginner** [ultralytics/yolov5#9615]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I use picture to detection is working well,Every picture can detect around 0.008ms
But I use video to detect it can not work!
Somebody know what's going on?
That error message as following :
 
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by sezer-muhammed** [comment]
hi, what were your video's res, extension, and other info?

**Comment by glenn-jocher** [comment]
@Yolobeginner video works well for me, i.e.:
```
!python detect.py --source  https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_portrait.mov
```

<img width="1197" alt="Screenshot 2022-09-27 at 17 02 41" src="https://user-images.githubusercontent.com/26833433/192563111-ef0d8253-6035-4742-829c-476b803e2950.png">
