### ISSUE TITLE
Saving video when running multiple sources at the same time

### ISSUE THREAD

**Issue by joesouaidd** [ultralytics/yolov5#9618]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Greetings, I am trying to run detect.py on multiple sources using a txt file "sources.txt" which contains 2 youtube videos link, the code will run, and objects are detected, but when I press q the code will exit, but it will not save the run. How can I save the output of each source?

**Comment by glenn-jocher** [comment]
python detect.py --save-txt

**Comment by joesouaidd** [comment]
Thank you for your reply, I tried it and it got saved as text files with the coordinates of the object, I want to save the multiple streams as videos, just like detect.py would normally do for a run with a video source. 
Example : python detect.py --classes 32  --img 640 --conf 0.5 --source video.mp4    (this one saves the resulting video with its detection)
but now it is like python detect.py --classes 32  --img 640 --conf 0.5 --source sources.txt (this one does not saves the resulting videos)

**Comment by glenn-jocher** [comment]
You might try setting save_img=True in detect.py

**Comment by joesouaidd** [comment]
Worked, Thank you! @glenn-jocher

**Comment by glenn-jocher** [comment]
@joesouaidd you're welcome! Happy to help! 😊 The YOLO community and the Ultralytics team are continually improving the YOLOv5 experience. If you have any more questions, feel free to ask!
