### ISSUE TITLE
[Torch] Where is non-max suppression?

### ISSUE THREAD

**Issue by adimux** [ultralytics/yolov5#9619]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi I'm observing low GPU utilization periodically during the optimize step.

I know that non-max suppression is hard to scale on GPUs so it usually runs on CPUs, so I was wondering if that's the explanation for low GPU utilization?

Also I was not able to find the code for non max suppression in the [PyTorch implementation](https://github.com/ultralytics/yolov5/blob/master/models/yolo.py).
Can you point me to the section of the code that takes care of that?

**Comment by hardikdava** [comment]
@adimux you can find implementation of non maximum suppression [here](https://github.com/ultralytics/yolov5/blob/7314363f26e23fc831a9a739b4031f9f0217084a/utils/general.py#L826)

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!
