### ISSUE TITLE
AttributeError: 'Detections' object has no attribute 'imgs'

### ISSUE THREAD

**Issue by aliaminibagh** [ultralytics/yolov5#9621]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

when I act as : 
```
@app.post("/object-to-img")
async def detect_gun_return_base64_img(file: bytes =  File(...)):
    input_image = get_image_from_bytes(file)
    results = model(input_image)
    results.render()  # updates results.imgs with boxes and labels
    for img in results.imgs:
        bytes_io = io.BytesIO()
        img_base64 = Image.fromarray(img)
        img_base64.save(bytes_io, format="jpeg")
    return Response(content=bytes_io.getvalue(), media_type="image/jpeg")
```
I wanna show result image with bounding boxes on it.
it up an error : 
```
 for img in results.imgs:

AttributeError: 'Detections' object has no attribute 'imgs'
```

I have another app exactly like this but it work. It's yolov5 version is : 
`YOLOv5  27eef7d torch 1.9.1+cpu CPU`

but in this new fastapi service the version of yolov5 which is clone is : 
`YOLOv5  v6.2-177-g2373d54 Python-3.9.12 torch-1.9.1+cpu CPU`

is this important?
when I copy oldest version yolov5 directory in new project, it does not work too.
What I do ? 

### Environment

- YOLOv5  v6.2-177-g2373d54 Python-3.9.12 torch-1.9.1+cpu CPU
- YOLOv5  27eef7d torch 1.9.1+cpu CPU

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aliaminibagh results.imgs has been renamed to results.ims

**Comment by aliaminibagh** [comment]
> @aliaminibagh results.imgs has been renamed to results.ims

thanks. it works now

**Comment by sanjuth** [comment]
> @aliaminibagh results.imgs has been renamed to results.ims

@app.post("/object-to-img")
async def detect_return_base64_img(file: bytes = File(...)):
    input_image = get_image_from_bytes(file)
    results = model(input_image)
    print(results)
    results.render()  
    for img in results.ims:
        bytes_io = io.BytesIO()
        img_base64 = Image.fromarray(img)
        img_base64.save(bytes_io, format="jpeg")
    return Response(content=bytes_io.getvalue(), media_type="image/jpeg")


hey I am trying to receive the response from this route to my react application but I am not able to find out which format the response is.
how do I receive an image from this route.
![Screenshot 2022-11-02 203524](https://user-images.githubusercontent.com/78399043/199525565-ed745ccc-557a-4deb-86e2-f7123a47362f.jpg)
