### ISSUE TITLE
something regarding yolov5l data is error as the picture

### ISSUE THREAD

**Issue by lixiangMindSpore** [ultralytics/yolov5#9625]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/78945582/192677990-5f18cbcc-83b3-442b-b901-aa59f18e6946.png)
something regarding yolov5l data is error, 
as the first picture, Speed CPU b1is 424.5, Speed V100 b1 is 10.9,
however, as the second picture, Speed CPU b1is 430, Speed V100 b1 is 10.1,
what's wrong?

**Comment by glenn-jocher** [comment]
@lixiangMindSpore thank you, yes you are right there was a mistake! I've corrected now.
