### ISSUE TITLE
Train.py AttributeError: 'ClassificiationModel" object has no attribute 'yaml'

### ISSUE THREAD

**Issue by ByunHyuckJoon** [ultralytics/yolov5#9626]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi, there's some issue when i run the train.py 

when i run the code

like python train.py --img 640 --batch 16 --epochs 80 --data 'data/VOC.yaml' --weights 'models/yolov5l-cls.pt' --device 0

below code error occurs what could be the solve the problems

### Environment

- YOLO: YOLOv5 🚀 2022-9-28 Python-3.8.13 torch-1.12.1+cu102
- Python: 3.8.13
- OS : CentOS 7

### Minimal Reproducible Example

Traceback (most recent call last):
  File "train.py", line 630, in <module>
    main(opt)
  File "train.py", line 526, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 123, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/hdd_data/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
**AttributeError: 'ClassificationModel' object has no attribute 'yaml'**

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ByunHyuckJoon you're trying to train a classification model with a detection script. If you want to start training a detection model then you must specify a detection model either as pretrained weights or as a --cfg to build from.
