### ISSUE TITLE
when should exp folders get created, model training for many epochs withought an exp folder ebing produced

### ISSUE THREAD

**Issue by Aya-S** [ultralytics/yolov5#963]
## ❔Question

I currently have 11 exp folders under runs( exp0 -exp10)
training has been going on for more than 10 epoch without additional exp folders being produced.

I'm confused as to when exp is produced as the behavior doesn't seem consistent

**Comment by glenn-jocher** [comment]
@Aya-S a new runs/exp directory is created when you start a new training.
