### ISSUE TITLE
Training Speed of Objects365 datasets

### ISSUE THREAD

**Issue by Stephen-Hao** [ultralytics/yolov5#9631]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question
Dear glenn,

When I train Object365 dataset, the training speed is slow on a 8 * 3090 machine.
my shell such as:

python -m torch.distributed.run --nproc_per_node 8 train.py 
--batch-size 128 
--workers 8 
--epochs 120
--weights ' ' --cfg 'models/yolov5x.yaml'
--hyp 'data/hyps/hyp.scratch-high.yaml'
--cache disk  --data 'data/Objects365.yaml'
--img 640 
--device 0,1,2,3,4,5,6,7

![image](https://user-images.githubusercontent.com/35420905/192768636-8806c6c4-5e82-4f47-b636-cde86897b23f.png)
How can I solve the problem? Thanks a lot.

**Comment by glenn-jocher** [comment]
@Stephen-Hao your command looks good. In our training we trained Objects365 to about 30 epochs with YOLOv5m6 in about 2 days with 8x A100.

If your utilization is low your resources may be saturated. You need at least 96 vCPUs for --workers 8 (each device will use 8 workers).

Also if IOps or read is limited on your hard drive the --cache disk may actually slow down your training, so try with and without --cache disk.

**Comment by Stephen-Hao** [comment]
> @Stephen-Hao your command looks good. In our training we trained Objects365 to about 30 epochs with YOLOv5m6 in about 1-2 days with 8x A100.
> 
> If your utilization is low your resources may be saturated. You need at least 96 vCPUs for --workers 8 (each device will use 8 workers).
> 
> Also if IOps or read is limited on your hard drive the --cache disk may actually slow down your training, so try with and without --cache disk.

I see! Thank you very much!

**Comment by buxihuo** [comment]
@Stephen-Hao 这一套训练设置，感觉至少半个月

**Comment by zhangyichent** [comment]
@Stephen-Hao 请问worker后来改了速度快了吗，改的多少？我也遇到一样的问题了，速度上不去。

**Comment by wangsun1996** [comment]
> ### Search before asking
> 
>     * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> 
> ### Question
> 
> Dear glenn,
> 
> When I train Object365 dataset, the training speed is slow on a 8 * 3090 machine. my shell such as:
> 
> python -m torch.distributed.run --nproc_per_node 8 train.py --batch-size 128 --workers 8 --epochs 120 --weights ' ' --cfg 'models/yolov5x.yaml' --hyp 'data/hyps/hyp.scratch-high.yaml' --cache disk --data 'data/Objects365.yaml' --img 640 --device 0,1,2,3,4,5,6,7
> 
> ![image](http://user-images.githubusercontent.com/35420905/192768636-8806c6c4-5e82-4f47-b636-cde86897b23f.png) How can I solve the problem? Thanks a lot.
> ### Additional
> 
> _No response_

Could you provide a yolov5.pt on object365(such as yolov5s/yolov5s6/or other on obj365 dataset)?Thank you very much!

**Comment by wangsun1996** [comment]
> @Stephen-Hao 请问worker后来改了速度快了吗，改的多少？我也遇到一样的问题了，速度上不去。

您这边有能提供的在object365上训练好的权重文件吗？yolov5s或者yolov5s6等？
