### ISSUE TITLE
Videos been only partially processed with default detect.py

### ISSUE THREAD

**Issue by jelexpuru** [ultralytics/yolov5#9633]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hi!

I was trying if I could run the detect.py script out of the box with some videos that we had.
When executing it with the following parameters

`python detect.py --device 0 --source "C:\...\GH013844.MP4" --save-txt --save-conf --save-crop`

we obtain the following log and a video of the proportional time (less than a second instead of 14):

![image](https://user-images.githubusercontent.com/107612276/192802682-70cd7182-954a-4236-a864-f2612f425198.png)

![image](https://user-images.githubusercontent.com/107612276/192803318-1da19377-9745-4b00-a8eb-d13bc898b3c2.png)

When trying the same with other similar videos the proportion is quite similar (around a 5% of the video). We've found this issue both with CPU and GPU.

We haven't made any modification on the original code and after diving on it for a while, we neither have found any reason for this behaviour. We also haven't seen any issue like this open.

### Environment

-YOLO: Yolov5 6.2
-OS: Windows 10
-Python: Python 3.9.13
-Torch: torch1.12.1

Input video format: 1280x960 120FPS
Codec: H264-MPEG-4 AVC

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jelexpuru thanks for the bug report! I've not seen any behavior like this. It may be a bug in cv2 when reading your videos. The default video we use for debugging is here, it's 1 second long. It processes "29/31" frames. Not sure why there is a mismatch.
```
!python detect.py --source https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_portrait.mov
```

<img width="828" alt="Screenshot 2022-09-28 at 16 47 35" src="https://user-images.githubusercontent.com/26833433/192810555-5946a61e-dc78-446e-bc50-3e1b8bc4882f.png">

**Comment by jelexpuru** [comment]
> @jelexpuru thanks for the bug report! I've not seen any behavior like this. It may be a bug in cv2 when reading your videos. The default video we use for debugging is here, it's 1 second long. It processes "29/31" frames. Not sure why there is a mismatch.
> 
> ```
> !python detect.py --source https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_portrait.mov
> ```
> 
> <img alt="Screenshot 2022-09-28 at 16 47 35" width="828" src="https://user-images.githubusercontent.com/26833433/192810555-5946a61e-dc78-446e-bc50-3e1b8bc4882f.png">

Thank you so much for the quick reply.

As a fact, before getting theese results i had an error concerning cv2 which caused an exception. After uninstalling and making a clean install it did work, but as shown above. I'll check again anything corcening cv2 just in case.

Just in case, it's 29/31 a expected result in your case? Could be cases where not all the video should be processed?

**Comment by glenn-jocher** [comment]
@jelexpuru I tried on our second benchmark video, a landscape version, and this one correctly processes 31/31 frames. Very strange. If you find any bugs or solutions please let us know.
```
!python detect.py --source https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_landscape.mov
```

<img width="855" alt="Screenshot 2022-09-28 at 17 04 31" src="https://user-images.githubusercontent.com/26833433/192814895-3458d7de-e1ea-4649-bc9d-8eaa3c638b4b.png">

**Comment by glenn-jocher** [comment]
@jelexpuru BTW, recent versions of OpenCV may have a video orientation bug, but I think this is a separate topic/issue and unrelated to this discussion.
