### ISSUE TITLE
why using detect.py use more power  than  PyTorch Hub  ?

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#9638]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i calculate the time of video detection unsing normal detect.py file and using  PyTorch Hub  ,
 PyTorch Hub has  less power (eleictric power ). and it more faster 
using Detect.py 

![WhatsApp Image 2022-09-23 at 4 42 31 AM](https://user-images.githubusercontent.com/23275255/192857195-3def3a5f-539e-43bf-8943-d0478cbc1ce4.jpeg)

using  PyTorch Hub 

![WhatsApp Image 2022-09-28 at 12 29 47 AM](https://user-images.githubusercontent.com/23275255/192857260-5df16273-971e-401e-8fc1-35fd95a2616c.jpeg)

**Comment by glenn-jocher** [comment]
@totoadel very interesting, thanks for the info! This may be because detect.py is saving inference results by default typically, while pytorch hub only does this on demand with results.save()

**Comment by totoadel** [comment]
@glenn-jocher , I stop any saving, I just do detection, and stop viewing also, for both

**Comment by glenn-jocher** [comment]
@totoadel maybe something about the pytorch dataloader then, which is absent from pytorch hub.

**Comment by totoadel** [comment]
@glenn-jocher I think the thread that in dataloader , i put print order on and I found a loop is running a lot i
While running the detection,

**Comment by glenn-jocher** [comment]
@VYRION-Ai Oh, I see! It's possible that the dataloader is causing the additional power consumption due to repeated iterations over the dataset. You may want to check the dataloader implementation and see if there are any opportunities to optimize it for inference. Feel free to reach out if you need further assistance!
