### ISSUE TITLE
Data behind Confusion Matrix

### ISSUE THREAD

**Issue by cool112624** [ultralytics/yolov5#9640]
### Discussed in https://github.com/ultralytics/yolov5/discussions/9635

<div type='discussions-op-text'>

<sup>Originally posted by **cool112624** September 28, 2022</sup>
Hi, I want reduce False Negative on confusion matrix of a model that I train

So I want to know which data is causing the false negative prediction so can I anywhere export the data that represent in each square of confusion matrix

like how can I get the data that are in this red square?

Thank you in advance 
![confusion_matrix](https://user-images.githubusercontent.com/51593747/192916317-2f3566e8-4c40-47b2-a089-31b6b969e3b7.png)
</div>

**Comment by glenn-jocher** [comment]
@cool112624 you can access the confusion matrix code right here. We don't output metrics per image, but we have in our product roadmap. This should allow you to see the worse performing images directly.

https://github.com/ultralytics/yolov5/blob/799e3d0cc92a9f431d97931641e7d0b46720699a/utils/metrics.py#L126-L223

**Comment by cool112624** [comment]
@glenn-jocher Hi, I get it, thank you
but I am new to python and yolov5, do you mind helping me by explain more detail on how to do it ?
very appreciate, thank you in advance

**Comment by cool112624** [comment]
@glenn-jocher Hi, can you help me with it?

**Comment by glenn-jocher** [comment]
@cool112624 you have to put breakpoints in the code there and handle the values however you want, i.e. save them or return them etc.

**Comment by cool112624** [comment]
I found another way by using val.py 
I changed the number of output images on val.py and plot.py so that I get all my datasets validation output I compare one by one to get which is fp or tp, althought this sound stupid

**Comment by glenn-jocher** [comment]
@cool112624 that's a straightforward workaround! If you prefer a more direct method, you can try adding code in the validation loop of val.py to save false positive and false negative images. However, your approach works as well. Good luck with your analysis!
