### ISSUE TITLE
About tfjs format export

### ISSUE THREAD

**Issue by wrsnice** [ultralytics/yolov5#9642]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I modified the backone and head part of yolov5s, when I finish training the model, Can I continue to export tfjs model via `export.py`?

**Comment by glenn-jocher** [comment]
@wrsnice yes you should be able to. If you have custom modules you will need to redefine these in TF in models/tf.py also though for TF export.
