### ISSUE TITLE
How do I find all the confidence values?

### ISSUE THREAD

**Issue by selimdizer** [ultralytics/yolov5#9648]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Yolo produces the best confidence value for each object, but I also need other confidence values. How can I do that?

![image](https://user-images.githubusercontent.com/82811657/193062262-f7b59794-4155-46fb-8956-5ee6a4058b9a.png)

I want to see other confidance and classes of detected objects.

**Comment by selimdizer** [comment]
![image](https://user-images.githubusercontent.com/82811657/193060280-ce5dec5d-bcc3-4062-ad2d-509be72c783d.png)

**Comment by selimdizer** [comment]
I want to see other confidance and classes of detected objects.

**Comment by glenn-jocher** [comment]
@selimdizer hey there!

To get all confidence values and classes of detected objects in YOLOv5, you can refer to the `pred` object returned by the model. It contains various attributes such as `pred[0]['confidence']` and `pred[0]['class']` which provide access to the confidence values and classes respectively.

You can find detailed information on accessing these attributes and more in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.

Let me know if you need further assistance!
