### ISSUE TITLE
Epoch status messages

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/yolov5#9659]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

It would be helpful if the 'training' epoch status display would print the elapsed time per epoch.
Stretch goal would be an ETA for the training run based on the number of epochs.
Not sure tqdm could be used for the entire training request, which would cover it.

The tqdm times display do not appear to represent the entire epoch cycle.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@apiszcz you can use Ultralytics HUB to train YOLOv5 models with additional features like ETAs:
https://hub.ultralytics.com
<img width="1492" alt="Screenshot 2022-10-01 at 16 49 38" src="https://user-images.githubusercontent.com/26833433/193415194-9dfb6093-f56b-4277-8df5-2af5095a7ef0.png">
