### ISSUE TITLE
About the different `pad` setting when initializing the test dataset in train.py and test.py

### ISSUE THREAD

**Issue by panhtt** [ultralytics/yolov5#966]
## ❔Question

In `train.py`, you don't set the `pad` parameter, so it will use the default `0.0`. But in `test.py`, you set `pad=0.5`. I think the correct value of `pad` should be `0.5` like in `test.py`, because it will discard some pixels when `pad=0.0`. Can you explain why you doing like this?

## Additional context
The test map results of `test.py` are always different from the results in training process. And I have checked out that the main and only difference is the `pad` setting.

**Comment by glenn-jocher** [comment]
@panhtt padding can only add area, never remove it.

**Comment by panhtt** [comment]
@glenn-jocher yes, you are right. It's my mistake. Thank you very much.

But I still suggest the setting of `pad` should be the same to output the same results in test process in `train.py` and `test.py`.

**Comment by glenn-jocher** [comment]
@panhtt yes, this a consideration when viewing training results in realtime. Testing a model directly with test.py will generally result in slightly better, and slightly slower, results than when testing as part of training.

The padding is omitted during training strictly for speed considerations.

**Comment by panhtt** [comment]
@glenn-jocher I see. Thank you for your reply.
