### ISSUE TITLE
I use subprocess to run Yolo command, do not see updated output

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/yolov5#9660]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,  I want to use subprocess

latestWeights = "last.pt"
cmd=f"python train.py --img 512 --batch 80 --epochs 600 --data data.yaml --weights {latestWeights} --cache  disk  --nosave"
subprocess.run(cmd, shell=true)

to equivalently  run command  this 
!python train.py --img 512 --batch 80 --epochs 600 --data data.yaml --weights last.pt --cache  disk  --nosave

It runs, but no updated output of progress. It is supposed to have continuous updated output.   I do not know if it run correctly without updated output.

**Comment by frabob2017** [comment]
It looks that subprocess will suppress the output update, but actually it run.

**Comment by glenn-jocher** [comment]
@frabob2017 hi there! It seems like the subprocess is indeed suppressing the output update, although the command is running in the background. To see the continuous output, you can try redirecting the standard output and error streams using `subprocess.Popen` with `stdout=subprocess.PIPE` and `stderr=subprocess.PIPE` and read the outputs in real-time. This should allow you to monitor the progress as the command runs. Let me know if you need further assistance!
