### ISSUE TITLE
Help please, I lose my previous training

### ISSUE THREAD

**Issue by athemsa** [ultralytics/yolov5#9663]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I don't understand, at each training I lose the previous ^^'
For example
First train i use :
python train.py --img 640 --batch 16 --epochs 300 --data dataset.yaml --hyp hyp.scratch.yaml --weights yolov5s.pt --workers 2 

and i have
![image](https://user-images.githubusercontent.com/46684763/193254662-abe81fd1-62db-4813-8339-5a46fda33dae.png)

Second train i use: 
python train.py --img 640 --batch 16 --epochs 300 --data dataset.yaml --hyp hyp.scratch.yaml --weights runs\train\exp\weights\best.pt --workers 2

![image](https://user-images.githubusercontent.com/46684763/193254763-41fb712b-1c54-44aa-8ddb-6b3806bea8a5.png)
i lost petdrake and impssible to detect him.

my dataset.yaml
![image](https://user-images.githubusercontent.com/46684763/193258990-44d991b1-0edf-4b48-bf86-b25445f3b030.png)

Can you help me please ? ^^'

**Comment by glenn-jocher** [comment]
See https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets/38/59

**Comment by athemsa** [comment]
thanks ^^

**Comment by glenn-jocher** [comment]
@athemsa you're welcome! If you have any more questions, feel free to ask. Good luck with your training!
