### ISSUE TITLE
How to train or detect other size images?

### ISSUE THREAD

**Issue by arkerman** [ultralytics/yolov5#9664]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi!
   I wanna trian the size of 2048*8800 pictures. And then ,i need to detect on the  2048*8800 pictures. So what should i do? Really look forward to your reply.

**Comment by glenn-jocher** [comment]
@arkerman you can train and detect at any image size using the --imgsz argument for train.py, detect.py

**Comment by arkerman** [comment]
@glenn-jocher  Thanks for your reply! But for one thing , the "-- imgz" can only pass in one value, not enough for the size of my image

**Comment by glenn-jocher** [comment]
@arkerman you can try two values, or if only one is accepted then pass largest dimension.
