### ISSUE TITLE
How can I use the results of the model?

### ISSUE THREAD

**Issue by Ryankim28** [ultralytics/yolov5#9665]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question
Hi!
First of all, please understand that the sentence may not be smooth because I'm foreigner who is not good at English.
I am a student who is working on a project using YOLOv5.
I understood YOLO's train and object detection but I'm having a hard time controlling YOLOv5 results.
The project I'm working on is to detect objects in real time, and I want to give you an event when it's detected, but I don't know what to do.
For example, if a dog appears while filming a video with a webcam, I will capture the image at that time and save it with the gps value. By the way, how should we handle the event in this part?
It's hard because this part hasn't been solved.
Thank you for reading this long message

**Comment by popcornkiller1088** [comment]
Please refer to https://github.com/ultralytics/yolov5/issues/36, after you train a model, you can use the API defined here to get the coordinate value for each detected object in bounding box: 
`
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Image
im = 'https://ultralytics.com/images/zidane.jpg'

# Inference
results = model(im)

results.pandas().xyxy[0]
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
`

**Comment by glenn-jocher** [comment]
@Ryankim28 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by Ryankim28** [comment]
When I studied based on your answers, I understood how the results of YOLO came out. However, can't we check the result value and control it while it's being processed in real time?
If I find an object in real time using Raspberry Cam, I want to use the result at that moment.

**Comment by glenn-jocher** [comment]
@Ryankim28 you can handle `results` at any time however you want.

**Comment by coleenestilo** [comment]
> # Results
> results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

hiii !! can u give the commands on the results like this? i'm trying to experiment on how I will show my results but I can't find the complete list of commands on the pytorch hub website. thank you!!!

**Comment by glenn-jocher** [comment]
Hello @jcsestilo! 👋

Absolutely, I'd be happy to help you with that. YOLOv5's `results` object provides several convenient methods to handle and display inference results. Here are some of the key methods you can use:

### Key Methods for Handling Results

1. **Print Results**:
   ```python
   results.print()  # Print results to the console
   ```

2. **Show Results**:
   ```python
   results.show()  # Display results on the screen
   ```

3. **Save Results**:
   ```python
   results.save()  # Save results to 'runs/hub' directory
   ```

4. **Crop Results**:
   ```python
   results.crop(save=True)  # Save cropped detections
   ```

5. **Pandas DataFrame**:
   ```python
   df = results.pandas().xyxy[0]  # Convert results to a pandas DataFrame
   print(df)
   ```

6. **Tensor Output**:
   ```python
   tensor = results.xyxy[0]  # Get results as a tensor
   print(tensor)
   ```

### Additional Methods

- **Render Results**:
   ```python
   results.render()  # Render results on the original image
   ```

- **JSON Output**:
   ```python
   json_results = results.pandas().xyxy[0].to_json(orient="records")  # Convert results to JSON
   print(json_results)
   ```

- **Sort Results**:
   ```python
   sorted_results = results.pandas().xyxy[0].sort_values("xmin")  # Sort results by xmin
   print(sorted_results)
   ```

### Example Usage

Here's a quick example to illustrate how you might use some of these methods:

```python
import torch

# Load model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Perform inference
img = 'https://ultralytics.com/images/zidane.jpg'
results = model(img)

# Print results
results.print()

# Show results
results.show()

# Save results
results.save()

# Get results as a pandas DataFrame
df = results.pandas().xyxy[0]
print(df)

# Convert results to JSON
json_results = df.to_json(orient="records")
print(json_results)
```

For more detailed information, you can refer to the [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading).

I hope this helps you with your experiments! If you have any more questions, feel free to ask. Happy experimenting! 😊

**Comment by jcsestilo** [comment]
thanks so muuuch <333
