### ISSUE TITLE
How to set custom generation value while hyperparameter evaluation 

### ISSUE THREAD

**Issue by ThiwankiDias** [ultralytics/yolov5#9672]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear sir,

I m very beginner to YOLOv5. As I read, I found hyperparameter evaluation in yolov5 use default generation size:   300 
my question is : 
is their any parameter to change that generation size to 200 or below value. 

thank you so much for any help.

**Comment by glenn-jocher** [comment]
@ThiwankiDias you can pass a number of generations to evolve, i.e. `--evolve 100`

Default is 300.
