### ISSUE TITLE
Training images without objects

### ISSUE THREAD

**Issue by zfli-xdu** [ultralytics/yolov5#968]
## ❔Question
hi, in my custom dataset, i have some images without objects, thus there are no annotations relate to those images. should i need to make an empty '.txt' label file to refer to it?

**Comment by glenn-jocher** [comment]
@ZhengfengLee background images do not require label files.

**Comment by zfli-xdu** [comment]
> @ZhengfengLee background images do not require label files.

I see. Thank you for your answer

**Comment by zfli-xdu** [comment]
> @ZhengfengLee background images do not require label files.

I still have a question: background images dont compute any loss, right?

**Comment by glenn-jocher** [comment]
@glenn-jocher all images are treated equally in the loss function. If they have no objects, they have no objects, but they are still processed as any other image and evaluate objectness loss at each anchor.

**Comment by zfli-xdu** [comment]
> @glenn-jocher all images are treated equally in the loss function. If they have no objects, they have no objects, but they are still processed as any other image and evaluate objectness loss at each anchor.

thanks

**Comment by HuiLin0220** [comment]
What if I make an empty '.txt' label file for a background image? Could it affect the training?

> @ZhengfengLee background images do not require label files.

**Comment by glenn-jocher** [comment]
Hello @HuiLin0220! Making an empty `.txt` label file for a background image would not negatively affect your training. However, it is not necessary. As mentioned previously, background images do not require label files. If there are no objects in an image, it will still be processed like any other image and evaluate objectness loss at each anchor, but will not impact any other metric such as the classification or localization loss. Let me know if you have any further questions or concerns!
