### ISSUE TITLE
error when use ddp to train with multi GPUs

### ISSUE THREAD

**Issue by Skyninth** [ultralytics/yolov5#9681]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when i train with ddp, i got the follow error, how can i solve this? thks your help!
python -m torch.distributed.run --nproc_per_node 2 train.py --batch 16 --weights yolov5s.pt --device 0,1

WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
  "message": {
    "message": "TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:\n    1. torch._C._distributed_c10d.TCPStore(host_name: str, port: int, world_size: int, is_master: bool, timeout: datetime.timedelta = datetime.timedelta(0, 300))\n\nInvoked with: '127.0.0.1', 29500, 1, True, datetime.timedelta(0, 900); kwargs: multi_tenant=True",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 345, in wrapper\n    return f(*args, **kwargs)\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/run.py\", line 719, in main\n    run(args)\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/run.py\", line 713, in run\n    )(*cmd_args)\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/launcher/api.py\", line 131, in __call__\n    return launch_agent(self._config, self._entrypoint, list(args))\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/launcher/api.py\", line 252, in launch_agent\n    result = agent.run()\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py\", line 709, in run\n    result = self._invoke_run(role)\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py\", line 837, in _invoke_run\n    self._initialize_workers(self._worker_group)\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py\", line 678, in _initialize_workers\n    self._rendezvous(worker_group)\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py\", line 538, in _rendezvous\n    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()\n  File \"/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py\", line 61, in next_rendezvous\n    multi_tenant=True,\nTypeError: __init__(): incompatible constructor arguments. The following argument types are supported:\n    1. torch._C._distributed_c10d.TCPStore(host_name: str, port: int, world_size: int, is_master: bool, timeout: datetime.timedelta = datetime.timedelta(0, 300))\n\nInvoked with: '127.0.0.1', 29500, 1, True, datetime.timedelta(0, 900); kwargs: multi_tenant=True\n",
      "timestamp": "1664795810"
    }
  }
}
Traceback (most recent call last):
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 252, in launch_agent
    result = agent.run()
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 837, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 678, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 538, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home/exp/miniconda3/envs/yolov5-6-ssl/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 61, in next_rendezvous
    multi_tenant=True,
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. torch._C._distributed_c10d.TCPStore(host_name: str, port: int, world_size: int, is_master: bool, timeout: datetime.timedelta = datetime.timedelta(0, 300))

Invoked with: '127.0.0.1', 29500, 1, True, datetime.timedelta(0, 900); kwargs: multi_tenant=True

**Comment by glenn-jocher** [comment]
@Skyninth it appears you may have environment problems. Note Python 3.6 is not supported for YOLOv5 training, and also note Multi-GPU tutorial recommends always using Docker for training.

Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

<a href="https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml"><img src="https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml/badge.svg" alt="YOLOv5 CI"></a>

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 [training](https://github.com/ultralytics/yolov5/blob/master/train.py), [validation](https://github.com/ultralytics/yolov5/blob/master/val.py), [inference](https://github.com/ultralytics/yolov5/blob/master/detect.py), [export](https://github.com/ultralytics/yolov5/blob/master/export.py) and [benchmarks](https://github.com/ultralytics/yolov5/blob/master/benchmarks.py) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.
