### ISSUE TITLE
I can't train with single-gpu.

### ISSUE THREAD

**Issue by hi-one-gg** [ultralytics/yolov5#9686]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Enviroment
Ubuntu 20.04
CUDA 11.4.152
Pytorch 1.12.0
yolov5-6.2

### Question

My computer is equipped with 3 gpu and my command is as follows.
`python train.py --data ./data/my_dataset.yaml --weights ./yolov5l6.pt --device 0 optimizer AdamW`

And I typed the `nvidia-smi` command.
![image](https://user-images.githubusercontent.com/13531174/193721973-81796263-b5c7-4c0b-8197-bb5b48be8250.png)

Why are three GPUs in use?
I can't train with another GPU now.

**Comment by thomassajot** [comment]
You can reduce the number of available GPUs with the environment variable`CUDA_VISIBLE_DEVICES` 
```bash
export CUDA_VISIBLE_DEVICES=0; python train.py --data ./data/my_dataset.yaml --weights ./yolov5l6.pt --device 0 optimizer AdamW
```

**Comment by blackCmd** [comment]
> You can reduce the number of available GPUs with the environment variable`CUDA_VISIBLE_DEVICES`
> 
> ```shell
> export CUDA_VISIBLE_DEVICES=0; python train.py --data ./data/my_dataset.yaml --weights ./yolov5l6.pt --device 0 optimizer AdamW
> ```

Great. Thank you.

**Comment by glenn-jocher** [comment]
@blackCmd you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your training!
