### ISSUE TITLE
Val batch labels use image of one category

### ISSUE THREAD

**Issue by yasmine-detection** [ultralytics/yolov5#9689]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 
I am using Yolov5 to detection of three object classes. Once the training is over, I find only one category used in the images of val batch labels and val batch pred. I want to know how to get random images of all classes for these validation images batches. 
These images are needed in my research to show the performance of the proposed model. 
I thank you for your attention.

**Comment by glenn-jocher** [comment]
@yasmine-detection you can customize the number of validation jpgs saved here:
https://github.com/ultralytics/yolov5/blob/c98128fe71a8676037a0605ab389c7473c743d07/val.py#L265-L269

**Comment by yasmine-detection** [comment]
In fact, I want to know to have more than one class in the validation jpgs not just increase the number of validation jpgs. My problem is having only one class object in the validation jpgs while the model is trained on three classes.

**Comment by glenn-jocher** [comment]
@yasmine-detection your validation set is up to you, I'm not sure what information you're seeking from me.

**Comment by yasmine-detection** [comment]
I am looking for having validation image batches of the three class not only one class like the generated train batches images.  [
![val_batch0_pred](https://user-images.githubusercontent.com/114597972/193877289-bfde4068-3a53-4646-9286-86614cd3871a.jpg)
](url)

**Comment by yasmine-detection** [comment]
all the generated validation images are presenting only the bird category while the model is trained on three classes.

**Comment by glenn-jocher** [comment]
@yasmine-detection so save more jpgs with what I've already shown you in https://github.com/ultralytics/yolov5/issues/9689#issuecomment-1267070648
