### ISSUE TITLE
mAP yolov5 validation without Torchvision

### ISSUE THREAD

**Issue by HarrySm** [ultralytics/yolov5#9692]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I would like run validation and get the mAP for yolov5 models. However, I am facing Torch and Torchvision versions conflict and I could not avoid them because it is used for the NMS see [here](https://github.com/ultralytics/yolov5/blob/c98128fe71a8676037a0605ab389c7473c743d07/utils/general.py#L923).

So my question is how to implement the NMS without using Torchvision and get the mAP without using Torchvision. Is there a way to do that?

You can see my error logs on Nvidia forum [here](https://forums.developer.nvidia.com/t/tensorrt-int8-calibration-python-api/227297).

Thank you in advance.

Best regards,
Harry

**Comment by glenn-jocher** [comment]
@HarrySm see torch and torchvision compat matrix here:
https://pypi.org/project/torchvision/

**Comment by HarrySm** [comment]
> @HarrySm see torch and torchvision compat matrix here: https://pypi.org/project/torchvision/

Hello @glenn-jocher ,

Thank you for your reply, I have already seen it. I do not have a lot of choices for Torch because I have to install it from Nvidia with CUDA so I have Torch+CUDA v1.13 specific for Nvidia devices. So there is no compatible version of TorchVision for Torch v1.13. I already post the issue about TorchVision to Nvidia.

I would like to get some help on how to do the NMS without using the TorchVision implementation, is that easy to do it and how?

Thank you again @glenn-jocher

**Comment by glenn-jocher** [comment]
@HarrySm I'd recommend resolving your environment issues. Your alternative is to re-write torchvision NMS yourself.

**Comment by HarrySm** [comment]
Okay, for now I cannot do anything with my envirement because I have no choice with Torch version on Nvidia device.

Thank you again Glenn :)

Harry

**Comment by glenn-jocher** [comment]
@HarrySm try Docker

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by Zephyr69** [comment]
I think building the correct torchvision from source will resolve this. Look at compatibility matrix for the correct version.

Instructions here (not for orin specifically but shouldn't be a problem) https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048

**Comment by HarrySm** [comment]
Hello @glenn-jocher ,

I have tried it but apparently the docker is not compatible with arm architecture. I am using the Jetson AGX Orin from Nvidia.

**Comment by HarrySm** [comment]
Hello @Zephyr69 ,

I will give it a try, the problem is that I am using the Jetpack 5.0.2 which has only one supported version of Torch with CUDA (v1.13) and at the compatibility matrix there is not yet a compatible version of Torchvision.

**Comment by zhiqwang** [comment]
@HarrySm Just FYI, v1.13a0 is not v1.13, It should be a version between v1.12 and v1.13.

**Comment by Zephyr69** [comment]
> Hello @Zephyr69 ,
> 
> I will give it a try, the problem is that I am using the Jetpack 5.0.2 which has only one supported version of Torch with CUDA (v1.13) and at the compatibility matrix there is not yet a compatible version of Torchvision.

If you couldn't find or don't know which torchvision to build, just build both (whichever desired version of) torch and torchvision from source. That will 100% work.

**Comment by zhiqwang** [comment]
Actually the git hash is https://github.com/pytorch/pytorch/tree/08820cb030927200c92733436f454f5fcf19c6bd, it's about Jun 23, you can find a suitable version of TorchVision for this time.

**Comment by HarrySm** [comment]
@zhiqwang Yes, now they uploaded a new version of Torch with CUDA support for my Jetpack I will give it a try and compile from source Torchvision as @Zephyr69 suggested to me.

**Comment by HarrySm** [comment]
> Actually the git hash is https://github.com/pytorch/pytorch/tree/08820cb030927200c92733436f454f5fcf19c6bd, it's about Jun 23, you can find a suitable version of TorchVision for this time.

Apparently it is this 0.13 here https://github.com/pytorch/vision/releases/tag/v0.13.0
28 Jun.

I will give it a try and keep you updated.

Thank you :)

**Comment by HarrySm** [comment]
Hello again @zhiqwang @Zephyr69 @glenn-jocher ,

I think I have resoled the issue with torchvision. What worked for me after trying different versions is the last Torch+CUDA from Nvidia and I build Torchvision from source as you suggested to me, so now I have Torchvision + CUDA as well.

I have tried to run the `val.py` script and it worked fine, now I will run it using TensorRT engine to see if it will run successfully.

Thank you very much :)

PS:
I will keep you updated about the result, I hope there will be no issues.

Best regard,
Harry

**Comment by HarrySm** [comment]
Thank you very much for your help, @zhiqwang @Zephyr69 @glenn-jocher 

It works now :)

**Comment by glenn-jocher** [comment]
@HarrySm glad to hear you were able to resolve the issue! The efforts of the YOLO community and our team at Ultralytics greatly contribute to the success of the YOLOv5 project. Should you encounter any further challenges or have more questions, feel free to reach out anytime. Congratulations on your successful implementation and best of luck with your future endeavors!
