### ISSUE TITLE
How do i see other predictions of detected object?

### ISSUE THREAD

**Issue by selimdizer** [ultralytics/yolov5#9699]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The class of the detected object is determined according to the best confidence value. But what I want to see is not only the best class, but also others.

**Comment by glenn-jocher** [comment]
@selimdizer to view additional predictions for detected objects, you can use the `--verbose` flag in the detect command. This will display all detected classes and their confidence values. You can also refer to the documentation for more details: https://docs.ultralytics.com/yolov5/

Let me know if you need further assistance!
