### ISSUE TITLE
Procedure of training the model offline.

### ISSUE THREAD

**Issue by nareshku397** [ultralytics/yolov5#9700]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Can you please tell the procedure which have to be followed to train model offline on pc. I have searched on the multiple sources but I am unable to find the procedure at all, 

### Additional

I have trained model in the older version. Currently I have annotated the images all the things are ready but I am stuck in finding a procedure from where I can start. Thanks

**Comment by glenn-jocher** [comment]
@nareshku397 see Train Custom Data tutorial:

## Tutorials

- [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
- [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️ RECOMMENDED
- [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
- [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) 🌟 NEW
- [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
- [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
- [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
- [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
- [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
- [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)
- [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description) 🌟 NEW
- [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)
- [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)  🌟 NEW
- [ClearML Logging](https://docs.ultralytics.com/yolov5/tutorials/clearml_logging_integration) 🌟 NEW
- [Deci Platform](https://github.com/ultralytics/yolov5/wiki/Deci-Platform) 🌟 NEW
- [Comet Logging](https://docs.ultralytics.com/yolov5/tutorials/comet_logging_integration) 🌟 NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by nareshku397** [comment]
Hello Thank you very much that you help me but I have a question that when
I am trying to train my custom model I have changed the dataset path  in
the file coco128.yaml and then i run train.py it is running but when i am
trying to execute the detect.py it is actually working on the previous
dataset even I am given testing data of my new dataset. so kindly help me
out to resolve this issue. Thanks in advance.

**Comment by pderrenger** [comment]
@nareshku397 ensure you're loading the correct weights file in `detect.py` by specifying the path to your trained model using the `--weights` argument. If the issue persists, verify that your dataset paths are correctly configured.
