### ISSUE TITLE
TypeError: object of type 'LoadScreenshots' has no len()

### ISSUE THREAD

**Issue by OopsYouDiedE** [ultralytics/yolov5#9703]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Run python .\detect.py --source screen --weights "E:\Download\yolov5-master\runs\train\exp11\weights\best.pt" --conf-thres 0.5 #

### Environment

OS -windows

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zhouzinimg that's strange. This command works for me on macOS. Are you using the most recent master branch of YOLOv5?



<img width="763" alt="Screenshot 2022-10-05 at 18 52 21" src="https://user-images.githubusercontent.com/26833433/194117341-999cf297-5165-4699-b990-9cad1a134bf5.png">
