### ISSUE TITLE
coco AP for each class

### ISSUE THREAD

**Issue by ljz1998zzzz** [ultralytics/yolov5#9706]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am wondering if I could get the yolov5 checkpoints' performance (AP) on each class of coco dataset. For example, the AP for the person prediction from yolov5s.pt you provided. I added some other classes in addition to coco in my own dataset and the AP for each class in your implementation will help me determine the performance of my model. Many thanks!

**Comment by glenn-jocher** [comment]
@ljz1998zzzz see Colab notebook for example of COCO val. You can use --verbose to display per class:

```
!python val.py --weights yolov5s.pt --data coco.yaml --img 640 --half --verbose
```
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

**Comment by glenn-jocher** [comment]
@ljz1998zzzz you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with evaluating your model!
