### ISSUE TITLE
Resolution at train and inference time must be the same?

### ISSUE THREAD

**Issue by desagab** [ultralytics/yolov5#9707]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I'm using Yolov5 for object detection of cuts over flat cardboards to develop a real-time application. 
Because of the computationally heavy image processing we need to costantly do, we scale down our images. However, because of that, they are really small, with low resolution and the cuts are nearly visible.
Provided that I'm going to always use 640 (or 320) as --imgsize, both for training and detection, I was wondering whether it is a problem if I train the model using images with high resolution and detect them at low resolution.

Below attached, an example of an image at low resolution.

![2022-09-23_17-35-52_d430_54](https://user-images.githubusercontent.com/49653189/194076413-9809fc25-b393-4ff4-8b92-da467090a9d6.jpeg)

**Comment by ljz1998zzzz** [comment]
Hello, I have done some similar experiments. The outcome shows it's OK to train data on a high resolution and detect on a low resolution, but the performance of detection will be relatively low compared to the validation result from high resolution data. A better solution is making sure you use the same img-size when you train and detect, same low or same high. If you use the same low resolution to train, then the validation result will be lower but normally still higher than the result that you trained on a high resolution and tested on a low resolution data.

**Comment by titaniumwhite** [comment]
@ljz1998zzzz as I guessed. Thanks for telling me the outcome of your experiments, you saved me some time.
