### ISSUE TITLE
Training on different img-size dataset

### ISSUE THREAD

**Issue by ljz1998zzzz** [ultralytics/yolov5#9708]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Question:
Hello, may I ask if there is a way that I could train yolov5 on a dataset with different image size? If I could do that, will this make my model difficult to converge?

Background:
For details, I have an image dataset with different sizes, and I don't want to change my images to the same size, like 640. That's  because I want my model is capable of distinguishing the aspect ratio of the object. If I change the image size, then the aspect ratio of object will be changed too, which is against my wish. Of course, I will ensure the sizes of image meet the requirement of model's stride. So does this idea make sense? I would be grateful if you can give me any advice or idea. Many thanks.

**Comment by glenn-jocher** [comment]
@ljz1998zzzz yes you can train on datasets of mixed image sizes, there is no problem. All images are resized to mosaics of image size --imgsz automatically during training.

**Comment by ljz1998zzzz** [comment]
@glenn-jocher I get it now. Thanks a lot.

**Comment by glenn-jocher** [comment]
@ljz1998zzzz you're welcome! Happy to help. If you have any more questions, feel free to ask. Keep up the great work!
