### ISSUE TITLE
Running the model twice on an image and its cropped result

### ISSUE THREAD

**Issue by yazeedhasan97** [ultralytics/yolov5#971]
## ❔Question
Hi YOLOv5 Team,

Thanx for your great work and efforts.

I am running the model on a webcam, get the resulted boxes, and clone an image cropped from the bonding boxes. However, I need to re-enter those cropped images into the model again (the same model but trained for a different specific task ) and I want them both to run simultaneously with a delay 1 second between the first and the second witch will allow me to keep the real-time performance

My two questions are:
1) how to direct the output from the first stage (cropped image of the first model) to the second stage?
2) applying the first point, how to divide the resources between the two equally?

**Comment by glenn-jocher** [comment]
@yazeedhasan97 two stage detection is already built into detect.py, whereby the bounding box contents are optionally passed to a classifier for FP rejection. See detect.py to get started.
https://github.com/ultralytics/yolov5/blob/5a9c5c1d3b02c8796e6af153d57af5821d8db0d6/detect.py#L40-L46

**Comment by iFlyyyy** [comment]
I also noticed the second stage classifier code, Is it available now?
Is resnet101 supported only?
how can I train it?

**Comment by glenn-jocher** [comment]
@iFlyyyy this is a bring-your-own-model situation. Some users like the option of having a second stage filter first stage detections to reduce FPs before passing results.  If you have a classifier (any classifier works, resnet101 is simply there as a placeholder) trained on the same classes, then you can specify it there.
