### ISSUE TITLE
How to detect only one certain object of the class ?

### ISSUE THREAD

**Issue by HripsimeS** [ultralytics/yolov5#9716]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher Hello. Is there some way to detect only one object of a certain class with Yolo5 ? For example by using webcam model detects only certain car in the car's class even if there are many other cars around. Thanks in advance!

**Comment by glenn-jocher** [comment]
@HripsimeS `python detect.py --classes 2 --max-det 1`
