### ISSUE TITLE
requirement inconsistency with CLI prompts 

### ISSUE THREAD

**Issue by babak-abad** [ultralytics/yolov5#9717]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

it is mentioned that **opencv-python>=4.1.1** in requirements.txt but when I use detect command, my CLI prompts 
> requirements: YOLOv5 requirement "opencv-python>=4.5.4" not found, attempting AutoUpdate...

### Minimal Reproducible Example

Run code below:
python detect.py --weights runs/train/exp/weights/best.onnx --dnn

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@babak-abad hi there! Yes these two are different. The reason is that DNN has higher version requirements, i.e. you won't be able to run DNN inference with 4.1.1 I believe but 4.1.1 suffices for everything else.
