### ISSUE TITLE
Loitering detection on video and run on Google Colab

### ISSUE THREAD

**Issue by callme79** [ultralytics/yolov5#972]
I'm new to python and can I know how to add a loitering detection on YOLOv5? I want to create a system like a person exist in the screen more than 20 seconds then an alert will raise and the bounding box of that person will change to red color.  Please help me out and share your ideas on how to solve this problem. Thank you.

**Comment by PiyalGeorge** [comment]
@callme79 Have you got this?

**Comment by Gurutva** [comment]
> I'm new to python and can I know how to add a loitering detection on YOLOv5? I want to create a system like a person exist in the screen more than 20 seconds then an alert will raise and the bounding box of that person will change to red color. Please help me out and share your ideas on how to solve this problem. Thank you.

 check out this repo : https://github.com/Gurutva/Intrusion-Detection , this might be helpful , it seems in accordance with your problem statement

**Comment by ADHITHIYA-14** [comment]
Hi this link -  https://github.com/Gurutva/Intrusion-Detection is not working anymore can you guide me to some other source.

**Comment by glenn-jocher** [comment]
@ADHITHIYA-14 hi there! Thanks for your interest in adding loitering detection to YOLOv5. 

For your requirements, I recommend using YOLOv5 to detect people in the video frames and then implement a timer to track how long they stay in the frame. You can use the `detect.py` script from YOLOv5 to perform detections and then customize the script to monitor the time each person spends in the frame. When the time threshold is surpassed, you can trigger an alert and change the bounding box color.

Feel free to explore Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for instructions on how to run YOLOv5 on Google Colab and customize the detection script to meet your specific needs.

Best of luck with your project, and feel free to reach out if you need any further assistance!
