### ISSUE TITLE
Visualization of class probabilities 

### ISSUE THREAD

**Issue by DoSquared** [ultralytics/yolov5#9721]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was wondering how to obtain class probabilities from YOLO detection. In specific, similar to the image below, the grid imposed on the image at first, then the bounding boxes, and the class probabilities. I can only get the final detection and labels. 

![image](https://user-images.githubusercontent.com/4492013/194350618-3bdd2225-9fcd-4955-bfc5-2d0b35610f01.png)

Thank you very much in advance!

**Comment by glenn-jocher** [comment]
@DaliaMahdy output feature grids are available in Detect() here:
https://github.com/ultralytics/yolov5/blob/7f097ddb6c9921d64fa504a8db79cf24fa0a913c/models/yolo.py#L38-L90

**Comment by DaliaMahdy** [comment]
Thank you for your reply

> @DaliaMahdy output feature grids are available in Detect() here:
> 
> https://github.com/ultralytics/yolov5/blob/7f097ddb6c9921d64fa504a8db79cf24fa0a913c/models/yolo.py#L38-L90

Thank you very much for your reply!

Is this function to be added to the training or detection, where in the notebook to add it?

**Comment by DaliaMahdy** [comment]
What should I give the function as input (nn.module)?

**Comment by glenn-jocher** [comment]
Detect forward method runs automatically for all YOLOv5 detection and segmentation models.

**Comment by DaliaMahdy** [comment]
> Detect forward method runs automatically for all YOLOv5 detection and segmentation models.

Thank you for the reply, I kindly need further explanation, how can I get the class probabilities not the feature grids?

**Comment by glenn-jocher** [comment]
@DoSquared you can obtain class probabilities from the YOLOv5 detect output using the `pred` attribute. This will contain the bounding box coordinates and associated class probabilities. For a more detailed explanation, you can refer to our documentation at https://docs.ultralytics.com/yolov5/.
