### ISSUE TITLE
Public mAP value for each of the COCO object categories?

### ISSUE THREAD

**Issue by iamdami** [ultralytics/yolov5#9725]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi.  
Is there a public mAP value for each of the COCO object categories?
Thanks :)

**Comment by glenn-jocher** [comment]
@iamdami you can run COCO val using the Colab example with val.py --verbose to see all classes.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en
