### ISSUE TITLE
Free batch size in onnx model

### ISSUE THREAD

**Issue by babak-abad** [ultralytics/yolov5#9728]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

For `.pb` file we can use `any batch size`. for example input size can be `? x 20 x 80 x 1`. So I can inference it with any `arbitrary batch size`.  Is it possible to `export onnx (for opencv inference)` as mentioned before?

**Comment by glenn-jocher** [comment]
@babak-abad I don't know about opencv inference but you can run ONNX runtime inference with dynamic batch size by exporting with the --dynamic tag
```
python export.py --include onnx --dynamic
```

**Comment by babak-abad** [comment]
tnx. it works but with weird results (on onnx file using dnn and c++) in both dynamic and static batch inference. Should I open the new problem as new issue?

**Comment by glenn-jocher** [comment]
@babak-abad It seems like you're encountering issues with the ONNX model using DNN and C++. You may want to consider opening a new issue with a clear description of the problem you're facing, including any error messages or unexpected behavior. This will enable the community to better understand and help resolve the issue.
