### ISSUE TITLE
Recommendations for running Yolo5 on Android

### ISSUE THREAD

**Issue by jeggers-88** [ultralytics/yolov5#973]
## ❔Question

Does anybody has recommendations, how to run yolo5 with nice performance on android ? 

## Additional context

First I tried to export my custom trained yolo5s NN to onnx to import it with opencv. But I was not able to load the onnx File successfully with the newest opencv 4.4.0:  
```
 Slice layer only supports steps = 1 (expected: 'countNonZero(step_blob != 1) == 0'), where 'countNonZero(step_blob != 1)' is 1
 must be equal to  '0' is 0
```

Actually I was successfully able to run the torchscript export with pytorch in my android app.  **But with very poor performance (nearly 2 seconds inference time on galaxy tab a sm-t510).** 
Running on my laptop the detect.py shows only ~0.015 seconds (yolo5s with NVIDIA Quadro T2000). 

Thanks very much for any help!

**Comment by zldrobit** [comment]
@jeggers-88 you could try [TFLite Android demo with GPU support](https://github.com/ultralytics/yolov5/pull/959#issuecomment-696058952), since your galaxy tab a sm-t510 has a GPU. I guess the inference time is about 1.5s like Snapdragon 820 GPU.

**Comment by jeggers-88** [comment]
Thanks for your answer, great that yolo5 now has inbuilt tflite export possibilities! 
However I switched the last week to tensorflow lite with a simple mobilenet network v1 (CPU execution time ~100ms for 320x320).  The ~1 second execution time (ok there 640x640) of the exported yolo tflite NN is too slow for my use case.
