### ISSUE TITLE
utils/general.py print_mutation variable keys does not correspond to output of seg train/val

### ISSUE THREAD

**Issue by AdrianStkr** [ultralytics/yolov5#9730]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

 File ".../yolov5-master/segment/train.py", line 674, in <module>
    main(opt)
  File ".../yolov5-master/segment/train.py", line 654, in main
    print_mutation(results, hyp.copy(), save_dir, opt.bucket)
  File ".../yolov5-master/utils/general.py", line 979, in print_mutation
f.write(s + ('%s,' * n % vals).rstrip(',') + '\n')
TypeError: not all arguments converted during string formatting

### Environment

- yolov5 v6.2
- torchvision 0.13.1
- torch 1.12.1
- Python 3.10.6
- Ubuntu 20.04.4 LTS

### Minimal Reproducible Example

 python .../segment/train.py --data coco128-seg.yaml --weights '' --cfg yolov5s-seg.yaml --img 640 --evolve --epochs 2 --batch-size 3

### Additional

Hi,

variable keys (see below) in print_mutation needs to be updated to correspond to the output of train in .../segment/train.py when --evolve is used. 

keys = ('metrics/precision', 'metrics/recall', 'metrics/mAP_0.5', 'metrics/mAP_0.5:0.95', 'val/box_loss',
            'val/obj_loss', 'val/cls_loss') + tuple(hyp.keys())  # [results + hyps]

thank you!

cheers,
Adrian

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AdrianStkr hi Adrian 👋,

Thanks for reporting this issue and providing the context! We value your input and I'll make sure to look into updating the variable keys in print_mutation to correspond to the output of train in .../segment/train.py when --evolve is used.

I appreciate your willingness to contribute and will keep you in the loop as we work on resolving this. Your support means a lot to the YOLOv5 community and the Ultralytics team.

Cheers!
