### ISSUE TITLE
Export results for validating and generating new training data

### ISSUE THREAD

**Issue by lonnylundsten** [ultralytics/yolov5#9731]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

I want to use the detection output in such a way that I can validate/cleanup the ml proposals and then re-incorporate into a new training set. 

RectLabel (https://github.com/ryouchinsa/Rectlabel-support) is a common tool used on Mac's for generating new training data sets. I would like to open output from yolov5 detection in a tool like this so that I could 1) cleanup and edit the model detection proposals and 2) prep that data for generating a new training set or further add to my existing set.

I would be nice to have a flag ( --output-training-data ) that allowed for outputting frame grabs from video without the localizations drawn on them and either voc xml or yolo txt files which could then be imported into a tool like RectLabel, LabelMe, etc for generating more training data.

### Use case

Anyone who is trying to improve model performance by increasing their training data size.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lonnylundsten** [comment]
RectLabel has offered up a potential solution as seen here:
https://github.com/ryouchinsa/Rectlabel-support/issues/203

**Comment by glenn-jocher** [comment]
@lonnylundsten `--save-txt` outputs image predictions YOLOv5 format that can be used for training.
