### ISSUE TITLE
Get bboxes in chronoloical order

### ISSUE THREAD

**Issue by dranreb1660** [ultralytics/yolov5#9732]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am training object detection to identify lines of handwritten texts,  then I can crop each line detected for further processing. However, the bounding boxes are not in order as each line appears in the original input image. Can someone help or point me to a useful resource?

Thanks

**Comment by thomassajot** [comment]
HI @dranreb1660, you could order the output lines by the `y` coordinates of the top left corner for example.  Something along the lines of (I write this by memory, the actual syntax or name of columns may differ a bit):

``` python
result = model(image)
lines = result.pandas().xyxy
lines_sorted_vertically = lines.sort_values('y') # use ascending=False if you need the reverse order
```

**Comment by dranreb1660** [comment]
great idea man this actually opened my brain to think about sorting. Thanks!

**Comment by dranreb1660** [comment]
> HI @dranreb1660, you could order the output lines by the `y` coordinates of the top left corner for example. Something along the lines of (I write this by memory, the actual syntax or name of columns may differ a bit):
> 
> ```python
> result = model(image)
> lines = result.pandas().xyxy
> lines_sorted_vertically = lines.sort_values('y') # use ascending=False if you need the reverse order
> ```

@thomassajot 
Great idea man this actually opened my brain to think about sorting. Thanks!
