### ISSUE TITLE
How to use classifier for various models?

### ISSUE THREAD

**Issue by PraveenMNaik** [ultralytics/yolov5#9733]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks to the introduction of classifier.... I wanted to use classifier for yolo5 for various models like EfficientNet, ResNet. However, I have seen the same algorithms are trained for ImageNet dataset [https://github.com/ultralytics/yolov5/pull/8956](url) .... how to write/use EfficientNet and Resnet models for custom dataset... pls

**Comment by glenn-jocher** [comment]
@PraveenMNaik this is super easy. You can start training any torchvision model, i.e. to train ResNet50:
```bash
python classify/train.py --model resnet50 --data imagenette160 --epochs 5 --img 224
```
<img width="974" alt="Screenshot 2022-10-09 at 22 59 55" src="https://user-images.githubusercontent.com/26833433/194779243-b9c240cf-4e1a-4171-8580-3e9ed419374e.png">

**Comment by PraveenMNaik** [comment]
Thanks for the reply. But, I want to run classifier my custom
dataset....how to do it....

**Comment by PraveenMNaik** [comment]
The classification doesn't show up mAP , Precision and Recall.... they show up Accuracy as performance metrics...
