### ISSUE TITLE
How to build a classification network with a yaml file

### ISSUE THREAD

**Issue by yang-0201** [ultralytics/yolov5#9734]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

How to build a classification network with a yaml file, for example I input a yolov5 yaml file, but only contains the structure of backbone, then build the classification network by the backbone structure in the file, and finally add the classification head to achieve the construction of the classification network, not just by the weight file to determine.
I see that this _from_yaml(self, cfg) function does not have the content of building classification network yet, is this function not implemented yet?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@yang-0201 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

Yes as you mentioned this functionality is not implemented yet, with classification training requiring a pretrained model. If you'd like to implement this feature in classify/train.py that would help future users as well.

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
