### ISSUE TITLE
about a result after running val.py,umm.....i do not know

### ISSUE THREAD

**Issue by FYM1209** [ultralytics/yolov5#9735]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

about a result after running val.py,umm.....i do not know.like this:
![image](https://user-images.githubusercontent.com/93715148/194734100-dbe996ef-3173-4cea-b70e-0c5f49c044bb.png)
|
|
|
^
![image](https://user-images.githubusercontent.com/93715148/194734091-1ecb7c70-5902-4503-8134-f24749d05f73.png)

**Comment by Laughing-q** [comment]
@FYM1209 your class index might be wrong, the original class index in COCO format is 0~91, but in yolov5 we set it 0~80. Make sure the `is_coco` variable in your `val.py` is `True`.

**Comment by FYM1209** [comment]
好的 多谢，我去查一下 @Laughing-q

**Comment by FYM1209** [comment]
is_coco is False, 我该怎么办呢，是训练的coco数据集呀 都没错呀

**Comment by Laughing-q** [comment]
@FYM1209 
[https://github.com/ultralytics/yolov5/blob/fde77584687041aa62795bb2c27e895cf73686bf/val.py#L160](https://github.com/ultralytics/yolov5/blob/fde77584687041aa62795bb2c27e895cf73686bf/val.py#L160)
is_coco是False还是True是自动根据这一行判断的，你的coco.yaml是什么样的呢

**Comment by FYM1209** [comment]
我解决了hahahah  我手动赋值为True了 @Laughing-q

**Comment by Laughing-q** [comment]
@FYM1209 我自己训练也习惯直接给的路径，而不是txt文件，所有我自己通常也是手动设置
