### ISSUE TITLE
Train image size and image prediction size must have same pixels ?

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#974]
## ❔Question
1. in Yolov5, i trained 1000 data image with random image size, like 1024x768 or 640x480 etc, is it wrong ? 
2. trained required same size ? Example 640x640 all for data trained ? 
3. data image to predict must have same size with data trained, example trained data is 640x480 then test image have size 1024x768 ?

Thank you

**Comment by NanoCode012** [comment]
You don’t need to resize them manually. It just works which is great.

I don’t know if there’s a “perfect” image size to use. It should be up to your experiment.

**Comment by luvwinnie** [comment]
i took a dataset with 4k and trained with 640, however, it seems like I need to use --img-size=3840 with detect.py to detect correctly, anyway to get the best performance for any size?

**Comment by glenn-jocher** [comment]
@luvwinnie train and detect at the same --img-size for best results.

**Comment by ghost** [comment]
@glenn-jocher how about the size on training data but with base width is 640, i mean the base width is 640 but have various height like 320x640, 480x640, 221x640, so just can resize by width, not both height and width, because if i resize with same size 640x640 got strecth image

**Comment by glenn-jocher** [comment]
@blinkbink train and detect at the same --img-size for best results, such as the default --img 640.

**Comment by ghost** [comment]
yes sorry, i don't understand, i mean --image-size 640 is for 640x640 right ? how about various like 480x640, 320x640, 211x640 ?

**Comment by glenn-jocher** [comment]
@blinkbink you only supply the longest dimension, --img 640. The rest is handled automatically.

**Comment by ghost** [comment]
I have some few questions. Since I am a beginner to this bear with my innocence in this;

1. For my project since it is an embedded application i decided to go with the fastest v6.0 yolov5n.pt (currently). Since it was pretrained on size - 640 pixels should i also custom train it at only 640 pixels or can i bump it up to higher pixels (say 1280 pixels)?
2. My image dataset consists of images with resolutions like 400*320 and also 3120*4160. So my question is, To get the best results should i reduce the resolution of higher resolution images or can it be the same way as it is?

**Comment by glenn-jocher** [comment]
@kabilan-2001 for fastest results run at lower imgsz, for more accurate results run at higher imgsz.

For large objects use YOLOv5n6 rather than YOLOv5n.

**Comment by ghost** [comment]
@glenn-jocher Thanks for your inputs. I saw somewhere like to know the exact training image size we should be resizing the image and check whether the custom object to be trained on is visible to our eye. Is that way crct to analyze and pick a particular image size for training?

And also training on lower image size will reduce training time. But will it reduce inference times while testing ?

**Comment by oguzaktas** [comment]
@glenn-jocher I have a video dataset and most of the videos have 1920×1080 resolution @25 fps, some of them have 720×576 @50 fps, and some of them have 1280×720 @30 fps. Which img-size is suitable for this data? And which pretrained model is suitable for small target object detection? I haven't tried P6 models yet.

**Comment by glenn-jocher** [comment]
@oguzaktas inference sizes are independent of image sizes, with larger inference sizes produce better mAP at slower speeds. The compromise is your choice based on your priorities, I can't choose for you. See Tips for Best Training Results tutorial for more details.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by skundeti374** [comment]
Hi @glenn-jocher , in yolov5, for example my original image size is 1152, and in training command, yolo --img size is 1024, yolov5 converts 1152 to 1024. 

While predictions, i want to know what happens at the backend, the model predicts on resized 1024 (resized from 1152 to 1024), and scales the detections back to original size 1152? At the final inference stage, the image and detections both are according to original 1152, not 1024 right?

I believe i have seen such scaling of detections in yolov8.
