### ISSUE TITLE
Bug in coco.yaml dataset during training

### ISSUE THREAD

**Issue by HripsimeS** [ultralytics/yolov5#9745]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

@glenn-jocher Hello Glenn. There is some issue with **coco.yaml** file as it is not downloading images in **train2017** folder and therefore **train.py** gives error that there are no images in that folder and training is not starting. 
Can you please check if it works fine on your side **python train.py --data coco.yaml --weights '' --cfg yolov5s.yaml ** 

I tried also training on coco128 dataset **python train.py --data coco128.yaml --weights '' --cfg yolov5s.yaml --img 640**
But unfortunatly received the following error 
**OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\User\anaconda3\envs\yolo5\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.** 

Can you please let me know how I can fix the issue with these two dataset so I can run the train.py file eventually. 

P.S. **detect.py** and **val.py** are working perfectly!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by HripsimeS** [comment]
@ShAmoNiA thanks a lot for your reply! That's a good idea, I will download the dataset manually;
Can you please share your **coco.yaml** file, I would appretiate a lot :)

**Comment by ShAmoNiA** [comment]
of course,
I sifted through DS and only used bird images. 

You need to declare your main route as below, after you need to specify your train and Val folder.
Just a reminder that, yolo will automatically recognize that your train route will be like [ route + "/" +train].

```
path: F:\birds cage\DataSet\coco  
train: train
val: val
```

At the end, you must declare number of your data set class (in my DS, it was just 1) and declare your class name like below:
```
nc: 1
names: ['birds']  
```

The final .yaml file will be something like this:
```
path: F:\university\birds cage\DataSet\coco  
train: train
val: val

nc: 1
names: ['birds']  # class names
```

**Comment by ShAmoNiA** [comment]
After this, If your problem isn't fixed, you need to decrease 'nw' variable.
See below link for more information:
https://github.com/ultralytics/yolov3/issues/1643

**Comment by HripsimeS** [comment]
@ShAmoNiA thanks a lot, your tips on creating a **coco.yaml** file worked perfectly 👍 🥇
