### ISSUE TITLE
How to explain the meaning of yolov5-seg'output ？

### ISSUE THREAD

**Issue by UNeedCryDear** [ultralytics/yolov5#9746]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/52729998/194822556-665e3055-f740-428e-b13a-3506a14508bb.png)<br>
output0: shape is [1,25200,117],
4 bbox+1 boxConfidence+80 classConfidence +32 ，What does the 32-length-data mean？<br>
output1: shape [1,32,160,160],
[160,160]=imgs/mask_ratio,

the last question is：
https://github.com/ultralytics/yolov5/blob/209be932dec9e89b902f0ac2975fa599e9bc676f/utils/segment/general.py#L56
mask_in is [res_pred_num,32]；
protos.float().view(c, -1) is [32,160,160]
mask_in.matmul(protos.float().view(c, -1) ) is [res_pred_num,160,160]，each channel is the mask image of each prediction result class, which is reduced by mask_ratio times.
But why does matrix multiplication need to be used here to get the final mask image?

### Additional

Why the output1 must it be 32 channels? Can it scale like the network by the params depth_multiple and width_multiple in yolov5x-seg.yaml?<br>

**Comment by glenn-jocher** [comment]
@UNeedCryDear mask protos for each output anchor are constructed by a matrix multiplication of the feature vector length 32 with the 32 mask protos. This is how segmentation works.

**Comment by UNeedCryDear** [comment]
@glenn-jocher 
Thanks!

**Comment by DimIsaev** [comment]
Help please

how to get mask polygon coordinates?

from tensor example:

`tensor([[ 0.00461, 0.13584, 0.11417, 0.11526, 0.00513, 0.24116, 0.03406, -0.21047, 0.04178, -0.03982, -0.15830, 0.11752, 0.20854, -0.25333, 0.28739, 0.09242, 0.34544, 0.05757, -0.24321, 0.19312, 0.20507, -0.64462, 0.20967, 0.14347, 0.27276, 0.01950, -0.04970, 0.17735, 0.22388, 0.32066, 0.21949, 0.06792]])
`

in the format

` [(point_x0,point_y0), (point_x1,point_y1),... (point_xN,point_yN), ]`

Thanx

**Comment by glenn-jocher** [comment]
@DimIsaev `python segment/predict.py --save-txt`

**Comment by DimIsaev** [comment]
> @DimIsaev `python segment/predict.py --save-txt`

convert over Opencv ?? 

`cv2.findContours(x, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[0] `

What does a tensor contain?

`det[:, 6:]`
[Link code](https://github.com/ultralytics/yolov5/blob/master/segment/predict.py#L153)
`
tensor([[ 0.00461, 0.13584, 0.11417, 0.11526, 0.00513, 0.24116, 0.03406, -0.21047, 0.04178, -0.03982, -0.15830, 0.11752, 0.20854, -0.25333, 0.28739, 0.09242, 0.34544, 0.05757, -0.24321, 0.19312, 0.20507, -0.64462, 0.20967, 0.14347, 0.27276, 0.01950, -0.04970, 0.17735, 0.22388, 0.32066, 0.21949, 0.06792]])
`

how to convert tensor to coordinates?

**Comment by winktool** [comment]
Is there a version code for ```onnxruntime-node```?

**Comment by glenn-jocher** [comment]
@winktool Currently, we don't have a version code for `onnxruntime-node`. However, you can find detailed information on using ONNX Runtime with Node.js in the [ONNX Runtime documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/onnxruntime/).
