### ISSUE TITLE
how to  run segmentation successfully in C++, onnxruntime and tensorrt?

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/yolov5#9747]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

the detection is ok, but the mask part, how to convert them to c++?

**Comment by glenn-jocher** [comment]
@xinsuinizhuan TRT segmentation runs automatically with YOLOv5, just export any segmentation model with export.py and follow usage examples shown after export.
