### ISSUE TITLE
where is segment pretrained models?

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/yolov5#9748]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

where is segment pretrained models?

**Comment by sctrueew** [comment]
https://github.com/ultralytics/yolov5/releases/download/v6.2/yolov5s-seg.pt
Or
Python segment/predict.py --weights yolov5s-seg.pt => automatically downloads the pre-trained and then runs it.

**Comment by glenn-jocher** [comment]
@sctrueew thanks for your interest in YOLOv5! Pretrained segmentation models can be found at the YOLOv5 releases page or can be downloaded automatically using the 'segment/predict.py' script. You can also find more information in the Ultralytics Docs. Let me know if you need further assistance!
