### ISSUE TITLE
Posssible to use label in voc notation? 

### ISSUE THREAD

**Issue by andrewGIS** [ultralytics/yolov5#975]
## ❔Question
Hi, I have small dataset with voc notation in xml files. Is it possible to use youer script to train with this
Sample object
![image](https://user-images.githubusercontent.com/34353589/93291743-5864a980-f7fd-11ea-9e97-8b7e589d73f7.png)

## Additional context
Sample xml 
```
<annotation>
	<folder>s2_truecolor_samples</folder>
	<filename>T39VXH_20190614_RGB324.JPG</filename>
	<path>D:\Work\_new_features\ML\yolo\s2_truecolor_samples\T39VXH_20190614_RGB324.JPG</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>416</width>
		<height>416</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>fell</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>187</xmin>
			<ymin>333</ymin>
			<xmax>237</xmax>
			<ymax>405</ymax>
		</bndbox>
	</object>
</annotation>
```

**Comment by NanoCode012** [comment]
As I recall, there is code to convert voc labels to yolo here. Maybe you can take part of the code below and modify it

https://github.com/ultralytics/yolov5/blob/5a9c5c1d3b02c8796e6af153d57af5821d8db0d6/data/scripts/get_voc.sh#L86-L140

**Comment by tenggyut** [comment]
[My Repo](https://github.com/tenggyut/pytorch_detectors) can handle voc style annotations without converting to darknet style, you may check there.

currently the repo is able to train yolov5 with custom voc style dataset, but not fully tested and docs, so use it at your own risk.

**Comment by andrewGIS** [comment]
Thank you, I will report after testing!

**Comment by tenggyut** [comment]
> Thank you, I will report after testing!

ddp is now supported, but only tested with a two-gpu machine. 

Verified with my own helmet dataset and can produce comparable results with ultralytics's version.

So good luck

**Comment by juliussin** [comment]
> As I recall, there is code to convert voc labels to yolo here. Maybe you can take part of the code below and modify it
> 
> https://github.com/ultralytics/yolov5/blob/5a9c5c1d3b02c8796e6af153d57af5821d8db0d6/data/scripts/get_voc.sh#L86-L140

HI! I wonder if this script could handle this [UA-DETRAC](http://detrac-db.rit.albany.edu/download) datasets. The problem is the training sample consists of some folders (represent videos), and each folders containing some photos (I think for each frame of the video). Meanwhile, the XML Annotation only corresponds to each folders, not each images. Could you suggest what should I do to train this datasets?
