### ISSUE TITLE
Curious to know why we cant port the Ultralytics weights file to other yolov5 repos

### ISSUE THREAD

**Issue by gd1925** [ultralytics/yolov5#9752]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone,

I have been trying to load the weights files trained by the Ultralytics Yolov5 to https://github.com/Okery/YOLOv5-PyTorch. On trying to load any model, I keep running into the errors-
![image](https://user-images.githubusercontent.com/50822928/194870937-5eba4eef-144d-4e7d-b20c-2d6ee74b6ccd.png)

Does it mean its not possible to directly load the models from Ultralytics repo? It does mention here that the weights are from the Ultralytics, loading this particular weights file does work and gives results.
![image](https://user-images.githubusercontent.com/50822928/194871259-2ec6b650-6da4-493d-9955-ca721992b019.png)

But on replacing the model with any other models gives the above error. Can someone guide me on this? I also tried to load model files to the https://github.com/Bobo-y/flexible-yolov5, but the error is the same - 
![image](https://user-images.githubusercontent.com/50822928/194869971-1708a2e6-c0fe-4ffe-8558-dfc08ffb8e10.png)

Thank you very much.

**Comment by zhiqwang** [comment]
@gd1925 maybe you could try this one https://github.com/zhiqwang/yolov5-rt-stack with `pip install -U yolort`, and than try belows:

```python
from yolort.models import YOLOv5

# Download checkpoint from https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5s.pt
ckpt_path_from_ultralytics = "yolov5s.pt"
model = YOLOv5.load_from_yolov5(ckpt_path_from_ultralytics, score_thresh=0.25)

model.eval()
img_path = "test/assets/bus.jpg"
predictions = model.predict(img_path)
```

> **Note**: I haven't had time to support 6.2 version and the master branch.

**Comment by zhiqwang** [comment]
And all the secrets are behind https://github.com/zhiqwang/yolov5-rt-stack/blob/main/yolort/models/_checkpoint.py

**Comment by gd1925** [comment]
Hi @zhiqwang , Thank you very much for your reply!! Your answer is very useful indeed, I will try it out! :D
