### ISSUE TITLE
How to save pixel coordinates of predicted 2D bounding box ?

### ISSUE THREAD

**Issue by HripsimeS** [ultralytics/yolov5#9753]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher I saw your great parameter to crop and save bounding box detections **python detect.py --save-crop** 

Is there any way to save pixel coordinates of predicted bounding box? For example, save coordinates in .txt files for bench class 

**13 0.405829 0.456086 0.80493 0.736484**

Look forward to hearing from you!

**Comment by glenn-jocher** [comment]
@HripsimeS glad to hear you found the solution! 🎉 Yes, the `--save-txt` argument in `detect.py` saves the predicted bounding box coordinates in .txt files. For more details on command-line arguments, check out our documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!
