### ISSUE TITLE
Purpose of using --data argument in detect.py

### ISSUE THREAD

**Issue by aliaminibagh** [ultralytics/yolov5#9755]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

What is the purpose of --data in detect.py?
After training the model and creating best.pt, I plan to use it. During the training, I considered the custom **data.yaml** file as input for **--data argument** .
Is it necessary to introduce this argument during inference or is it not important? If I don't introduce it, the network will use **coco.yaml** by default.

![image](https://user-images.githubusercontent.com/59368585/194918713-50affcfb-da91-45a2-8d18-364988ffc681.png)

**Comment by glenn-jocher** [comment]
@aliaminibagh for model types that do not contain class name metadata (i.e. TensorRT, CoreML, etc.) a data yaml can be passed.

**Comment by aliaminibagh** [comment]
> @aliaminibagh for model types that do not contain class name metadata (i.e. TensorRT, CoreML, etc.) a data yaml can be passed.

Thanks @glenn-jocher . can you explain more?

**Comment by glenn-jocher** [comment]
@aliaminibagh absolutely! When you're using YOLOv5 for inference, the `--data` argument is used to provide the model with information about the dataset that it was trained on, such as class names and colors. This is essential for correct labeling during inference. If you don't specify the `--data` argument, the default `coco.yaml` will be used, but if you trained your model on a custom dataset, it's important to specify the correct `data.yaml` file during inference.

You can find detailed information about the `--data` argument and its usage in our documentation at https://docs.ultralytics.com/yolov5/. Let me know if you need further assistance!
