### ISSUE TITLE
train many yolov5 custom model

### ISSUE THREAD

**Issue by ShAmoNiA** [ultralytics/yolov5#9757]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Greeting, 
I have a python code which I want to use it as my main file.
In this file, I want to train yolov5 model several times.

I used 2 ways for this although both of them wasn't successful.

First way:
I imported train.py from yolov5 and I called run() function every time I want train my new model; like below: 
```
from yolov5 import train

train_info = train.run(data='yolov5/data/test.yaml', weights='yolov5n.pt',epochs=100, batch_size=8)
train_info = train.run(data='yolov5/data/test.yaml', weights='yolov5x.pt',epochs=100, batch_size=8)
train_info = train.run(data='yolov5/data/test.yaml', weights='yolov5l.pt',epochs=100, batch_size=8)

```

But unfortunately, that wasn't successful. (https://github.com/ultralytics/yolov5/issues/9737)

Second way:
I used os.system() from training mu model and in many times that works fine for me; 
```
os.system("python yolov5_edited/yolov5/train.py --data test.yaml --weights 'yolov5n.pt' --cfg yolov5n.yaml --batch-size 8 --name {} --epoch 40".format(item))
```
![Uploading image.png…]()

though, in some times it stuck at the beginning of 3th epoch when yolo want to start validation for  second epoch.

Do we have better way for this action?
my main code must train at least 200 model and I need clean way for it.

**Comment by glenn-jocher** [comment]
@ShAmoNiA I would run trainings trainings from CLI as in your second example. We run CI this way, not the python way.

**Comment by ShAmoNiA** [comment]
Thanks for your response @glenn-jocher 
So, what is your opinion if you want to train model Automatically without using CLI.

**Comment by glenn-jocher** [comment]
Write a bash script?

**Comment by ShAmoNiA** [comment]
Does that mean I have to write a script in any case? :(
Honestly, I wrote GA with python and in each iteration, it needs to train a model.
So, based on your idea, I should run a script at the end of each iteration (or generation) and get information about the trained model from it.

Thank you very much @glenn-jocher .

**Comment by glenn-jocher** [comment]
@ShAmoNiA if you want a python example that runs training hundreds of times you can also simply look at the evolution code in train.py:
https://github.com/ultralytics/yolov5/blob/2f1eb21ad6c0f715f38200c31e6e01a92c5acb25/train.py#L528-L620

**Comment by ShAmoNiA** [comment]
Thanks again.

**Comment by glenn-jocher** [comment]
@ShAmoNiA you're welcome! If you have any other questions or need further assistance, feel free to ask. Good luck with your project!
