### ISSUE TITLE
SavedModel files with '.' in the pathname fail due to the use of Path.suffix() to compare against suffixes that don't start with '.'

### ISSUE THREAD

**Issue by agentmorris** [ultralytics/yolov5#9758]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

detect.py infers the model type from the suffix (e.g. ".pt"); specifically, it uses Path.suffix() to compare suffixes to elements of the list ['.pt', '.torchscript', '.onnx', '_openvino_model', '.engine', '.mlmodel', '_saved_model', '.pb', '.tflite', '_edgetpu.tflite', '_web_model', '_paddle_model'].

This happens in [general.py](https://github.com/ultralytics/yolov5/blob/master/utils/general.py#L401).

Under normal circumstances, Path.suffix returns a suffix() starting with ".", so it's a brittle operation to compare the value of Path.suffix() to strings that start with "_".  It happens to work in the default case because there are no .'s in the default model name (e.g. yolov5s_saved_model), but this becomes problematic if there are .'s in the filename, e.g. yolov5s.0.0.1_saved_model.

Using endswith() rather than Path.suffix() would probably capture the intended behavior a bit better.

If someone can confirm that this is not intended behavior, I can submit a PR.

Thanks!

### Environment

Python 3.10.4
Ubuntu 20.04
YOLOv5 commit 2f1eb21ad6c0f715f38200c31e6e01a92c5acb25

### Minimal Reproducible Example

```
python export.py --include saved_model

# This works fine
python detect.py --weights yolov5s_saved_model/

mv yolov5s_saved_model yolov5s.a.b.c_saved_model

# This does not work, see error below
python detect.py --weights yolov5s.a.b.c_saved_model/
```

The second invocation of detect.py gives:

AssertionError: yolov5s.a.b.c_saved_model/ acceptable suffix is ['.pt', '.torchscript', '.onnx', '_openvino_model', '.engine', '.mlmodel', '_saved_model', '.pb', '.tflite', '_edgetpu.tflite', '_web_model', '_paddle_model']

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@agentmorris I think in general it's always best practice to avoid periods in directory names. 

I'm not aware of any complaints so far. If you'd like to propose changes the code that handles model type identification is here:
https://github.com/ultralytics/yolov5/blob/2f1eb21ad6c0f715f38200c31e6e01a92c5acb25/models/common.py#L589-L602

**Comment by agentmorris** [comment]
Thanks, I submitted [PR 9759](https://github.com/ultralytics/yolov5/pull/9759).  Very low priority, this is unlikely to block anyone. 
 This is reasonably likely to be encountered by others who are exporting fto SavedModel format, since it's not that unusual to have multiple .'s in a trained model filename (e.g. something.version.pt), which results in folders with .'s.  But it's easy to work around, ergo, very low priority.

Thanks again for all of your hard work, on behalf of all of the projects that YOLOv5 makes possible!

**Comment by glenn-jocher** [comment]
Thanks for your contribution, @agentmorris! Your input and effort are greatly appreciated. We all collectively benefit from the YOLO community's dedication and collaboration. Kudos also to the open-source contributors who continue to advance the YOLOv5 project.

If you need any further assistance or have additional suggestions, feel free to reach out.
