### ISSUE TITLE
how to show the boundingbox whose probability is < 0.3 after run Pthon val.py

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/yolov5#9762]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I run  !python val.py --weights **, and I want to show the bounding box whose probability is between  0.2< probability < 0.3. where can I modify the code to do it?  I know YoloV5 only shows bounding box whose probability > 0.3; but my research need to show some specific range of probability.  In the validation, runs/valid/exp, I do not find the predicted bounding box coordinate information either. 

![image](https://user-images.githubusercontent.com/57141860/194980777-1441a19d-3164-4cdb-b67f-03664bb80ec1.png)

**Comment by glenn-jocher** [comment]
@frabob2017 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by frabob2017** [comment]
I used the torch.hub you mentioned. However, it cannot detect anything. If I use the same data set and weights, run !python val.py , it can detect at least one thing although there are still a lot of things missing. It looks that there is difference between them. 

Meanwhile, this command can only run on images. If I feed model as a folder including many images, it will not run. Do you know why? 
# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list
# Inference
results = model(im)

**Comment by glenn-jocher** [comment]
@frabob2017 you can lower confidence threshold like this:

```python
model = ...
model.conf = 0.10

results = model(im)
```

**Comment by frabob2017** [comment]
> @frabob2017 you can lower confidence threshold like this:
> 
> ```python
> model = ...
> model.conf = 0.10  # set confidence threshold (default 0.25)
> 
> results = model(im)
> ```

But this cannot work on a folder, only works on a single file. Do you know how to work for a whole folder although I can run os.listdir to run an image one by one.
