### ISSUE TITLE
Why  box = w - l[3], l[2], w - l[1], l[4] in copy_paste?

### ISSUE THREAD

**Issue by xiaokening** [ultralytics/yolov5#9763]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

in below function,why `box = w - l[3], l[2], w - l[1], l[4]` ?l[1], l[2], l[3], l[4] are **top left x, top left y, bottom right x,bottom right y**.I think `box = l[3], l[2], l[1], l[4]`, can you give me some insight？Thanks!

>https://github.com/ultralytics/yolov5/blob/cf4f3c3455d14c62e11dcce9f1d30211509da72f/utils/augmentations.py#L213

**Comment by xiaokening** [comment]
It's my fault, I know why now,Thank you for your object detection project！

**Comment by glenn-jocher** [comment]
@xiaokening you're welcome! I'm glad you figured it out. Thank you for your contribution and support for the YOLOv5 project. If you have any more questions or need further assistance, feel free to ask. Good luck with your object detection tasks!
