### ISSUE TITLE
Web Cam in camera is not working

### ISSUE THREAD

**Issue by khanrajesh** [ultralytics/yolov5#9770]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

While running the detect.py with a simple command  
`!python train.py --img 640 --batch 16 --epochs 1 --data {dataset.location}/data.yaml --weight yolov5x.pt --cache --worker 2`
`!python detect.py  --img 640 --source 0 --line-thickness 1`
the camera of laptop is not working and giving the error 

`Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\air\Tool_Object_Detection\odec\detect.py", line 255, in <module>
    main(opt)
  File "C:\Users\Admin\Desktop\air\Tool_Object_Detection\odec\detect.py", line 250, in main
    run(**vars(opt))
  File "C:\Users\Admin\Desktop\air\Tool_Object_Detection\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Admin\Desktop\air\Tool_Object_Detection\odec\detect.py", line 111, in run
    for path, im, im0s, vid_cap, s in dataset:
  File "C:\Users\Admin\Desktop\air\Tool_Object_Detection\odec\utils\dataloaders.py", line 355, in __next__
    if not all(x.is_alive() for x in self.threads) or cv2.waitKey(1) == ord('q'):  # q to quit
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1333: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvWaitKey'`

The detection is working with images and videos.

### Minimal Reproducible Example

!git clone https://github.com/ultralytics/yolov5 
%cd yolov5
%pip install -qr requirements.txt
%pip install torch==1.8.2 torchvision==0.9.2 torchaudio===0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cu111

import torch
import os
import numpy as np
from matplotlib import pyplot as plt
from IPython.display import Image, clear_output #to display image
import glob
from IPython.display import Image, display

!python train.py --img 640 --batch 16 --epochs 1 --data {dataset.location}/data.yaml --weight yolov5x.pt --cache --worker 2

!python detect.py  --img 640 --source 0 --line-thickness 1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by cr-velox-git** [comment]
The problem was with the opencv-python package, using a different version was able to resolve the error.

**Comment by glenn-jocher** [comment]
@khanrajesh glad to hear you were able to resolve the issue! The YOLOv5 team always appreciates user feedback and community contributions. If you have any further inquiries or encounter more challenges, feel free to ask. 🚀
