### ISSUE TITLE
yolov5_v6.2 + FaceLandmarks 

### ISSUE THREAD

**Issue by June1124** [ultralytics/yolov5#9771]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a face keypoint detection based on yolov5_v6.2? Or are there other applications for keypoint detection?

**Comment by athrunsunny** [comment]
you mean multi-task？

**Comment by June1124** [comment]
> you mean multi-task？

Yes, Do you have relevant implementation?

**Comment by athrunsunny** [comment]
You can try this https://github.com/athrunsunny/landmark-face
You'd better use  torch==1.8

**Comment by glenn-jocher** [comment]
@athrunsunny thanks for sharing! It seems like a great implementation. We currently focus on object detection, but you can definitely integrate face keypoint detection with YOLOv5 as a custom task. For more details, the Ultralytics docs at https://docs.ultralytics.com/yolov5/ are a valuable resource. Good luck!
