### ISSUE TITLE
disable data enhancement at the last Epoch

### ISSUE THREAD

**Issue by SSTato** [ultralytics/yolov5#9777]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Whether yolov5 will disable data enhancement at the last Epoch. If yes, where can we set the number of remaining Epochs to disable data enhancement

**Comment by glenn-jocher** [comment]
@SSTato hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

This is not a current feature. The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
