### ISSUE TITLE
How can I reduce number of hidden layers for train?

### ISSUE THREAD

**Issue by star4s** [ultralytics/yolov5#9780]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I reduce number of hidden layers for train?
I need to control the number of hidden layers for train.
Thank you for your attention.

**Comment by glenn-jocher** [comment]
@star4s use a smaller model?
```
python train.py --weights yolov5n.pt
```

**Comment by star4s** [comment]
@glenn-jocher
I used yolov5x6.pt model. I would like to keep the structure of yolov5x6.pt and to reduce number of hidden layers for train.

**Comment by glenn-jocher** [comment]
@star4s you can customize the compound scaling constants of your model here:
https://github.com/ultralytics/yolov5/blob/16f87bb38e76a5aa14ee93252042063b678ece86/models/hub/yolov5x6.yaml#L5-L6

And then point to `--cfg yolov5x6.yaml` when training
