### ISSUE TITLE
 Runing Multiple trainings (or inference) in parallel in a single GPU

### ISSUE THREAD

**Issue by wafa-bouzouita** [ultralytics/yolov5#9781]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Please what modifications must I do to the code to let runing multiple trainings in parallel in a single GPU possible ?

Thank you

**Comment by MartinPedersenpp** [comment]
My guess would be that if there is available memory in your GPU, you can run two training sessions in parallel, but the second if not both sessions will fail if your GPU goes OOM.
Make sure to set your batch size on the first training session and monitor the GPU usage with nvidia-smi

**Comment by glenn-jocher** [comment]
@wafa-bouzouita this is not recommended, but you can run two trainings on the same device:

```
python train.py --device 0
python train.py --device 0
```
