### ISSUE TITLE
How to add a 10*10 large detection layer？

### ISSUE THREAD

**Issue by taotao6** [ultralytics/yolov5#9791]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The Internet is always adding a small detection layer, but I want to add a large detection layer。
What should I do？

**Comment by glenn-jocher** [comment]
@taotao6 use a P6 model, they have P6/64 detection layers for large objects, i.e. `python train.py --weights yolov5s6.pt`

**Comment by taotao6** [comment]
> @taotao6 use a P6 model, they have P6/64 detection layers for large objects, i.e. `python train.py --weights yolov5s6.pt`

thanks a lot！and I see P7 and P34, what do they do

**Comment by glenn-jocher** [comment]
P34 only has P3/8 and P4/16 output grids for small object detection. P7 has a P7/128 grid for extremely large objects.
