### ISSUE TITLE
Visualize mapping yolov5

### ISSUE THREAD

**Issue by chelsea456** [ultralytics/yolov5#9793]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi sir, i have a question in visualize 
![image](https://user-images.githubusercontent.com/104009307/195483921-6cb1c4d3-a050-4766-a48c-c6136969ca23.png)
i don't know why have 32 picture in stage0conv , what mean in each pictute. tks sir!!!

**Comment by glenn-jocher** [comment]
Each is a channel
