### ISSUE TITLE
save_json in val.py leads to error because of annotation

### ISSUE THREAD

**Issue by lfangyu09** [ultralytics/yolov5#9794]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks a lot for sharing the code. When I run val.py, it shows an error
 "pycocotools unable to run: [Errno 2] No such file or directory: '../coco/annotations/instances_val2017.json'".

Since I transform the annotation from PASCAL VOC format to COCO format, I do not have the json file. I searched a lot but I did not find a good way to get the COCO json file. May I ask how I can get the json file? Thanks a lot.

**Comment by glenn-jocher** [comment]
@lfangyu09 pycocotools is only intended for COCO dataset right now.

**Comment by lfangyu09** [comment]
Thanks a lot for your quick response. I remove the save json flag. How can I get the coco evaluation results based on val.py?

**Comment by glenn-jocher** [comment]
@lfangyu09 if you train coco.yaml it's applied automatically.

**Comment by lfangyu09** [comment]
Yes. I tried.
`python val.py --weights runs/train/exp/weights/best.pt --data crack_detection.yaml --img 512 --task test --save-txt --verbose --save-json`
But it shows 
> "pycocotools unable to run: Results do not correspond to current coco set".
Since I used my custom data, I checked the datast json and predicted result json. This error is caused by the predicted result json.

**Comment by glenn-jocher** [comment]
@lfangyu09 as I said it's only intended for COCO
