### ISSUE TITLE
How to put pure background into training

### ISSUE THREAD

**Issue by yanni1995** [ultralytics/yolov5#9797]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to put pure background into training

**Comment by glenn-jocher** [comment]
@yanni1995 add images without labels to your dataset. These will be used as background images automatically.

**Comment by yanni1995** [comment]
need an empty txt file or no txt file

**Comment by glenn-jocher** [comment]
no txt file required for background images.

**Comment by yanni1995** [comment]
ok,thanks you answer

**Comment by frabob2017** [comment]
I did the exact same things. 90% of my dataset are background images without labels.  It looks that too many background images will decrease detection sensitivity based on my preliminary observation.  I am still working on it.

**Comment by Rich2020** [comment]
Do we need to add a name/label in the config/YAML file?

E.g.,:
```
names:
  0: cats
  1: dogs
  2: mice
  3: background
```

**Comment by glenn-jocher** [comment]
@Rich2020 no, you just add any background images you want to your dataset by placing them in the same directory as your training images. You'll see the extra images shown in the train/val set stats when training starts. No other changes necessary.

**Comment by Rich2020** [comment]
@glenn-jocher Brilliant. Thank you and happy holidays!

**Comment by glenn-jocher** [comment]
@Rich2020 thank you, your kind words are much appreciated! Happy holidays to you too! If you have any more questions, feel free to ask.
