### ISSUE TITLE
How can I add the output feature maps of two models?

### ISSUE THREAD

**Issue by aa484** [ultralytics/yolov5#9798]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In common.py, I copy the Concat and change the return. 
In yolo.py, I add the class. 
However, errors will be reported when the code runs.
Who can help me realize the feature map addition class？
Please help me.

### Additional

![2022-10-13 16-04-02](https://user-images.githubusercontent.com/82189545/195540195-b066f63f-902d-43eb-ab3c-6dc5fdfe57f3.png)

**Comment by 1998Jiang** [comment]
1

**Comment by glenn-jocher** [comment]
@1998Jiang hello,

Thank you for your interest in YOLOv5! Can you please provide more information about the error you are encountering when trying to add the output feature maps of two models? Providing specific error messages and the relevant code segments will be helpful in identifying the issue and offering a solution.

Looking forward to your response.
