### ISSUE TITLE
Is it feasible to run the detection.py on nvidia jeton tx2 with Pytorch 1.4.0 and python 3.6 ?

### ISSUE THREAD

**Issue by HenryWang628** [ultralytics/yolov5#98]
I have ran the detection.py on a remote server with Pytorch 1.4.0 (lower than the requirement) and python 3.7 without error. 
I wonder if it is feasible to finish the inference with an environment of Pytorch 1.4.0 and  python 3.6 on jetson tx2. Thanks!

**Comment by glenn-jocher** [comment]
@HenryWang628 I have no idea.

If you want to know if its possible why don't you try it?

**Comment by HenryWang628** [comment]
I 'm working on it

> @HenryWang628 I have no idea.
> 
> If you want to know if its possible why don't you try it?

OK, I'm woking on it, Thanks!

**Comment by luosiwu** [comment]
I've tried it, it doesn't work on TX2, how's the building master

**Comment by luosiwu** [comment]
> I have ran the detection.py on a remote server with Pytorch 1.4.0 (lower than the requirement) and python 3.7 without error.
> I wonder if it is feasible to finish the inference with an environment of Pytorch 1.4.0 and python 3.6 on jetson tx2. Thanks!

Hi, how's it going
