### ISSUE TITLE
Running Yolov5 Segmentation (Custom) models exported as ONNX on C++ (OpenCV - DNN)

### ISSUE THREAD

**Issue by JustasBart** [ultralytics/yolov5#9800]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi guys,

I need some help understanding the output of the segmentation models (As a non-Python developer).
What I know and have working thus far is running regular yolov5 models (Trained on custom data) where sample code already exists on GitHub.

To my best understanding this is what the ONNX (Object detection) model inference outputs:

![image](https://user-images.githubusercontent.com/40023722/195561392-0dbcfadc-0c9a-4be0-b1a4-a9e467ac3bbe.png)

Moving onto yolov5 Segmentation is where things get a little bit more complicated to interpret...

![segmentations](https://user-images.githubusercontent.com/40023722/195564865-2ec62c5c-ed92-49c1-8451-66335350f063.jpg)

As you can see from the above diagram I'm still able to extract the detection bounding boxes with the same approach (Although making sure that I'm decoding the correct output), but my issue is that I want to decode/use OpenCV to draw the Segmentations for those detections.

I've seen a few instances where the answer to a segmentation output question was "Well just look at the Python code for achieving this" but that's no good for me as a C++ developer...

I'm willing to submit a clean, cut-down version of the C++ code for achieving this as a thank-you for any help that anyone could provide in terms of what needs to happen here in order to make sense of this.
And yes, I am aware that this will likely come back to some fundamentals of segmentation in general, but I wouldn't really know that either so if there's any chance of answering things in terms of steps (Especially based on OpenCV) that would be ideal.

Based on what I've read thus far it involves matrix multiplications but what am I multiplying/scaling and drawing in the end?
How do I package up a raw output into a segmentation polygon?

Thank you for any help in advance...

**Comment by UNeedCryDear** [comment]
https://github.com/UNeedCryDear/yolov5-seg-opencv-dnn-cpp
You can get the segment mask in the detection bounding-box,which it is different from the original whole-img-mask
https://github.com/UNeedCryDear/yolov5-seg-opencv-dnn-cpp/blob/6a9eb00f05beae8d926644f8b1c80d9cfd6cc074/yolo_seg.cpp#L183

**Comment by JustasBart** [comment]
You're an absolute legend, thank you very much!

**Comment by Muneeb-Ahmed-Khan** [comment]
> https://github.com/UNeedCryDear/yolov5-seg-opencv-dnn-cpp You can get the segment mask in the detection bounding-box,which it is different from the original whole-img-mask https://github.com/UNeedCryDear/yolov5-seg-opencv-dnn-cpp/blob/6a9eb00f05beae8d926644f8b1c80d9cfd6cc074/yolo_seg.cpp#L183

Thanks for providing this. This code is pretty hard for me to understand but I am trying to grasp it. Thanks again. You are legend.

**Comment by glenn-jocher** [comment]
@Muneeb-Ahmed-Khan thanks for sharing the link to the code that demonstrates how to get the segment mask within the detection bounding box. I appreciate your kind words, but I must emphasize that the credit goes to the YOLOv5 community and the Ultralytics team for developing and maintaining the YOLOv5 repository.

If you have any further questions or need more assistance, feel free to ask. We're here to help!
