### ISSUE TITLE
How to look at the summary after running the code in cmd again？

### ISSUE THREAD

**Issue by taotao6** [ultralytics/yolov5#9801]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/37886233/195581213-79370f87-2b32-4c10-842a-453630d497ff.png)

I turned cmd off, how can that result be seen again.

**Comment by glenn-jocher** [comment]
@taotao6 val.py generates the validation results shown, i.e.
https://github.com/ultralytics/yolov5/blob/16f87bb38e76a5aa14ee93252042063b678ece86/val.py#L2-L20

**Comment by taotao6** [comment]
> @taotao6 val.py generates the validation results shown, i.e.
> 
> https://github.com/ultralytics/yolov5/blob/16f87bb38e76a5aa14ee93252042063b678ece86/val.py#L2-L20
I mean I want the result after running train.py.

**Comment by taotao6** [comment]
> @taotao6 val.py generates the validation results shown, i.e.
> 
> https://github.com/ultralytics/yolov5/blob/16f87bb38e76a5aa14ee93252042063b678ece86/val.py#L2-L20

This val.py result is much higher than that

**Comment by taotao6** [comment]
> @taotao6 val.py generates the validation results shown, i.e.
> 
> https://github.com/ultralytics/yolov5/blob/16f87bb38e76a5aa14ee93252042063b678ece86/val.py#L2-L20

I'm sorry. You're right. I misread the parameters
