### ISSUE TITLE
How to load a custom model?

### ISSUE THREAD

**Issue by int3r5t377ar** [ultralytics/yolov5#9802]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I use the code
`model = torch.hub.load('ultralytics/yolov5', 'custom', path='C:/Users/Documents/yolov5/runs/train/exp/weights/best.bt', force_reload=True)`
to load the custom model I have trained.
The code is found in the internet and it works for the examples I referenced at. 
But for me, it keeps generating errors:
```
PS C:\Users\Documents\yolov5> & C:/Users/anaconda3/python.exe "c:/Users/Documents/yolov5/myfile.py"
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to C:\Users/.cache\torch\hub\master.zip
YOLOv5  2022-10-13 Python-3.9.13 torch-1.12.1 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)

Traceback (most recent call last):
  File "C:\Users/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 47, in _create
    model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
  File "C:\Users/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 331, in __init__
    pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, paddle, triton = self._model_type(w)
  File "C:\Users/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 596, in _model_type
    check_suffix(p, sf)  # checks
  File "C:\Users/.cache\torch\hub\ultralytics_yolov5_master\utils\general.py", line 409, in check_suffix

Traceback (most recent call last):  File "c:\Users\Documents\yolov5\myfile.py", line 11, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'custom', path='C:/Users/Documents/yolov5/runs/train/exp/weights/best.bt', force_reload=True)   
  File "C:\Users\anaconda3\lib\site-packages\torch\hub.py", line 540, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\anaconda3\lib\site-packages\torch\hub.py", line 569, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 81, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 76, in _create
    raise Exception(s) from e
Exception: [Errno 2] No such file or directory: 'C:\\Users\\Documents\\yolov5\\runs\\train\\exp\\weights\\best.bt'. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.
```
Also, I have no idea why the path becomes `'C:\\Users\\Documents\\yolov5\\runs\\train\\exp\\weights\\best.bt'`.

**Comment by glenn-jocher** [comment]
@int3r5t377ar the error is telling you that there is no file in the location you specified:
```
Exception: [Errno 2] No such file or directory: 'C:\\Users\\Documents\\yolov5\\runs\\train\\exp\\weights\\[best.bt](http://best.bt/)'
```

Windows loading of YOLOv5 PyTorch Hub models is run every 24 hours and operates correctly:
https://github.com/ultralytics/yolov5/actions/runs/3238824126/jobs/5307473149

https://github.com/ultralytics/yolov5/blob/16f87bb38e76a5aa14ee93252042063b678ece86/.github/workflows/ci-testing.yml#L133-L135

**Comment by int3r5t377ar** [comment]
> @int3r5t377ar the error is telling you that there is no file in the location you specified:
> 
> ```
> Exception: [Errno 2] No such file or directory: 'C:\\Users\\Documents\\yolov5\\runs\\train\\exp\\weights\\[best.bt](http://best.bt/)'
> ```
What should I do to use the `best.bt` file? The file is in the location there.

**Comment by glenn-jocher** [comment]
Looks like user error due a mispelling. You've got a *.bt suffix which you probably meant to write as *.pt

**Comment by int3r5t377ar** [comment]
> Looks like user error due a mispelling. You've got a *.bt suffix which you probably meant to write as *.pt

Oh thank you so much. I overlooked such a simple mistake over long time. And it works fine now. I am gonna close this question.

**Comment by bukobeer01** [comment]
> @int3r5t377ar the error is telling you that there is no file in the location you specified:
> 
> ```
> Exception: [Errno 2] No such file or directory: 'C:\\Users\\Documents\\yolov5\\runs\\train\\exp\\weights\\[best.bt](http://best.bt/)'
> ```
> 
> Windows loading of YOLOv5 PyTorch Hub models is run every 24 hours and operates correctly: https://github.com/ultralytics/yolov5/actions/runs/3238824126/jobs/5307473149
> 
> https://github.com/ultralytics/yolov5/blob/16f87bb38e76a5aa14ee93252042063b678ece86/.github/workflows/ci-testing.yml#L133-L135

**************************************************
can you help me I'm using torch 1.11.0+cu113

import torch
path = 'yolov5s.pt'
model = torch.hub.load('.', 'custom', path=path, source='local') 
print(model('images\1.jpg')) 

I got 
==============================
  File ".\load3.py", line 3, in <module>
    model = torch.hub.load('.', 'custom', path=path, source='local')
  File "C:\Users\bukob\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\bukob\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\hub.py", line 430, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "C:\Users\bukob\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\hub.py", line 76, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '.\\hubconf.py'

**Comment by Sha312003** [comment]
In the first argument of torch.hub.load write the path of yolo directory.
For example, instead of model = torch.hub.load('.', 'custom', path=path, source='local') write 
model = torch.hub.load('/content/yolov5', 'custom', path=path, source='local').
Hope this helps

**Comment by glenn-jocher** [comment]
@Sha312003 your error message suggests that your current directory does not contain a file called `hubconf.py`. You can specify the path to the directory that contains `yolov5s.pt` file using `torch.hub.load()` function like this:

```python
import torch

path = 'yolov5s.pt'
model = torch.hub.load('ultralytics/yolov5', 'custom', path=path, source='local') 
print(model(torch.randn(1,3,640,640))))
```

This code loads the `yolov5s.pt` file from the Ultralytics YOLOv5 hub repository and returns a detection model that can be used for inference on images. You can then call the model with an image tensor to get the predicted detections.

**Comment by dark292929** [comment]
tengo un error 

model = torch.hub.load('ultralytics/yolov5','custom',
                        path = 'D:/python/pythonProject/model/carros.pt', force_reload=True)


para subir mi modelo personalizable no reconoce,no se si alguien le paso

**Comment by glenn-jocher** [comment]
Hola! Parece que estás enfrentado un problema al cargar tu modelo personalizado. Asegúrate que la ruta al archivo `.pt` es correcta y accesible.

Tu código parece estar mayormente correcto, solo verifica la ruta. Aquí tienes un ejemplo ligeramente ajustado para asegurarnos que se usa correctamente:

```python
import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path='D:/python/pythonProject/model/carros.pt', force_reload=True)
```

Si el modelo sigue sin reconocer, verifica que `'carros.pt'` exista en la ruta especificada y que no haya errores en el nombre del archivo. ¡Espero que esto te ayude! 😊
