### ISSUE TITLE
How to save each category of pictures identified to a folder named corresponding to the category

### ISSUE THREAD

**Issue by chen136942027** [ultralytics/yolov5#9805]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to save each category of pictures identified to a folder named corresponding to the category

**Comment by glenn-jocher** [comment]
@chen136942027 you can use the `--save-txt` or `--save-hybrid` YOLOv5 command line arguments to save inference results to text files or both text and image files, respectively. For more details, please refer to the [Ultralytics documentation](https://docs.ultralytics.com/yolov5/). If you have further questions, feel free to ask!
