### ISSUE TITLE
How to change threshold of YOLOV5 that throw away bounding box

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/yolov5#9808]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using YOLO to detect bone fracture.   Based on my understanding of YOLO algorithm from YouTube lecture, YOLO will throw away the bounding box whose probability is less than 0.3. However, YOLO miss a lot of bone fractures in my dataset but occasionally can detect one or two whose probability is just 0.3.  Where I can modify YOLOV5 code to set this threshold 0.3 to 0.2, so I can keep more bounding box.  Otherwise, YOLOV5 for my dataset almost detect nothing.

**Comment by glenn-jocher** [comment]
@frabob2017 you can reduce --conf to increase recall, i.e.:

```
python detect.py --conf 0.10
```

Default value is 0.25

**Comment by frabob2017** [comment]
> @frabob2017 you can reduce --conf to increase recall, i.e.:
> 
> ```
> python detect.py --conf 0.10
> ```
> 
> Default value is 0.25

During the training, is there a way to lower this threshold?   90% of my training data are background images, this is the reason I guess why detection rate is almost zero.   By decreasing this threshold, I hope to increase some detection rate.

**Comment by frabob2017** [comment]
> --conf 0.10

great,  after decrease the threshold, higher detection rate even though there are still a lot missing. Keep on training.

**Comment by glenn-jocher** [comment]
> > @frabob2017 you can reduce --conf to increase recall, i.e.:
> > ```
> > python detect.py --conf 0.10
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Default value is 0.25
> 
> During the training, is there a way to lower this threshold? 90% of my training data are background images, this is the reason I guess why detection rate is almost zero. By decreasing this threshold, I hope to increase some detection rate.

No. Conference threshold is an inference parameter, not a training parameter.

**Comment by frabob2017** [comment]
By default 0.25, there is almost no detection.  However, I found that after I change threshold from 0.1 to 0.0001, there is no difference in detection rate.   I expect to the lower threshold, the higher detection rate although FP will also increase.  I use python val.py rather than detect.py. I want to compare ground truth (GT) vs prediction.

**Comment by frabob2017** [comment]
the improvement is more like that the model got more training rather than the threshold.

**Comment by glenn-jocher** [comment]
@frabob2017 changing '--iou-thres' to a lower value can increase the detection recall by allowing more overlapping predictions. However, it can result in more false positives. You may try values below 0.5 to see how it affects detection. Good luck!
