### ISSUE TITLE
DDP training . Training batch size and validation batch size are different.

### ISSUE THREAD

**Issue by SanKumSan** [ultralytics/yolov5#9812]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am conducting training using 4 GPUs DDP.

batch size = 8.

Training is performed on 4 GPUs and I can see that the total training images batches = training images/batch_size and is correct, during training epoch, but during validating, total validation images = total_test_images/4.

The figure will give the clear idea. 
There are 5600 training images and batch size used is 8, so we have 700 batches in each epoch.
There are 1400 images for validation, but the total batches is 350, which is 350 X 4 = 1400, but not 175 , 1400/8 = 175.
It should have been 175 batches in validation step.

I do not understand, why different batch size used for training and validating.

![deee](https://user-images.githubusercontent.com/57710619/195998240-20f92f41-5232-423d-83c2-79ab23bca6c8.PNG)

This 4 batchsize, is slowing down validation in each epoch.
Any help is appreciated and I am on money with the GPUs here.

Thanks in advance.

**Comment by glenn-jocher** [comment]
Larger batch size is used during validation for faster validation.

**Comment by SanKumSan** [comment]
Hello  @glenn-jocher thanks for your reply.
you are right, but here, **its actually half of the given batch_size.**

**Comment by glenn-jocher** [comment]
There's a miunderstanding in your interpretation of the console readout. Your validation and training sets are the same size. Train has been divided into 700 batches and val into 350, therefore each val batch is twice as large as each training batch.

**Comment by SanKumSan** [comment]
Validation step runs only on one GPU or all GPUs?

My concern is validation is slow, it has less images and still takes more time, because, the validation batch size is 4 which is wrong , because I have given batch_size = 8.

I am not sure if I really misread the console output, because, validation step clearly takes more time, because, the batch size during validation is not what I have given (8) instead it is half (4) of my input.

The number of images given above is the clear proof of this.

Thanks

**Comment by glenn-jocher** [comment]
@SanKumSan I've already explained to you that you are misunderstanding the console output and that val uses 2x the training batch size. 

Validation runs on single-GPU.

**Comment by SanKumSan** [comment]
Validation runs on single-GPU.
This answered my question, thanks for your help.

**Comment by glenn-jocher** [comment]
@SanKumSan you're welcome! If you have any more questions, feel free to ask. Good luck with your validation!
