### ISSUE TITLE
How to Stream Frames Real-Time using gstreamer

### ISSUE THREAD

**Issue by oes5756** [ultralytics/yolov5#9818]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

https://github.com/gustavozantut/yolov5_live_results

Through the corresponding yolov5 code,
Save the frame.

I hosted it in a raspberry pie environment.
"python detect.py --source 0 --save-frame"

Use gsreamer to capture frames that are stored in real time
I want to watch it on PC through live streaming, but I don't know how.

**Comment by glenn-jocher** [comment]
@oes5756 streams like webcams are automatically showed by detect.py if cv2 allows it:
https://github.com/ultralytics/yolov5/blob/e42c89d4efc99bfbd8c5c208ffe67c11632da84a/detect.py#L101-L102

**Comment by oes5756** [comment]
@glenn-jocher 

yes yolov5 command "python detect.py --source 0" is success in raspberry pi + pi camera
but raspberry pi the camera screen
I want to stream on PC.

**Comment by glenn-jocher** [comment]
@oes5756 you can stream the camera by piping the output to gstreamer, e.g. `python detect.py --source 0 --save-video --video-output gstreamer`. See the [YOLOv5 docs](https://docs.ultralytics.com/yolov5/) for more options.
