### ISSUE TITLE
Why is the total number the same as the other classes？

### ISSUE THREAD

**Issue by taotao6** [ultralytics/yolov5#9820]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/37886233/196120917-c86c9650-ec6b-49d5-8c44-960e79c4326b.png)

**Comment by glenn-jocher** [comment]
@taotao6 mAP computation includes all images. Whether they have TPs or not they can also have FPs for all classes.
