### ISSUE TITLE
PR Curve explaination

### ISSUE THREAD

**Issue by mim201820** [ultralytics/yolov5#9824]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello 
I just want to understand the PR Curve.

What are the numbers next to the labels is it the confidence or AP and what doest mean if that value is equal to 0

![Screenshot_20221017_123843-1](https://user-images.githubusercontent.com/65327419/196157988-7c727e00-59c1-46ca-99e9-e43c772e7359.png)

**Comment by glenn-jocher** [comment]
AP
