### ISSUE TITLE
What is `data` parameter doing in `export.py`?

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#9826]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Ultralytics team,

I would like to understand better the parameter what is doing the parameter `data` in this line:
https://github.com/ultralytics/yolov5/blob/e42c89d4efc99bfbd8c5c208ffe67c11632da84a/export.py#L579

I exported to TensorRT a custom model providing the `custom_data.yaml` file, but when I am goint to inference using `detect.py` I get the following results:
```
image 1/1 ......../image.png: 640x640 1 bicycle, 1 airplane, 1 train, 83.5ms
Speed: 0.7ms pre-process, 83.5ms inference, 1.6ms NMS per image at shape (1, 3, 640, 640)
```

is `data.yaml`parameter saving the classes for TensorRT? or does this just work for other kind of export methods?

Thanks in advance

### Additional

The code I am using for exporting to TensorRT is the following:
`python export.py --weights custom.pt --include engine --dynamic --workspace 4 --device 0 --batch-size 2 --data custom.yaml`

Any help will be appreciated.

**Comment by glenn-jocher** [comment]
@hdnh2006 dataset set is used by TFLite for INT8 quantization. For TensorRT it is unused during export.

TensorRT does not attach class names as metadata, so you can optionally pass a --data yaml during inference with correct class names.

**Comment by hdnh2006** [comment]
Thanks @glenn-jocher  for your quick reply, everything is understood now.

**Comment by glenn-jocher** [comment]
Great! Let me know if you have any other questions.
