### ISSUE TITLE
Something is wrong with Confusion matrix?

### ISSUE THREAD

**Issue by 1chimaruGin** [ultralytics/yolov5#9827]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Here is the confusion matrix from my custom dataset training. 

![confusion_matrix](https://user-images.githubusercontent.com/35499653/196178145-4dfa0801-ea65-4918-8859-e4d03d7f1096.png)

### Environment

Latest yolov5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MheadHero** [comment]
Not really sure, this is error or no. actually confusion matrix need tn also right? Hope @glenn-jocher can reply as well.

**Comment by glenn-jocher** [comment]
@MheadHero hey there! 👋 The confusion matrix you've shared looks good! For binary classification, a 2x2 matrix (containing true positives, false positives, true negatives, and false negatives) suffices, while for multi-class problems, it's generally larger.

If you're looking for more insights on confusion matrices and their interpretation, our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) could be really helpful! Let me know if you need further assistance.
