### ISSUE TITLE
opencv dnn 4.2.0 inference for yolov5 compatibility

### ISSUE THREAD

**Issue by MarioCiranni** [ultralytics/yolov5#9830]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I need to run inference with opencv dnn, with opencv version 4.2.0. Unfortunately, if I try to load the net in onnx format I get the following error:
cv2.error: OpenCV(4.2.0) ../modules/dnn/src/onnx/onnx_importer.cpp:110: error: (-215:Assertion failed) !tensor_proto.raw_data().empty() || !tensor_proto.float_data().empty() || !tensor_proto.double_data().empty() || !tensor_proto.int64_data().empty() in function 'getMatFromTensor'

However if I try to do the same with your new released classification models I do not encounter the above error.
I know I can solve the issue by upgrading the opencv version but I do need 4.2.0 version of opencv, could you help me out in understanding what differs in the models from the object detection (yolov5n.onnx) to classification(yolov5-cls.onnx) related to the opencv error ?
(My guess is that there is something different in the pyTorch saving procedure or anyway in the way variables are saved loosely speaking.)

**Comment by MarioCiranni** [comment]
anyone ?:'(

**Comment by glenn-jocher** [comment]
@MarioCiranni hi there! 🌟

Thank you for reaching out! The issue you're experiencing with OpenCV 4.2.0 and YOLOv5 object detection models is likely related to the format of the saved model. Our new YOLOv5 classification models may have been saved differently to avoid this specific error. 

Upgrading the OpenCV version is the recommended solution for compatibility. If you're unable to upgrade, you might consider using a conversion tool to modify the model format.

Hope this helps! 🚀
