### ISSUE TITLE
Remove the Output Node and Relevant Layers

### ISSUE THREAD

**Issue by anujdutt9** [ultralytics/yolov5#9833]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi. I am trying to remove the last output node and it's associated last layers from the trained model. What's the best way to do it? The goal of this experiment is to get the output from the 3 individual output nodes of different scales instead of a combined output using the "output" node.
I am using YOLOv5 v6.1 codebase, with YOLOv5s model trained on custom dataset.
I remember that in YOLOv5 v5.0, there used to be an option like `model.model[-1].export = not opt.grid` that could tell whether we want to include the Detect layer or not, but cannot find that in v6.1.

Thanks.

### Additional

I am trying to remove this last part specifically.

![image](https://user-images.githubusercontent.com/11924142/196287887-e7a10f50-fb6a-4b9a-bc07-378a7f5025f4.png)

**Comment by glenn-jocher** [comment]
@anujdutt9 you can select layers of the model pretty easily, i.e. `model.model[:-1]`. 

The Detect() module itself is in models/yolo.py if you want to modify it directly.

**Comment by anujdutt9** [comment]
Awesome, thanks 👍

**Comment by glenn-jocher** [comment]
@anujdutt9 you're welcome! If you have any other questions, feel free to ask. Good luck with your experiment!
