### ISSUE TITLE
Data enhancement issues

### ISSUE THREAD

**Issue by pengchen0429** [ultralytics/yolov5#9835]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Would it affect my final results if I used offline data enhancement to expand the number of images in the dataset, and then used my own online data enhancement?
Mainly expand my 2000 pictures to 10000 pictures by clipping, translating, adding noise and rotating angle.
Looking forward to your reply

**Comment by MartinPedersenpp** [comment]
It doesn't really matter how you do the data augmentation, but to be fair, I think it would be easier for you to test out your 2000 images as they are and then mess with the hyperparameters and do an evolve session: https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution
Best of luck to you

**Comment by glenn-jocher** [comment]
@MartinPedersenpp thanks for reaching out! It shouldn't significantly impact your results whether you enhance your data offline or online. You can expand your dataset using various techniques like clipping, translating, adding noise, and rotating angles as you suggested. However, to achieve the best performance, I recommend testing your initial 2000 images as they are and then experimenting with different hyperparameters using the hyperparameter evolution process.

Best of luck with your project!
