### ISSUE TITLE
Curious to know how best.pt is saved

### ISSUE THREAD

**Issue by gd1925** [ultralytics/yolov5#9836]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone!

I have been trying to understand the repo and the github have been very useful in trying to understand different tricks.
I was curious about one thing- how is the best.pt calculated? Is it the model with the most mAP (0.5) or mAP (0.5:0.95) scores? Or like the lease losses?

Thank you in advance for your answers!

**Comment by ExtReMLapin** [comment]
Please use the search function and don't hesitate to also use google

Answered here https://github.com/ultralytics/yolov5/issues/2303#issuecomment-786854853

**Comment by gd1925** [comment]
Thank you very much for your reply!

**Comment by ExtReMLapin** [comment]
Don't forget to close the issue 😊

**Comment by glenn-jocher** [comment]
@ExtReMLapin you're welcome! Our team really appreciates your understanding. If you need any further assistance, please don't hesitate to ask. Have a great day!
