### ISSUE TITLE
Issue exporting model trained via DDP

### ISSUE THREAD

**Issue by dalistarh** [ultralytics/yolov5#984]
Hi,

First, let me congratulate you on your super-useful framework!

I've been trying to fine-tune and then export a yolov3-spp variant to ONNX. 
Training works fine; I ran

> python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 128 --data coco.yaml --cfg yolov3-spp.yaml --weights ./weights/yolov3-spp.pt --epochs 100

However, when I try to export via 

> python models/export.py --weights ./runs/exp26/weights/last.pt  --img 640 --batch 1

I keep getting:

> Namespace(batch_size=1, img_size=[640, 640], weights='./runs/exp26/weights/best.pt')
> Traceback (most recent call last):
>   File "models/export.py", line 31, in <module>
>     model = attempt_load(opt.weights, map_location=torch.device('cpu'))  # load FP32 model
>   File "/home/dan/frameworks/coco/yolov5/models/experimental.py", line 137, in attempt_load
>     model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
>   File "/home/dan/neural-compression/env/lib/python3.6/site-packages/torch/serialization.py", line 584, in load
>     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>   File "/home/dan/neural-compression/env/lib/python3.6/site-packages/torch/serialization.py", line 842, in _load
>     result = unpickler.load()
>   File "/home/dan/neural-compression/env/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 460, in __setstate__
>     self.process_group = _get_default_group()
>   File "/home/dan/neural-compression/env/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 285, in _get_default_group
>     raise RuntimeError("Default process group has not been initialized, "
> RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

My machine has 4 V100 GPUs running CUDA 10.x.

Thanks!

**Comment by NanoCode012** [comment]
Hi, I did a quick test. I can successfully export to ONNX via ddp using the `5s` model on the latest commit trained on coco128. Could it be the model?
