### ISSUE TITLE
How I can convert all the output of yolov5 tflite into float32?

### ISSUE THREAD

**Issue by muntakim1** [ultralytics/yolov5#9851]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Here is a sample of my model input and output. I want all the outputs into float32, But it gives 3 outputs into float and 1 in int32.
How can I achieve this? I want to deploy my model to the cisco Meraki sense vision platform.

![image](https://user-images.githubusercontent.com/32785930/196610885-dca473a7-4fb9-4a36-a8bc-3c35993a2825.png)

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **Export Formats**. YOLOv5 🚀 offers export to most popular formats used today. See our [TFLite, ONNX, CoreML, TensorRT Export Tutorial](https://docs.ultralytics.com/yolov5/tutorials/model_export) for details.

## Formats

YOLOv5 inference is officially supported in 11 formats:

💡 ProTip: Export to ONNX or OpenVINO for up to 3x CPU speedup. See [CPU Benchmarks](https://github.com/ultralytics/yolov5/pull/6613).
💡 ProTip: Export to TensorRT for up to 5x GPU speedup. See [GPU Benchmarks](https://github.com/ultralytics/yolov5/pull/6963).

Format                      | `export.py --include`         | Model
:---                        | --:                           | :--
[PyTorch](https://pytorch.org/)                     | -                             | `yolov5s.pt`
[TorchScript](https://pytorch.org/docs/stable/jit.html)                 | `torchscript`                 | `yolov5s.torchscript`
[ONNX](https://onnx.ai/)                        | `onnx`                        | `yolov5s.onnx`
[OpenVINO](https://docs.openvino.ai/latest/index.html)                    | `openvino`                    | `yolov5s_openvino_model/`
[TensorRT](https://developer.nvidia.com/tensorrt)                    | `engine`                      | `yolov5s.engine`
[CoreML](https://github.com/apple/coremltools)                      | `coreml`                      | `yolov5s.mlmodel`
[TensorFlow SavedModel](https://www.tensorflow.org/guide/saved_model)       | `saved_model`                 | `yolov5s_saved_model/`
[TensorFlow GraphDef](https://www.tensorflow.org/api_docs/python/tf/Graph)         | `pb`                          | `yolov5s.pb`
[TensorFlow Lite](https://www.tensorflow.org/lite)             | `tflite`                      | `yolov5s.tflite`
[TensorFlow Edge TPU](https://coral.ai/docs/edgetpu/models-intro/)         | `edgetpu`                     | `yolov5s_edgetpu.tflite`
[TensorFlow.js](https://www.tensorflow.org/js)               | `tfjs`                        | `yolov5s_web_model/`
[PaddlePaddle](https://github.com/PaddlePaddle)               | `paddle`                        | `yolov5s_paddle_model/`


## CPU Benchmarks on Colab Pro+ CPU instance

Full [CPU benchmarks](https://github.com/ultralytics/yolov5/pull/6613)

```
benchmarks: weights=/content/yolov5/yolov5s.pt, imgsz=640, batch_size=1, data=/content/yolov5/data/coco128.yaml, device=cpu, half=False, test=False
Checking setup...
YOLOv5 🚀 v6.1-135-g7926afc torch 1.10.0+cu111 CPU
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 41.5/166.8 GB disk)

Benchmarks complete (241.20s)
                   Format  mAP@0.5:0.95  Inference time (ms)
0                 PyTorch        0.4623               127.61
1             TorchScript        0.4623               131.23
2                    ONNX        0.4623                69.34
3                OpenVINO        0.4623                66.52
4                TensorRT           NaN                  NaN
5                  CoreML           NaN                  NaN
6   TensorFlow SavedModel        0.4623               123.79
7     TensorFlow GraphDef        0.4623               121.57
8         TensorFlow Lite        0.4623               316.61
9     TensorFlow Edge TPU           NaN                  NaN
10          TensorFlow.js           NaN                  NaN
```

## GPU Benchmarks on Colab Pro+ V100 instance

Full [GPU benchmarks](https://github.com/ultralytics/yolov5/pull/6963)

```
benchmarks: weights=/content/yolov5/yolov5s.pt, imgsz=640, batch_size=1, data=/content/yolov5/data/coco128.yaml, device=0, half=False, test=False
Checking setup...
YOLOv5 🚀 v6.1-135-g7926afc torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 46.7/166.8 GB disk)

Benchmarks complete (458.07s)
                   Format  mAP@0.5:0.95  Inference time (ms)
0                 PyTorch        0.4623                10.19
1             TorchScript        0.4623                 6.85
2                    ONNX        0.4623                14.63
3                OpenVINO           NaN                  NaN
4                TensorRT        0.4617                 1.89
5                  CoreML           NaN                  NaN
6   TensorFlow SavedModel        0.4623                21.28
7     TensorFlow GraphDef        0.4623                21.22
8         TensorFlow Lite           NaN                  NaN
9     TensorFlow Edge TPU           NaN                  NaN
10          TensorFlow.js           NaN                  NaN
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by muntakim1** [comment]
The problem I am facing is when I export my model from pt to tflite. I need all the outputs as float32 but the exports function doesn't allow me to have all outputs in float32. I am using --nms option to get four outputs.

**Comment by muntakim1** [comment]
![image](https://user-images.githubusercontent.com/32785930/196687033-e993cde0-cb5f-407a-a794-7abbc46c39c7.png)

@glenn-jocher Why there is an Integer32 can you help me to fix this issue?

**Comment by muntakim1** [comment]
https://stackoverflow.com/questions/74127739/how-to-change-yolov5-tflite-model-output-to-float32
 I have asked a question in StackOverflow also

**Comment by glenn-jocher** [comment]
@muntakim1 👋 Hey! I see you're having trouble with YOLOv5's TFLite model outputs. While the model export script currently doesn't support converting all outputs to float32, one workaround is to manually modify the TFLite conversion script to accomplish this. I've seen your question on StackOverflow and will provide a detailed response there. Your feedback is helping to improve the YOLOv5 community, and we appreciate it!
