### ISSUE TITLE
Specific object coordinates

### ISSUE THREAD

**Issue by mr1fullhouse** [ultralytics/yolov5#9852]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do I single out a specific objects coordinates? I want to be able to play a video and while multiple objects of a single class are on the screen to get the  xywh coordinates of a single object closest to the center. 

-I have only one class in my custom data set
-I get around 10 to 15 objects detected
-I want to single out one and get its exact xywh
-I want to be able to save them to variables and get the centerof that specific object

Is there a spcific way to phrase what I am trying to do to make searching easier in the future? As well is there any documentation that goes into higher detail on how to select each individual object of a single class? So if i detect 12 faces how do I specifiy the coordinates of faces 3 and 5 and not all of them?

**Comment by MartinPedersenpp** [comment]
https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading
Using results.pandas will return a dataframe containing all of your bounding boxes, you can iterate over this and find the box closest to the center and save that in a variable.
I am not sure if you define closest to center as the corner closest to the center or the center of bounding box closest to center.
Good luck

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by mr1fullhouse** [comment]
Thank you MartinPedersenpp this helped a lot!

**Comment by MartinPedersenpp** [comment]
> Thank you MartinPedersenpp this helped a lot!

Glad that I could help 👍🏼
don't forget to mark this issue as solved, if your question has been answered.

**Comment by glenn-jocher** [comment]
@MartinPedersenpp you're welcome! I'm glad the information was helpful for you. If you have any more questions or need further assistance, feel free to ask. Have a great day!
