### ISSUE TITLE
Change YOLOv5 model so first convolution layer accepts 1 channel

### ISSUE THREAD

**Issue by Thomas-OBrien4** [ultralytics/yolov5#9854]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there, 

I have been trying to make yolov5 work on singular channel IR images and have found discussion #6288 very helpful, though now am receiving the error: 

Given groups=1, weight of size [32, 3, 6, 6], expected input[16, 1, 640, 640] to have 3 channels, but got 1 channels instead.

So I am now trying to change the number of input channels in the first convolution layer (in_channels) at the suggestion of: [https://discuss.pytorch.org/t/runtimeerror-given-groups-1-weight-64-3-3-3-so-expected-input-16-64-256-256-to-have-3-channels-but-got-64-channels-instead/12765/29](url). 

I have got as far as trying to alter the yolov5s.yaml file, but don't see a relevant argument for in_channels. 

I was just wondering whether this is the right approach or whether I am missing something.

Thank you very much for any help you can give me

**Comment by glenn-jocher** [comment]
You can add `ch: 1` in your yaml to build a model with 1 input channel.

**Comment by frabob2017** [comment]
> You can add `ch: 1` in your yaml to build a model with 1 input channel.

I saw you replied to a similar question, mention that 1 channel does not cost a lot of time in YoloV5. It look it is not important.

**Comment by glenn-jocher** [comment]
@tommob4 that's expected. First convolution layer represents <1% of the model's params and flops, so changing it from 1 to 3 input channel is a negligible effect on the model.

**Comment by glenn-jocher** [comment]
@Thomas-OBrien4 you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your YOLOv5 project!
