### ISSUE TITLE
How do I get the official versions of map_small?

### ISSUE THREAD

**Issue by LUO77123** [ultralytics/yolov5#9855]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to know what the official AAA version 6.1 or 6.0 APsmall and APmedium are. How do I get the official versions of map_small?
![image](https://user-images.githubusercontent.com/87272337/196696005-607f3ee5-c453-4b29-b50b-fae7769c159c.png)

### Additional

like this:
![image](https://user-images.githubusercontent.com/87272337/196696057-d5effce7-7dbc-4928-b522-34b3c0c9897d.png)

**Comment by glenn-jocher** [comment]
@LUO77123 see notebook for val example:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

<img width="666" alt="Screenshot 2022-10-19 at 15 02 58" src="https://user-images.githubusercontent.com/26833433/196698437-77acd2d8-6fc0-46b7-8e5d-ed547309a2d9.png">

**Comment by LUO77123** [comment]
> @LUO77123 see notebook for val example: https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
> 
> <img alt="Screenshot 2022-10-19 at 15 02 58" width="666" src="https://user-images.githubusercontent.com/26833433/196698437-77acd2d8-6fc0-46b7-8e5d-ed547309a2d9.png">

Thank you, but I only see the yolov5s version of APsmall. Are there any other versions?such as yolov5m or yolov5l.

**Comment by glenn-jocher** [comment]
Run any version you want yourself

**Comment by glenn-jocher** [comment]
@LUO77123 you can calculate mAP for any YOLOv5 model version using the `val.py` script in the YOLOv5 repository. Here is the command to calculate mAP for YOLOv5m:

```bash
python val.py --weights yolov5m.pt --img 640 --conf 0.001 --iou 0.65
```

Replace `yolov5m.pt` with the path to the YOLOv5m model weights. You can adjust the `--img`, `--conf`, and `--iou` parameters as needed.
