### ISSUE TITLE
Getting Error: (-5: Bad argument) when loading the YOLOv5 model with Open CV in C++

### ISSUE THREAD

**Issue by edargham** [ultralytics/yolov5#9857]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to deploy my YOLOv5 model with OpenCV 4.6.0 using C++. However, no matter what I try to do Open CV's ONNX importer throws the following runtime error:

```text
OpenCV(4.6.0) Error: Bad argument (Can't read ONNX file: .\yolov5s.onnx) in cv::dnn::dnn4_v20220524::ONNXImporter::ONNXImporter, file C:\opencv-4.6.0\opencv-4.6.0\modules\dnn\src\onnx\onnx_importer.cpp, line 255
```

This is the command I'm using to export the model in PowerShell:

```text
python .\yolov5\export.py --data "C:\vehicle_engine_yolov5s_r11\data.yaml" --weights "C:\vehicle_engine_yolov5s_r11\weights\best.pt" --simplify --include onnx
```

I tried it with my own exported weights using export.py and with the default weights and the result is still the same.

- I have also switched between the `master`, `v7.0` and `v7.0.1` branches and retrying the export.
- I also tried exporting the model in ProtoBuf (.pb) format.
- I even tried building Open CV from source.

**All to no avail.** 

I've honestly fired all my bullets and couldn't find anything online related to the problem and error, I cannot even know where the process is failing and if there's an error from my end. Here's my `main(void)` function where I load the model.

```c++
int main(void)
{
	try
	{
		std::vector<std::string> classList
		{
			"Bus",
			"Car",
			"Truck"
		};

		cv::Mat frame{ cv::imread("C:\\YOLO\\datasets\\vehicle_dataset\\test\\images\\1.jpg") };
		cv::dnn::Net net{ cv::dnn::readNet(".\\yolov5s.onnx") }; // This line throws the runtime exception in question.

		std::vector<double>  layersTimes{ };
		std::vector<cv::Mat> detections{ processInput(frame, net) };

		cv::Mat img{ postProcess(frame.clone(), detections, classList) };

		double freq{ cv::getTickFrequency() / 1000 };
		double timeTaken{ net.getPerfProfile(layersTimes) / freq };

		std::string label{ cv::format("Inference Time:\t%.4f ms", timeTaken) };

		cv::putText(img, label, cv::Point(20, 40), FONT_FACE, FONT_SCALE, RED);
		cv::imshow("Output", img);
		cv::waitKey(0);

		return 0;
	}
	catch (cv::Exception& e)
	{
		std::cout << std::endl << e.what() << std::endl;
		return -1;
	}
}
```
Is there a problem with my own code causing this to fail? In anyway, how can I solve this issue?

**Comment by edargham** [comment]
On Windows, make sure to use full paths. Relative paths don't work on Windows.
Solved it by changing `".\\yolov5s.onnx"` to `"C:\\list\\of\\sub\\dirs\\yolov5s.onnx"`

**Comment by glenn-jocher** [comment]
@edargham great to hear that you managed to solve the issue! 👍 You're absolutely right about the need to use full paths on Windows. It's a common pitfall when working with file paths in the Windows environment. If you encounter any more challenges or have further questions, feel free to reach out. The YOLOv5 community and the Ultralytics team are here to help!
