### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by thomassajot** [ultralytics/yolov5#9859]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

No sure where to put this issue as it is not a bug. 
The documentation of https://docs.ultralytics.com/tutorials/torchscript-onnx-coreml-export/ mentions the export scripts in `models/export.py` but is located at the root of the repo.

**Comment by glenn-jocher** [comment]
@thomassajot oh thanks! Sort of a bug. I'll fix.

**Comment by glenn-jocher** [comment]
@thomassajot docs are updated now!
