### ISSUE TITLE
Is it possible that my model never converges

### ISSUE THREAD

**Issue by arun-gautham** [ultralytics/yolov5#9864]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Iam training a model which seems to never end, the best.pt was generated about 200 epocs back

python train.py --img 1280 --batch 4 --epochs 4000 --hyp /content/yolov5/data/hyps/xxxxx.yaml --data {dataset.location}/data.yaml --resume <some path>/last.pt  --name <somepath> --exist-ok

How ever it is to be noted that i never did get 100 iterations in one session, due to colab sessions.

Is it that we need 100 iterations to stop in one session, or it could be in multiple sessions ?

This is the first time iam facing this issue , earlier we reached the best in about 150 epochs.

**Comment by MartinPedersenpp** [comment]
https://github.com/ultralytics/yolov5/blob/6371de8879e7ad7ec5283e8b95cc6dd85d6a5e72/utils/torch_utils.py#L380-L401

I know that best_fitness gets stored in the last.pt file, so I assume that all of the Earlystopper parameters gets stored as well, can you post your latest 100 results.csv lines and check that there has been no improvement in the last 100 epochs.

**Comment by arun-gautham** [comment]
[results.csv](https://github.com/ultralytics/yolov5/files/9827351/results.csv)

Attached is the csv file

**Comment by MartinPedersenpp** [comment]
Okay, so the best fitness value was around epoch 160, so something indicates that resuming might not pass values to the earlystopping feature

**Comment by ExtReMLapin** [comment]
It does converge, it just does it really soon

![image](https://user-images.githubusercontent.com/3909752/196989236-9e4dffdc-908d-4076-bd36-571dc883e666.png)

**Comment by glenn-jocher** [comment]
@ExtReMLapin thank you for the feedback. It seems that the model converges quite early in the training process. Regarding the EarlyStopping utility, you are correct, when resuming, the best fitness value is not passed to the feature. 

If you are considering contributing, a pull request to address this issue would be greatly appreciated. 

Your contribution would benefit the YOLO community and the Ultralytics team.
