### ISSUE TITLE
Unable to detect http and rstp under Windows 10

### ISSUE THREAD

**Issue by SSTato** [ultralytics/yolov5#9866]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I can correctly run python detect on Google Colab python detect.py --source 'https://ultralytics.com/images/zidane.jpg'
![image](https://user-images.githubusercontent.com/93987794/196897502-3ee13786-9e16-4d83-b1ce-0869555a449c.png)

However, an error will be reported under Window10
![image](https://user-images.githubusercontent.com/93987794/196897749-b463fb5a-07a9-4c72-9ff8-f32314545ac0.png)

The error reporting code is yolov5 6.2. When I use 5.0, it is normal. When I use 6.1, it also reports an error. If ROOT is removed, it can run successfully. However, there is no 5.0 process when detecting video streams.
![image](https://user-images.githubusercontent.com/93987794/196898616-7ae4bfca-e5e9-4fc6-b46e-81cd9487f0fd.png)
After my search, the error is the judgment of "if Path(sources).is_file()", but when I correct it, there will still be other errors.
![image](https://user-images.githubusercontent.com/93987794/196898719-ca14cd74-6306-4e76-b118-80b65ed06f01.png)

In any case, there are some problems with ’LoadStreams‘ under Windows10

### Environment

YOLO:YOLOv5-6.2  2022-6-30 Python-3.7.13 torch-1.7.1+cu110 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
OS:Windows10
python：3.7

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SSTato** [comment]
When I replace 
        if os.path.isfile(sources):
            with open(sources) as f:
                sources = [x.strip() for x in f.read().strip().splitlines() if len(x.strip())]
        else:
            sources = [sources]
 with
       sources = Path(sources).read_text().rsplit() if Path(sources).is_file() else [sources]
 it works normally.

![image](https://user-images.githubusercontent.com/93987794/196905379-e8b63a63-f5cf-4601-bd18-72a3ed7a2832.png)

**Comment by glenn-jocher** [comment]
@SSTato thanks! Can you please submit a PR with your fix?
