### ISSUE TITLE
when i use segment predict.py with save-txt the wrong have  occur how to resolve it ?

### ISSUE THREAD

**Issue by WANGCHAO1996** [ultralytics/yolov5#9868]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

python segment/predict.py  --save-txt
segment/predict: weights=best.pt, source=/data/wangch/k12-seg/segdata/images, data=data/seg.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=True, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/predict-seg, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1, retina_masks=False
YOLOv5 🚀 2022-10-7 Python-3.8.13 torch-1.8.1 CUDA:0 (GeForce RTX 2080 Ti, 11019MiB)

Fusing layers... 
YOLOv5x-seg summary: 330 layers, 88343789 parameters, 0 gradients, 264.3 GFLOPs
Traceback (most recent call last):
  File "segment/predict.py", line 273, in <module>
    main(opt)
  File "segment/predict.py", line 268, in main
    run(**vars(opt))
  File "/data/wangch/anaconda3/envs/torch1.8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "segment/predict.py", line 158, in run
    segments = reversed(masks2segments(masks))
  File "/data/wangch/yolov5-master/utils/segment/general.py", line 132, in masks2segments
    c = np.array(c[np.array([len(x) for x in c]).argmax()]).reshape(-1, 2)
ValueError: attempt to get argmax of an empty sequence
@jkocherhans

**Comment by WANGCHAO1996** [comment]
>

**Comment by glenn-jocher** [comment]
@WANGCHAO1996 good news 😃! Your original issue has resolved several days ago in a recent PR.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
