### ISSUE TITLE
Low GPU utilization for batch inference.

### ISSUE THREAD

**Issue by syntherick** [ultralytics/yolov5#9871]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi. I followed the instructions as per torch.hub documentation for batch inference. So, one thing I noticed is the GPU utilization is only 40-50% it never goes up to 80-100%, why is it like that?
 
![Screenshot from 2022-10-20 09-43-07](https://user-images.githubusercontent.com/59579709/196982103-f6e226c3-0782-41e9-ad7c-c496c884a0f2.png)

**Comment by ExtReMLapin** [comment]
Keep in mind this is "average" usage, it means it's used 40% of the time, not really at 40%.
In other words, there is a bottleneck somewhere else, maybe increase batch (not really with your current memory usage) or prepare the data ahead of being sent to the gpu so it doesn't have to "wait".

**Comment by syntherick** [comment]
@ExtReMLapin I am using following Dataset class dataloader uses batchsize=8 and numworkers=8:

` class YOLOv5ImgDataset(torch.utils.data.Dataset):
    """
    A Dataset class to perform Batch Processing for YOLOv5

    Args:
        img_list (list): List of path of images.
    """
    def __init__(
        self, 
        img_list, 
    ):
        self.img_list = img_list

    def __len__(
        self
    ) -> int:
        return len(self.img_list)

    def __getitem__(
        self, 
        index:int
    ) :
        imgpath = self.img_list[index]
        return imgpath `

**Comment by syntherick** [comment]
@ExtReMLapin I am using torch.hub for batch inference and I have massive dataset hence I designed above Dataset class such that 8 image paths per iteration are given to model for inference. Hope this makes sense

**Comment by ExtReMLapin** [comment]
`img_list` is filled with ready to use np arrays ?

**Comment by syntherick** [comment]
@ExtReMLapin yes it is prefilled with list of imagepaths (entire dataset).

**Comment by ExtReMLapin** [comment]
Alright, while i'm not exactly sure about what i'm about to say, you're storing either way paths to images (jpg) that need to be converted before being sent to the GPU OR paths to np arrays (files) that need to be loaded into ram before being sent to the GPU.

There are multiple strategies you can think of.

Right now, yolov5 has only 3 as far as I understood : 

* Do like you do , don't cache anything, and just report "paths"
* Convert all the images to np arrays and store them on the disk (npy files) so you can load them when needed, you save some CPU time, but you can lose I/O time, depending on your disk speed. 
* Keep everything in ram, it saves CPU and I/O time but eats a crazy amount of ram.

There is something more you can do, a trade of.

Preload `100` images in ram in a [`Queue`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue), ready to be used and sent to GPU, so as numpy arrays.
In another thread (a multiprocess process, not a python thread) fill this Queue as soon as it's quantity goes bellow `100`.
`100` being an arbitrary number, obviously.

The only thing it gives you here it a buffer to take absorb the time lost on I/O, while eating less ram.

**Comment by ExtReMLapin** [comment]
Hear me out, It's only going to work if :  

* Your disk usage is not at 100% usage
* Your cpu usage is not at 100% usage

**Comment by ice-tall-cold** [comment]
@syntherick Hi, I have a similar GPU low utilization issue when training on COCO dataset. I want to know if you have figured out the reason. Thanks!
