### ISSUE TITLE
--view-img Doesn't work in Docker image 

### ISSUE THREAD

**Issue by muhammedakyuzlu** [ultralytics/yolov5#9872]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I just installed the latest yolov5 Docker image, before that I used to run yolov5 locally, 
when I execute python detect.py --view-img 
it gives an error

QFactoryLoader::QFactoryLoader() checking directory path "/opt/conda/bin/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Is there anything I should install inside the docker image?

this is the way I run the image 

docker run --gpus all -it \
--name yolov5 \
-e DISPLAY=:0 -e TERM=xterm  \
-v /tmp/.X11-unix:/tmp/.X11-unix --privileged \
-v /dev/dri:/dev/dri \
--cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
-p 8888:8888 \
docker.io/ultralytics/yolov5:latest /bin/sh

**Comment by glenn-jocher** [comment]
@muhammedakyuzlu sorry, showing images with cv2.imshow() is no supported in Docker and certain other environments. This works in consoles locally.

**Comment by muhammedakyuzlu** [comment]
@glenn-jocher ok thanks for the inform

**Comment by glenn-jocher** [comment]
@muhammedakyuzlu you're welcome! If you have any more questions or need further assistance, feel free to ask. The YOLO community and the Ultralytics team are here to help!
