### ISSUE TITLE
Dual Camera

### ISSUE THREAD

**Issue by NBarile** [ultralytics/yolov5#9878]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello !

I have a simple question :
Can I use 2 webcam for detection and How can did it ?

I want to improve my vision detection with a second angle of camera,
and I try to adapt the detect.py code but I don't know how to do it.

Thanks !

**Comment by glenn-jocher** [comment]
@NBarile 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by MartinPedersenpp** [comment]
> I have a simple question : Can I use 2 webcam for detection and How can did it ?
> 
> I want to improve my vision detection with a second angle of camera, and I try to adapt the detect.py code but I don't know how to do it.
> 
> Thanks !

To expand on the tip from Glenn:
What you can do is load your model with torch hub.
With opencv or your preferred image processing module, you can open a stream for each of your webcams,
In a loop you can fetch a frame from each webcam and pass it through your YOLO model and perform your analysis of the data.
Be aware that depending on what you are trying to detect, your model will need to be trained on images from both angles.
Good luck!

**Comment by NBarile** [comment]
> > I have a simple question : Can I use 2 webcam for detection and How can did it ?
> > I want to improve my vision detection with a second angle of camera, and I try to adapt the detect.py code but I don't know how to do it.
> > Thanks !
> 
> To expand on the tip from Glenn: What you can do is load your model with torch hub. With opencv or your preferred image processing module, you can open a stream for each of your webcams, In a loop you can fetch a frame from each webcam and pass it through your YOLO model and perform your analysis of the data. Be aware that depending on what you are trying to detect, your model will need to be trained on images from both angles. Good luck!

I see the loop in detect.py, it's this :
`for path, im, im0s, vid_cap, s in dataset:`

But I don't know how to change it, I'm a beginner in python and I don't understand this for loop... 

I thinking I can add directly the new camera inferance in this for, but i don't know how to add it.... 

Or I can lunch detect.py twice for my two camera, but I think the performance will be reduced

**Comment by MartinPedersenpp** [comment]
@NBarile Ideally you don't want to use detect.py, but create your own script with torch and opencv
