### ISSUE TITLE
Segmentation of selected objects

### ISSUE THREAD

**Issue by iman-badr** [ultralytics/yolov5#9882]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using Yolov5 to segment objects. I am supposed to hide specific objects like persons for security reasons. I could hide all detected objects by using parmater alph=0.9 when calling  annotator.masks
However, I cannot differentiate between objects since the filter is applied to all filters
Does any one know how this could be done
thank you in advance,
Iman Badr

**Comment by glenn-jocher** [comment]
@iman-badr hi Iman, 

To segment specific objects such as persons for security reasons, you can modify the YOLOv5 inference code to apply the alph value specifically to detected persons.

For detailed guidance, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ or ask for further assistance in the discussions.
