### ISSUE TITLE
Yolov5 Detect is over-writing Open-CV version

### ISSUE THREAD

**Issue by Narasimmavinay** [ultralytics/yolov5#9883]
Hi,

I am trying to use aruco detection along with the yolov5 detection but yolov5 is over-writing the existing opencv-contrib version => 4.6.0 to 4.1.2 and I get the below error

"module 'cv2' has no attribute 'aruco'"

Can you pls suggest a way to prevent over-writing of existing versions of libraries?

Thanks in advance

**Comment by glenn-jocher** [comment]
@Narasimmavinay you might try commenting out the requirements check in detect.py to see if that helps here:
https://github.com/ultralytics/yolov5/blob/eef90572bf11602b17816a1721980cdb07a95eb2/detect.py#L252

**Comment by glenn-jocher** [comment]
@Narasimmavinay great I'm glad to hear that! Let us know if you find any other bugs or think of additional useful features that YOLOv5 lacks!
