### ISSUE TITLE
--resume traning from wandb stoped after first epoch 

### ISSUE THREAD

**Issue by mohamadjaara97** [ultralytics/yolov5#9886]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! 
I tried to resume my training from wandb but i get everytime the same problem what i cant really understand. 

Hier is my wandb project: https://wandb.ai/mohamadjaara/train/runs/1z9gnh1y/overview?workspace=user-mohamadjaara

Note: i got the same Error in all other projects too

and thats the Error what i got: 

**Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
     48/299      5.06G    0.02119    0.01505    0.02205         89        320: 100%|██████████| 5999/5999 [27:47<00:00,
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   0%|          | 0/503 [00:00
Traceback (most recent call last):
  File "train.py", line 632, in <module>
    main(opt)
  File "train.py", line 526, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 349, in train
    results, maps, _ = validate.run(data_dict,
  File "C:\Users\ma777\anaconda3\envs\traning\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Yolo\yolov5\val.py", line 263, in run
    callbacks.run('on_val_image_end', pred, predn, path, names, im[si])
  File "C:\Yolo\yolov5\utils\callbacks.py", line 76, in run
    logger['callback'](*args, **kwargs)
  File "C:\Yolo\yolov5\utils\loggers\__init__.py", line 205, in on_val_image_end
    self.wandb.val_one_image(pred, predn, path, names, im)
  File "C:\Yolo\yolov5\utils\loggers\wandb\wandb_utils.py", line 506, in val_one_image
    box_data = [{
  File "C:\Yolo\yolov5\utils\loggers\wandb\wandb_utils.py", line 513, in <listcomp>
    "box_caption": f"{names[int(cls)]} {conf:.3f}",
KeyError: 0
wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.**

**Comment by glenn-jocher** [comment]
@mohamadjaara97 hi there! 👋 It looks like the issue might be related to a KeyError during training. Could you please confirm if you have a specific set of instructions you're following to resume training from wandb? You may want to ensure that your environment and dependencies are all set up correctly. If you're still encountering the issue, please provide more details about your setup so we can better assist you. Thank you!
