### ISSUE TITLE
TypeError: update_output_model() got an unexpected keyword argument 'auto_delete_file'

### ISSUE THREAD

**Issue by JeremyCraigMartinez** [ultralytics/yolov5#9889]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

[Change from 2 months back](https://github.com/ultralytics/yolov5/commit/5cb9fe612a215e0b7f6d99bf39e91cc52ab13c53#diff-33c598c680edd3d5bb6a80177861c1a89a6c4f17bea580adb0212e772b268c9dR238) seems to be failing. Perhaps a newer version of ClearML stripped this argument. Maybe a fix for this would be to add a version requirements for ClearML or remove it altogether? 

```
Traceback (most recent call last):
  File "yolov5/train.py", line 630, in <module>
    main(opt)
  File "yolov5/train.py", line 524, in main
    train(opt.hyp, opt, device, callbacks)
  File "yolov5/train.py", line 424, in train
    callbacks.run('on_train_end', last, best, epoch, results)
  File "/home/ec2-user/SageMaker/Signature detection/yolov5/utils/callbacks.py", line 76, in run
    logger['callback'](*args, **kwargs)
  File "/home/ec2-user/SageMaker/Signature detection/yolov5/utils/loggers/__init__.py", line 297, in on_train_end
    auto_delete_file=False)
TypeError: update_output_model() got an unexpected keyword argument 'auto_delete_file'
```

### Environment

- YOLO: YOLOv5x
- Sagemaker (EC2: ml.p2.xlarge)
- Python: 3.7.12
- OS: Linux ip-172-16-95-121 4.14.294-150.533.amzn1.x86_64 #1 SMP Thu Sep 29 00:51:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- ClearML: 1.0.3

### Minimal Reproducible Example

```
!python yolov5/train.py ...
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@JeremyCraigMartinez hi, thanks for the bug report!

@thepycoder can you take a look at this bug? It looks like a ClearML argument no longer exists but is being passes in the YOLOv5 code. This is occurring in two places in the loggers/__intit__.py:

<img width="828" alt="Screenshot 2022-10-24 at 22 23 44" src="https://user-images.githubusercontent.com/26833433/197621918-b16207ec-9d7c-4461-adfb-c8df76c3584e.png">

Should we just delete this argument and problem solved?
```
TypeError: update_output_model() got an unexpected keyword argument 'auto_delete_file'
```

**Comment by glenn-jocher** [comment]
@thepycoder opened PR #9909 with possible fix, can you please review?

**Comment by thepycoder** [comment]
Hey @glenn-jocher,

Sorry for the late reply. Getting rid of the `auto_delete_file` would just resurface bug #9251 which I fixed by adding this paramter in PR #9265.

It seems to be breaking because of ClearML version being 1.0.3, which is quite old by now (1y 4m) and didn't have the required parameter yet. So a quick fix for @JeremyCraigMartinez is to update your clearml if possible :) This intergation was written much more recently and didn't take older clearml versions into account.

That said, I agree we don't want it to break randomly for people, so wdyt:

- Add a minimum version number to the requirements file, even if clearml is just in comments?
- Add a try except clause to catch it and warn user
- Add a clear note in the ClearML readme
- Maybe enforce a minimum version at intialization time, where the actual clearml import is done already in a try except clause anyway?

**Comment by glenn-jocher** [comment]
@thepycoder got it! We definitely want to add version requirements then in the commented line in requirements.txt, other than that we can check version on import (with a warning, a pip update, both, or just an assert etc). 

I'll close #9909.

**Comment by glenn-jocher** [comment]
@thepycoder opened #9933 with updates to requirements.txt and ClearmL tutorial adding minimum requirements for pip install clearml>=1.2.0

**Comment by glenn-jocher** [comment]
@JeremyCraigMartinez the main problem is that your clearml package is out of date (version >=1.2.0 is required with YOLOv5). Please your ClearML with and try again, and let us know if this fixes your problem. Thanks!
```
pip install -U clearml
```

**Comment by glenn-jocher** [comment]
@thepycoder PR is merged providing better awareness for version constraints with YOLOv5. Let's see how this works and then we can escalate to more measures like version checks on imports if this continues to be a problem. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐
