### ISSUE TITLE
How to SIMPLIFY inference on a single image?

### ISSUE THREAD

**Issue by vantienpham** [ultralytics/yolov5#989]
## ❔Question
Dear all, I've read all the tutorial and related part of this repositories including training on custom datasets, using detect.py.
That's great!
My problem is the file detect.py is accepts many options (--source accept video, directories, images...) and this make the codes too long and complicated.
I trained yolov5s on my custom dataset, I got the best.pt and I tried to inference on a video using detect.py, it works well.
In my case, I just want a script/function that receive an image and return list of predicted objects.
For example:
```
def get_predictions(image, model=best.pt, opt):
    predictions = [[class_id1 bouding_box1 score1], [class_id1 bouding_box1 score1], ...] 
    #list of predictions when inference using best.pt, bounding_box should be in any format, I will convert it to my format later: top left bottom right 
    return predictions
```
I'm in rush so I hope someone experienced with this repo can help me quick.
Any suggestion is highly appriciated!
Many thanks!

**Comment by NanoCode012** [comment]
Hi @pvtien96 , you don't have to pass in all the arguments. Only some of them. For saving predictions, you could be looking for 

https://github.com/ultralytics/yolov5/blob/5a9c5c1d3b02c8796e6af153d57af5821d8db0d6/detect.py#L159

Here should be the complete command:

```bash
python detect.py --source img.jpg --weights path/to/best.pt --save-txt
```

**Comment by vantienpham** [comment]
Hi @NanoCode012 , yes, your opinion works, but I need a function to integrate into my own application, not whole the file detect.py.

**Comment by NanoCode012** [comment]
@pvtien96 , oh I see! I think you can slightly modify detect function’s input and output to suit your needs. I don’t think there’s a way to call detect as a function per your purpose right now without changing anything.
