### ISSUE TITLE
about swing transformer

### ISSUE THREAD

**Issue by zcswdt** [ultralytics/yolov5#9890]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to apply swing transformer to the feature extraction network of yolo network,thank you

**Comment by glenn-jocher** [comment]
@zcswdt you'd need to update a custom model yaml with the architecture and modules you are interested in.

**Comment by zcswdt** [comment]
> @zcswdt you'd need to update a custom model yaml with the architecture and modules you are interested in.

thank you
