### ISSUE TITLE
weights-cgf file to .pt file

### ISSUE THREAD

**Issue by JDJelectronics** [ultralytics/yolov5#9893]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there,

how can i convert weights / cfg to  a .pt file?

Greats Jelmer

**Comment by glenn-jocher** [comment]
@JDJelectronics no
