### ISSUE TITLE
RuntimeError: shape '[128, 16, 144, 4]' is invalid for input of size 2064384

### ISSUE THREAD

**Issue by tangruinenu** [ultralytics/yolov5#9894]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      0/299      33.6G    0.07417    0.07462    0.07416        242        640: 100%|██████████| 1833/1833 [28:01<00:00,  1.09it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   0%|          | 0/39 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 631, in <module>
    main(opt)
  File "train.py", line 525, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 349, in train
    results, maps, _ = validate.run(data_dict,
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/testgpu/yolov5-master/val.py", line 209, in run
    preds, train_out = model(im) if compute_loss else (model(im, augment=augment), None)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/testgpu/yolov5-master/models/yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/testgpu/yolov5-master/models/yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/testgpu/yolov5-master/models/common.py", line 1411, in forward
    out3=self.csp2(x1)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/testgpu/yolov5-master/models/common.py", line 999, in forward
    x_2=self.focuspa2(x_2)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/testgpu/yolov5-master/models/common.py", line 1152, in forward
    Q = self.query_conv(x).view(m_batchsize, n, (height//2)*(height//2), 2 * 2)
RuntimeError: shape '[128, 16, 144, 4]' is invalid for input of size 2064384

Why is there such a problem in validation after a round of training? And I set batch to 64 instead of 128

### Environment

YOLOv5 🚀 2022-10-21 Python-3.8.0 torch-1.13.0.dev20220815+cu116 CUDA:0 (NVIDIA A40, 48486MiB)

### Minimal Reproducible Example

Why is there such a problem in validation after a round of training? And I set batch to 64 instead of 128

### Additional

Why is there such a problem in validation after a round of training? And I set batch to 64 instead of 128

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tangruinenu 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. The error here appears to be from custom code that you've written.

Validation runs at twice the batch size of training for better validation speed.


## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by tangruinenu** [comment]
> @tangruinenu 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. The error here appears to be from custom code that you've written.
> 
> Validation runs at twice the batch size of training for better validation speed.
> 
> ## How to create a Minimal, Reproducible Example
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
> * ✅ **Minimal** – Use as little code as possible to produce the problem
> * ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
> * ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:
> 
> * ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
> * ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.
> 
> If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! 😃

Thank you, but if I can train normally, is it to prove that my network structure is OK? And I have tested coco128 with my code and it is OK. It seems that there is something wrong with the validation set of COCO.

**Comment by glenn-jocher** [comment]
In general any custom modules you create must be robust to any batch size. Even if you request a batch size the last batch in a set may be smaller.

**Comment by tangruinenu** [comment]
> In general any custom modules you create must be robust to any batch size. Even if you request a batch size the last batch in a set may be smaller.

The problem now is that the feature dimensions don't match. If it wasn't the dataset, then why was I able to run 300 times on coco128? During verification, the input should also be (640,640), but the result error is mainly caused by the wrong height and width of the feature map

**Comment by glenn-jocher** [comment]
@tangruinenu it's understandable that encountering a discrepancy in the feature dimensions can be puzzling, especially after successful training on the coco128 dataset. It's essential to verify that the input dimensions during validation match the expected values. Additionally, considering potential differences between the coco128 and COCO datasets is advisable.

If you'd like further assistance in troubleshooting and resolving this issue, please consider providing a concise, reproducible example to help our team investigate and address the matter effectively. Thank you for your understanding and cooperation!
