### ISSUE TITLE
About W&B support

### ISSUE THREAD

**Issue by ShpihanVlad** [ultralytics/yolov5#9897]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I see that you've recently removed Weights and Biases from tutorial, so is that a subject to be deprecated?

**Comment by glenn-jocher** [comment]
@ShpihanVlad hi there! The recent removal of Weights and Biases (W&B) support from the tutorial is not indicative of deprecation. We continually update the repository to ensure that it reflects the latest developments in YOLOv5. You can find the most current information and guidance on using W&B with YOLOv5 in our documentation at https://docs.ultralytics.com/yolov5/. Let me know if you have any other questions!
