### ISSUE TITLE
Obviously inaccurate detection on Apple Silicon with MPS acceleration

### ISSUE THREAD

**Issue by TANG617** [ultralytics/yolov5#9900]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I've read the tutorial from https://github.com/ultralytics/yolov5/pull/7878 and solve the problem 'The operator 'aten::nonzero' is not currently supported on the MPS backend' from https://github.com/ultralytics/yolov5/issues/8508

And the setup command is just like the following:
```
(Torch-GPU-Latest) timli@MacBook-Pro-by-Tang yolov5-master % PYTORCH_ENABLE_MPS_FALLBACK=1 python detect.py --device mps --source 0
detect: weights=yolov5s.pt, source=0, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=mps, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 2022-9-25 Python-3.10.6 torch-1.14.0.dev20221023 MPS

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
1/1: 0...  Success (inf frames 1920x1080 at 30.00 FPS)
```

It seems to work, but the result is  obviously wrong. 

![202210240930567fVU7TScreenshot2022-10-24at09.29.41](https://cdn.jsdelivr.net/gh/TANG617/images@master/20221024093614Kqfs1K202210240930567fVU7TScreenshot%202022-10-24%20at%2009.29.41.png)

And it crashes.

```
0: 384x640 2 persons, 10.5ms
Traceback (most recent call last):
  File "/Users/timli/MyLibrary/yolov5-master/detect.py", line 259, in <module>
    main(opt)
  File "/Users/timli/MyLibrary/yolov5-master/detect.py", line 254, in main
    run(**vars(opt))
  File "/Users/timli/opt/anaconda3/envs/Torch-GPU-Latest/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/timli/MyLibrary/yolov5-master/detect.py", line 170, in run
    label = None if hide_labels else (names[c] if hide_conf else f'{names[c]} {conf:.2f}')
KeyError: 168
```

If I don't enable '--device mps', it works perfectly.
BTW, it seems that 'mps' boost about 5 times over 'cpu', which is exciting. 

### Environment

- YOLOv5 🚀 2022-9-25 Python-3.10.6 torch-1.14.0.dev20221023 MPS
- macOS 13.0 (22A379)
- Apple M1 Pro on MBP 14 2021 with 16GB Memory

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@TANG617 yes MPS seems to produce issues on detection models, but classification models work correctly. I don't know exactly where the problem lies.

**Comment by jgoo9410** [comment]
+1

**Comment by 25benjaminli** [comment]
This needs more attention.

**Comment by jgoo9410** [comment]
https://github.com/ultralytics/yolov5/issues/10178#event-8197299228

**Comment by lonnylundsten** [comment]
I'm running a custom trained model on an M1 Max MBP and I get the following error after running inference on 18 images.
If I use the  '--hide-labels' flag it works ok -- 125,000+ images.

```
Traceback (most recent call last):
  File "/Users/lonny/Documents/Code/Python/yolov5/detect.py", line 261, in <module>
    main(opt)
  File "/Users/lonny/Documents/Code/Python/yolov5/detect.py", line 256, in main
    run(**vars(opt))
  File "/Users/lonny/.pyenv/versions/3.11.3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lonny/Documents/Code/Python/yolov5/detect.py", line 172, in run
    **label = None if hide_labels else (names[c] if hide_conf else f'{names[c]} {conf:.2f}')**
                                                                    ~~~~~^^^
KeyError: 380
```

**Comment by glenn-jocher** [comment]
@lonnylundsten hello! Thank you for reaching out to us and bringing this up. 

I understand your concern regarding using MPS backend with the YOLOv5 detection model. It seems that MPS produces issues on detection models, as mentioned by member of the YOLOv5 community. We appreciate your patience with this issue.

We are continuously working on improving the YOLOv5 model, the bug reports we credit to our community and try to solve them as efficiently as possible. Unfortunately, due to the limitations of this issue, we are unable to provide you with a more detailed response at the moment.

Nonetheless, please be assured that we are aware of this matter, and we will provide an update as soon as we have a fix for it. We encourage you to keep an eye on our updates, YOLOv5 documentation, and tutorials for more information.

If you have any other questions or concerns, please don't hesitate to keep asking. We're here to help.
