### ISSUE TITLE
Question regarding the metrics (Precision, Recall, mAP)

### ISSUE THREAD

**Issue by HCL-91** [ultralytics/yolov5#9904]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear editors, 

I have been training and testing yolov5 on various datasets.
However, only recently, I began to pay closer attention to the metrics given by yolo.

I understand that mAP is given by calculating the Precision-Recall curves for multiple IoU thresholds (0.5 : 0.05: 0.95)
But, I was not quite sure what the final Precision and Recall values meant precisely.

![image](https://user-images.githubusercontent.com/67674024/197508378-6e57dda2-a674-4756-a905-f2f036c78887.png)

For obtaining the values under 'P' and 'R', I was not sure what confidence threshold and IoU threshold were used.
For example, for the results above, since 'P' is 1, I should not be seeing any False Positive predictions.
But once I print all of the predicted results, I often find False Positive predictions. 
So I felt that I was not using the proper thresholds for which the model achieves 'P' of 1.

I would greatly appreciate your help on this matter.
 
Always thanks for your great work!

**Comment by glenn-jocher** [comment]
@HCL-91 P and R computations shown in YOLOv5 are presented at the maximum F1 confidence threshold, which should produce the best balance of P and R. 

![image](https://user-images.githubusercontent.com/26833433/197618720-28afc826-c7d6-4518-a68a-15fccae82c44.png)

You can find the code responsible for this threshold determination here, and if you want you can assign it a static threshold like 0.25, which is nominally used in other places like detect.py and the val.py confusion matrix.

https://github.com/ultralytics/yolov5/blob/fba61e55836273847947498c01314499d8e5e7dc/utils/metrics.py#L91-L92

**Comment by HCL-91** [comment]
Thank you very much for the response.
Given the best 'P' and 'R' it possible to find the corresponding confidence & IoU threshold
such that I can run 'detect.py' and 'val.py' using those values?
(I am assuming that loading 'best.pt' works in this case)

Thank you,

**Comment by HCL-91** [comment]
Thanks for the help, I'm seeing things more clearly now.

Sorry to be a nuisance, but just last bits of questions are the following :

For the code below,
 i = smooth(f1.mean(0), 0.1).argmax()  # max F1 index 
 p, r, f1 = p[:, i], r[:, i], f1[:, i] 

I am led to believe that iou value used is 0.5 for calculating 'p', 'r', and 'f1' (iou for deteremining TP & FP, not the iou-thresh for NMS)
and 'i' represents the conf-thres which gives the best  f1-score.

Am I correctly understanding the 'p' and 'i' ?

Thank you so much,

**Comment by glenn-jocher** [comment]
p is precision and i in the index of max f1 condidence

**Comment by aqsab2022-ami19** [comment]
in Yolov 5, why the precision and recall shown in the terminal not the same as the calculation of the same confusion matrix? I mean, why the terminal-generated P and R different from the confusion matrix calculation?

**Comment by aqsab2022-ami19** [comment]
Please help me to understand it. why the result is different?
![387494365_313913204941357_8364698442219586867_n](https://github.com/ultralytics/yolov5/assets/153488985/700fbcb2-b651-4e37-997a-53c8d911e03b)

**Comment by glenn-jocher** [comment]
@aqsab2022-ami19 the precision and recall values shown on the terminal are computed at the maximum F1 confidence threshold, which aims to balance precision and recall. The confusion matrix provides precision and recall values that may differ since they are calculated based on the IoU and confidence thresholds. For more detailed information, refer to the [`metrics.py`](https://github.com/ultralytics/yolov5/blob/master/utils/metrics.py) code to understand how these values are derived.

**Comment by abetancordelrosario** [comment]
> Please help me to understand it. why the result is different? ![387494365_313913204941357_8364698442219586867_n](https://private-user-images.githubusercontent.com/153488985/289458107-700fbcb2-b651-4e37-997a-53c8d911e03b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjU2NjgsIm5iZiI6MTcxNjM2NTM2OCwicGF0aCI6Ii8xNTM0ODg5ODUvMjg5NDU4MTA3LTcwMGZiY2IyLWI2NTEtNGUzNy05OTdhLTUzYzhkOTExZTAzYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwODA5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjA4ZWVmZjkyZTVlODM1OTQ5ZTNkZWM3YTY0NDEyMDQxZDE5MDc1ZWMwNDBhZDk0NTFmYTMyMGZiOTE2MDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iA5UsSj5eimjW3QCV8KSqbnkX71yXCSGlBxvLJFPAxI)

@aqsab2022-ami19 did you solve this problem?
