### ISSUE TITLE
Use Yolo for anomaly detection

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#9906]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

I do have my software running with a yolo network that recognizes some folded crates. Since Yolo is already implemented, I was thinking to add a second network that runs in parallel, to detect if the crate has some bags inside and if it is broken (aka walls missing.)

Basically the idea is to train a generic network that can differentiate between:

- a crate
- a broken crate
- a crate with bag.

the crates can vary in shape and color, so I was wondering if this is a good idea. 
my questions are:

1) Does it make sense to use yolo for anomaly detection if it has to simply "categorize"  by kind of defect without giving any other information about the location or whatever of the anomaly?
2) Does it have to have image of every shape/color of the OK crates, or will it be able to learn that a crate with all walls is symmetric? wo basically, is it able to learn the concept of "crate with 4 walls" without having every single example, but only 70/80% of them?
3) would it be better to tag the whole crate as "crate without a wall" or "crate with a bag inside", or rather the "missing wall" object and the "bag" object?

any help on this is greatly appreciated.

**Comment by glenn-jocher** [comment]
@tanzerlana yes YOLO will work for anomaly detection and/or detection of different types of crates like normal, damaged etc. The simplest way to start is to collect a dataset of the breakdown you are interested and and then train a model to establish a performance baseline. See Tips for Best Results for additional details.

## Tutorials

- [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
- [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️ RECOMMENDED
- [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
- [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) 🌟 NEW
- [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
- [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
- [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
- [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
- [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
- [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)
- [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description) 🌟 NEW
- [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)
- [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)  🌟 NEW
- [ClearML Logging](https://docs.ultralytics.com/yolov5/tutorials/clearml_logging_integration) 🌟 NEW
- [Deci Platform](https://github.com/ultralytics/yolov5/wiki/Deci-Platform) 🌟 NEW
- [Comet Logging](https://docs.ultralytics.com/yolov5/tutorials/comet_logging_integration) 🌟 NEW

Good luck 🍀 and let us know if you have any other questions!
