### ISSUE TITLE
Why the "forward" function has changed in the Detect class

### ISSUE THREAD

**Issue by EveningLin** [ultralytics/yolov5#9910]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In previous versions, 0.5 was subtracted to make it within the range of (- 0.5, 1.5)
```
if self.inplace:
                    y[..., 0:2] = (y[..., 0:2] * 2 - 0.5 + self.grid[i]) * self.stride[i]  # xy
                    #box center的x,y的预测被乘以2并减去了0.5，让他的预测范围变成（-0.5，1.5）就是能跨半个网格预测
                    #然后加上self.grid[i]，就是加上网格的宽度/高度
                    #最后乘上self.stride[i]，就是步长，定位到原先预测的那个点
                    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
                    #对预测框高宽的处理

```
however，in latest version it has change  . i would like to ask for the reason .thx
```
                if self.inplace:
                    y[..., 0:2] = (y[..., 0:2] * 2 + self.grid[i]) * self.stride[i]  # xy
                    # box center的x,y的预测被乘以2并减去了0.5，让他的预测范围变成（-0.5，1.5）就是能跨半个网格预测
                    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
```

**Comment by glenn-jocher** [comment]
@EveningLin the 0.5 grid offset is now applied to self.grid[i], reducing the need for this operation in every forward pass.

**Comment by EveningLin** [comment]
thank you for your reply. 
two more questions hoping you could help me.
(1)Why square （** 2）
`y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh`

（2）SAM optimizer could not be applied in yolov5。
SAM optimizer: https://github.com/davda54/sam#readme

**Comment by EveningLin** [comment]
@glenn-jocher thank you for your reply.
two more questions hoping you could help me.
(1)Why square （** 2）
y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i] # wh

（2）SAM optimizer could not be applied in yolov5。
SAM optimizer: https://github.com/davda54/sam#readme

**Comment by glenn-jocher** [comment]
@EveningLin **2 is part of the anchor equation y = (x * 2) ** 2 - 0.5

**Comment by glenn-jocher** [comment]
I'm not familiar with the SAM optimizer, for this question you might want to ask the author

**Comment by EveningLin** [comment]
thanks a lot

**Comment by glenn-jocher** [comment]
@EveningLin you're welcome! If you have any more questions, feel free to ask. Good luck with your work!
