### ISSUE TITLE
Dominated Color of an Object

### ISSUE THREAD

**Issue by joesouaidd** [ultralytics/yolov5#9914]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Greetings,

I would like to ask if there's a way to extract the dominant color of an object detected.

Thank you.

**Comment by glenn-jocher** [comment]
@joesouaidd seems like a cv2 postprocessing op unrelated to ML
