### ISSUE TITLE
ONNX: export failure   ----yolo-pose branch have the same bug of #6995

### ISSUE THREAD

**Issue by ZhangLe-fighting** [ultralytics/yolov5#9923]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

yolov5-pose have the same bug（#6995），ONNX: export failure: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
Since that community is not active, I hope to get help here.

### Environment

torch 1.12.1 + cuda102
python 3.8
onnx 1.8.1
Linux hik-gpu 4.15.0-142-generic 16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Minimal Reproducible Example

'''
download zip https://github.com/TexasInstruments/edgeai-yolov5.git --yolo-pose
copy to gpu server
cd repository
# input 
python models/export.py --weights yolov5_coco_model/yolov5_coco.pt  --img 640 --batch 1 --simplify --export-nms --device='0'
# output
ONNX: export failure: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
'''

### Additional

1. It seems OK to use the CPU to export，
2. This question is very similar to #6995，
3. I hope the official can fix the corresponding problem of the warehouse！

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ZhangLe-fighting errors generated by https://github.com/TexasInstruments/edgeai-yolov5.git should be raised directly in that repo. Not sure why you're raising an issue here.

**Comment by ZhangLe-fighting** [comment]
> 
so sorry , but that repo is too inactive. So I tryto find the answer in this repo.

**Comment by glenn-jocher** [comment]
@ZhangLe-fighting got it. I would try to track down the author there as it's likely the error originates in code introduced there rather than here.

**Comment by ZhangLe-fighting** [comment]
> @ZhangLe-fighting got it. I would try to track down the author there as it's likely the error originates in code introduced there rather than here.

That's great ！
