### ISSUE TITLE
yolov5 multi process

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#9924]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi @jkocherhans i ask befor if i can use mulit process with yolov5,and i code it and just want to other with it 
, you can find it here 
https://github.com/totoadel/multi_process_yolov5.git
https://www.linkedin.com/feed/update/urn:li:activity:6990634953386397696
, i want to know what your opnino ?

**Comment by glenn-jocher** [comment]
Your URL is broken
