### ISSUE TITLE
I want to use cutmix method instead of mosaic preprocessing method for research purpose, anyone have idea?

### ISSUE THREAD

**Issue by MheadHero** [ultralytics/yolov5#9928]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to use cutmix method instead of mosaic preprocessing method for research purpose, anyone have idea?

**Comment by glenn-jocher** [comment]
Cutmix isn't available by default but you could check Albumentations or implement your own custom functions in utils/augmentations.py
