### ISSUE TITLE
GPU utilization is low when training on COCO dataset

### ISSUE THREAD

**Issue by ice-tall-cold** [ultralytics/yolov5#9929]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I'm using 3090ti to train yolov5s. When I train with COCO128, it's pretty fast and GPU utilization is high. But when I train with COCO dataset, it's much slower and GPU utilization is also low. I search on the website and realize it might be that the data read speed is low and GPU is always waiting. Then I use the new SSD and it increases the training speed and GPU utilization a little. But it still takes one and a half hours to train one epoch. Do you know what else I can do to further increase the training speed and GPU utilization? Appreciate it if you can provide any advice.

**Comment by ice-tall-cold** [comment]
And I already train on cached data and tried increasing the batch size.

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by MartinPedersenpp** [comment]
What is your batch size?

**Comment by ice-tall-cold** [comment]
> What is your batch size?

Now I'm using 64. And it gets better than before.

**Comment by glenn-jocher** [comment]
@ice-tall-cold glad to hear that increasing the batch size has improved the training speed! 🚀 Larger batch sizes can often help utilize the GPU more efficiently. If you have any more questions or need further assistance, feel free to ask!
