### ISSUE TITLE
error installing grpcio

### ISSUE THREAD

**Issue by Rishabh3112002** [ultralytics/yolov5#9931]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I have recently updated my mac to macos 13(ventura) and while installing the requirements.txt i am getting a "legacy-install-failure" while installing grpcio.

### Environment

-OS: Macos 13(ventura)
-python: 3.9.10

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by tsangz189** [comment]
This is because platform problem, I used to encounter this issue while installing tensorboard and solved by install `tensorflow-deps`
```
conda install -c apple tensorflow-deps
# then rerun
pip install -r requirements.txt
```

**Comment by hanifizzudinrahman** [comment]
> conda install -c apple tensorflow-deps

thanks broooo

**Comment by glenn-jocher** [comment]
@hanifizzudinrahman you're welcome! If you have any more questions or run into any issues, feel free to ask. Good luck with your installation! 😊
