### ISSUE TITLE
[SOLVED] Save data always on the same txt using --save-txt on yolov5 using detect.py

### ISSUE THREAD

**Issue by diogompontes** [ultralytics/yolov5#9936]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, i'm pretty new at working with yolo so...
I'm using --save-txt on yolov5 and i want to save data always in the same txt and not create a new one after receiving a new image. How could i do that?

**Comment by MartinPedersenpp** [comment]
https://github.com/ultralytics/yolov5/blob/32a92185738c93e5f0b0f6971de0812cd6fd5f34/detect.py#L143-L149

Change txt_path to your desired directory/txt file

Be aware that the save-txt arg appends to the txt file, so if you don't want it to append for each time you run detect.py, you need to rewrite the following part a small bit:

https://github.com/ultralytics/yolov5/blob/32a92185738c93e5f0b0f6971de0812cd6fd5f34/detect.py#L163-L166

Good luck!

**Comment by diogompontes** [comment]
Thanks for the help @MartinPedersenpp !

**Comment by MartinPedersenpp** [comment]
> Thanks for the help @MartinPedersenpp !

You are welcome, don't forget to mark this issue as solved, if your problem has been fixed
