### ISSUE TITLE
 How can I save the log file?

### ISSUE THREAD

**Issue by misoinwoo** [ultralytics/yolov5#9938]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hello

When running train.py
I want to save the displayed phrases as a text file.

How can I save it?

">>" does not work in shell scripts.

 python train.py --epochs 5 --data data/custom.yaml --cfg models/yolov5s.yaml --weights yolov5s.pt --workers 0 >> result.txt

cat result.txt
github: skipping check (offline), for updates see https://github.com/ultralytics/yolov5

![image](https://user-images.githubusercontent.com/113008551/198171859-318a5a4d-7ab8-4d04-a185-3daae5a29fa2.png)

**Comment by glenn-jocher** [comment]
@misoinwoo hi there,

You can easily save the displayed phrases from the training process to a text file using the redirection operator in your shell command. The command you provided should work, and the log output can be redirected to `result.txt` as expected.

If you encounter any issues with this approach, please ensure that your command is executed in a compatible shell environment. Additionally, you can find more information in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ under `Training > Logging`.

Let me know if you need further assistance with this.
