### ISSUE TITLE
How to perform HPO with ClearML?

### ISSUE THREAD

**Issue by tiensu** [ultralytics/yolov5#9939]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to do HPO with ClearML by using guidelines from https://github.com/ultralytics/yolov5/tree/master/utils/loggers/clearml (Hyperparameter Optimization section). 
- Fill task ID: base_task_id = 'b07f6d90a0c14778963be694c93e5112'
- Run command: python utils/loggers/clearml/hpo.py 
But there is an error as below:
![hpo](https://user-images.githubusercontent.com/6857665/198227968-b255dfaf-379f-4ef6-95fa-6953ed47e7f2.png)

On ClearML dashboard, the value of batch_size is 64:
![image](https://user-images.githubusercontent.com/6857665/198220035-913395f0-d28f-4233-a2c8-7fa0a570ec21.png)

Can you help me point out what I am doing wrong?

**Comment by glenn-jocher** [comment]
@tiensu thanks for your ClearML question! 

@thepycoder can you take a look at this please? Thanks!

**Comment by thepycoder** [comment]
@tiensu thanks for checking out ClearML!

Can you check if using [Integer Parameter Range](https://clear.ml/docs/latest/docs/references/sdk/hpo_parameters_uniformintegerparameterrange/) works instead?

Batch size should be an integer, so if you try to tell ClearML to treat it as a "uniform parameter" it will think of it as a float :)

If you only want to try a very limited range of possibilities, check out [discrete parameter range](https://clear.ml/docs/latest/docs/references/sdk/hpo_parameters_discreteparameterrange) instead and just pass a list! :)

Good luck and let us know if it works!

**Comment by tiensu** [comment]
@glenn-jocher & @thepycoder 
I followed your instructions. Now it worked.
Thank you for your support!

**Comment by tiensu** [comment]
@thepycoder
After running some experiments, it seems to have an error:
![image](https://user-images.githubusercontent.com/6857665/200246970-89f789eb-4b32-46e5-ad3a-4a3a85a56da4.png)
Please help me check it!

**Comment by thepycoder** [comment]
@tiensu can you add the HPO file you're using? I'll try to set it up myself and help you :)

**Comment by tiensu** [comment]
@thepycoder 
This is the hpo.py file that I am using.
[hpo.zip](https://github.com/ultralytics/yolov5/files/9949302/hpo.zip)
