### ISSUE TITLE
setting nc on yolov5s.yaml

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#9940]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

https://github.com/ultralytics/yolov5/blob/master/models/yolov5s.yaml
https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml

If train custom (nc=1), does the yolov5s.yaml need to fix?

**Comment by glenn-jocher** [comment]
classes are adapted automatically from your dataset
