### ISSUE TITLE
Why is the information about the number of layers different between the training phase and the testing phase

### ISSUE THREAD

**Issue by yuan-kai-design** [ultralytics/yolov5#9941]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

train:
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

Model Summary: 283 layers, 7082421 parameters, 7082421 gradients, 16.5 GFLOPS
--

</body>

</html>
test:
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

Model Summary: 224 layers, 7072789 parameters, 0 gradients, 16.4 GFLOPS
--

</body>

</html>

**Comment by glenn-jocher** [comment]
@yuan-kai-design models are fused during validation and prediction.
