### ISSUE TITLE
How can I increase the number of real time camera devices step-by-step? + I wonder what sources.txt clearly is

### ISSUE THREAD

**Issue by jjjjjjjjjjhhhhhh** [ultralytics/yolov5#9962]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

**How can I increase the number of real time camera devices step-by-step?** 

+ I've read other QNAs in this REPO and understood that I must add my camera devices into the sources.txt, however I couldn't find where the file was. If I have to create it, can I know the standards writing it?

**Comment by glenn-jocher** [comment]
@jjjjjjjjjjhhhhhh yes you can pass multiple streaming sources to detect.py in a sources.txt file that you create with one address i.e. 'rtsp://camera/address' on each line, no commas or anything else required
