### ISSUE TITLE
Why did the dimension suddenly change during validation, instead of 640, and I didn't start the multi-scale training

### ISSUE THREAD

**Issue by tangruinenu** [ultralytics/yolov5#9967]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![1667044113395](https://user-images.githubusercontent.com/100890412/198829753-e5154e46-df57-4386-95fe-e17dfbae3c35.png)
I've mentioned this before, but it's probably my code. However, the reason for the error is that the image is not resized during verification. For example, the input dimension in the image is (128,3,416,672), which leads to dimension mismatch. I specially set imagesize to 640 in the val.py file, but it still fails

### Additional

I've mentioned this before, but it's probably my code. However, the reason for the error is that the image is not resized during verification. For example, the input dimension in the image is (128,3,416,672), which leads to dimension mismatch. I specially set imagesize to 640 in the val.py file, but it still fails

**Comment by glenn-jocher** [comment]
Padding of stride/2 is added to each side during validation. You can disable this by setting pad=0 in val_loader.

**Comment by UsernameYG** [comment]
Hello, I'm confused about this pad setting. Why add pad at `self.batch_shapes = np.ceil(np.array(shapes) * img_size / stride + pad).astype(np.int) * stride` ? It seems that batch_shape is okay without pad added, is there any cases that don't adding pad will cause errors?

**Comment by tangruinenu** [comment]
> Hello, I'm confused about this pad setting. Why add pad at `self.batch_shapes = np.ceil(np.array(shapes) * img_size / stride + pad).astype(np.int) * stride` ? It seems that batch_shape is okay without pad added, is there any cases that don't adding pad will cause errors?

In fact, I set pad to 0 according to the author's method, but it was still wrong.

**Comment by UsernameYG** [comment]
I met this similar problem when I set p6 in model structures, and default pad=0.5 will cause stride be added to batch_shapes, and concat p6 operation in head will raise an error. By setting pad=0 it works fine.
In your case does the image tensor size resume to 640 or still remain 672

**Comment by tangruinenu** [comment]
> I met this similar problem when I set p6 in model structures, and default pad=0.5 will cause stride be added to batch_shapes, and concat p6 operation in head will raise an error. By setting pad=0 it works fine. In your case does the image tensor size resume to 640 or still remain 672

I am still as in the picture val input image size is [416,672], so far has not been resolved.

**Comment by UsernameYG** [comment]
Have you check val_loader at line 206 in train.py? 'pad' in create_dataloader is passed to class LoadImagesAndLabels in dataloader.py, line 566 :`self.batch_shapes = np.ceil(np.array(shapes) * img_size / stride + pad).astype(int) * stride` to be exact. My suggestion is debug here and see whether batch_shapes is correct or not.

**Comment by glenn-jocher** [comment]
@UsernameYG great observations! Debugging at that location will certainly provide more insight into the issue. Let's take a look there and see if the batch_shapes are being calculated correctly. This should help in understanding why the image tensor size is not being resized as expected.
