### ISSUE TITLE
Ideal epoch and bach size value for 15000 pictures

### ISSUE THREAD

**Issue by gurselturkeri** [ultralytics/yolov5#9969]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I want to train 15000 pictures with RTX3070. Whas should be epoch and bach size value?

**Comment by Sanath1998** [comment]
Ideally you need to give 50 epochs initially and batch-size 64 depending upon your hardware configurations.
Check for the over-fitting and if so reduce/ increase based on it.

**Comment by glenn-jocher** [comment]
@Sanath1998 thanks for reaching out! For 15,000 images with an RTX3070, a good starting point is 50 epochs and a batch size of 64. From there, monitor for overfitting and adjust as needed. Let me know if you need further help. Good luck with your training!
