### ISSUE TITLE
About the Classification model

### ISSUE THREAD

**Issue by ZhaoMonica** [ultralytics/yolov5#9974]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I would like to ask what preprocessing has been done for the data when using yolov5-6.2 code to train the classification model, and whether normalization, bgr->rgb and other operations have been carried out. I have not learned about relevant processing in the code you provided?

**Comment by glenn-jocher** [comment]
@ZhaoMonica you can look at the inference transforms here:
https://github.com/ultralytics/yolov5/blob/e704970f7f606d6d3e58641e9384f38b532aa846/utils/augmentations.py#L349
