### ISSUE TITLE
In-code inference for instance segmentation

### ISSUE THREAD

**Issue by prp-e** [ultralytics/yolov5#9975]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I did the model stuff as usual, and I got the warning about segmentation not being okay with AutoShape or some similar stuff. But I have a question, is it possible to do in-code inference for instance segmentation?

**Comment by davidserra9** [comment]
Same question!

**Comment by Evzen-T** [comment]
Im facing the same issue with inferencing custom trained instance segmentation models on my camera (oak d camera)

**Comment by glenn-jocher** [comment]
@prp-e @davidserra9 @Evzen-T segmentation is not yet supported by AutoShape(), but if you guys would like to help add this feature in a PR that would be great!
