### ISSUE TITLE
topk-all

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#9976]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

    parser.add_argument('--topk-all', type=int, default=100, help='TF.js NMS: topk for all classes to keep')

It is on export.py

what doe it mean?

It mean that  
setting --topk-all 10  
if the image has 60 person, it will detect the 10 of 60 person with sort.
So the model only detect 10 obj?

**Comment by glenn-jocher** [comment]
@alicera hi there! The `--topk-all` argument in `export.py` refers to the number of top results to keep for each class during inference. Setting `--topk-all 10` means that the model will keep the top 10 detections for each class. If the image has 60 persons, the model will still detect all 60 persons, but it will only keep the top 10 detections for each class. 🕵️‍♂️✨
