### ISSUE TITLE
How do I adjust label's size?

### ISSUE THREAD

**Issue by Frost819** [ultralytics/yolov5#998]
## ❔Question
The image itself is too small to be labeled.
So the size of the labels and characters are way too big. How do I adjust?
Thanks.

**Comment by glenn-jocher** [comment]
You can adjust the detection plotting parameters here:
https://github.com/ultralytics/yolov5/blob/c4cb78570cfca23d7e0a5aa7b4ee7e8c6b8d998c/detect.py#L111-L114
