### ISSUE TITLE
Equations of model parameters (L, C, R) from [depth|width]_multiple?

### ISSUE THREAD

**Issue by bryanbocao** [ultralytics/yolov5#9981]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When we specify the ```depth_multiple``` and ```width_multiple``` in the ```model.yaml``` file, what are the equations to compute model parameters (L, C, R), where ```L``` is the ```#layers```, ```C``` is the ```#channels``` and ```R``` is the ```resolution```?

Thanks!

**Comment by glenn-jocher** [comment]
@bryanbocao the equations for computing model parameters (L, C, R) based on the depth_multiple and width_multiple values in the model.yaml file are not explicitly provided, but you can calculate them using the equations below:

L = ((depth_multiple - 1) / 3) + 1
C = (width_multiple * 64)
R = 32 * (2 ** (int(math.log(max_size // 32, 2)) - 2))
(include 'import math' at the top of the model.yaml file)

You can also refer to the Ultralytics Docs for more detailed information on customizing the YOLOv5 architecture. Cheers!
