### ISSUE TITLE
when training yolov5 network， model learn small object first or big object first？

### ISSUE THREAD

**Issue by ZuyongWu** [ultralytics/yolov5#9982]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when training yolov5 network， model learn small object first or big object first？

**Comment by glenn-jocher** [comment]
all sizes are learned at the same time
