### ISSUE TITLE
Adding additional Yolo Detection Head

### ISSUE THREAD

**Issue by hyperf0cus** [ultralytics/yolov5#9983]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello There! How to correctly add extra YOLO detection head? Is there someone who already tried this?

### Additional

My example YAML:

# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc_1: 80  # number of classes
nc_2: 80
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.25  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head_1:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect1, [nc_1, anchors]],  # Detect(P3, P4, P5)
  ]

head_2:
  [[9, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 28

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 32 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 29], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 35 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 25], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 38 (P5/32-large)

   [[32, 35, 38], 1, Detect2, [nc_2, anchors]],  # Detect(P3, P4, P5)
  ]
_No response_

**Comment by glenn-jocher** [comment]
@hyperf0cus hi there! To add an additional YOLO detection head, you can define a new `head_2` section in the YAML similar to `head_1`, but with unique module arguments. Each head should end with `Detect{#}` specifying the number of classes and the anchors. You seem to have the structure correctly defined, but make sure to correctly adjust the backbone output channels to fit the new head. Feel free to ask if you encounter any issues. Good luck!
