### ISSUE TITLE
Fails when testing with different resolutions like 480, 720, 1080 resolution

### ISSUE THREAD

**Issue by jackson0988** [ultralytics/yolov5#9990]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained the model with img size 640. The testing data is of different resolutions like  640X480, 1280X720 AND 1920X1080. While testing, I have resized the video to 640x640 resolution, since the model is trained with img size 640. The model detects the object (can be seen in terminal) but fails to draw the bounding box.
1. What is the preferable resolution HxW for the testing data, if model is trained at img=640.
2. Whats is the preferable resolution HxW for testing data, if model is trained at imag=1280
3. Can the model be generalized for different resolution?

Please advise. Thank you!

**Comment by glenn-jocher** [comment]
@jackson0988 models generalize to similar resolutions, i.e. official models are --img 320 or --img 416 or --img 768 etc will all work fine, but you will get best results when objects are similarly sized to what you trained on.

**Comment by jackson0988** [comment]
@glenn-jocher Thank you. I have few questions too.
1. To get the better result, can I have different resolution of annotated samples in the training data?
 2. What  does --img 416 denotes height or width?
3. For a different resolution of testing data like 480, 720 and 1080p what is the preferred(generalized) --img size in training and testing?
