### ISSUE TITLE
Missing class labels in plotted metrics

### ISSUE THREAD

**Issue by schreiterjp** [ultralytics/yolov5#9991]
Hi, 
after training the saved plots are without any colorisation or class related labels and so nearly useless. For example the F1 curve: 
![F1_curve](https://user-images.githubusercontent.com/72251050/199182790-d26ee052-321a-48cc-8256-a76084ea750b.png)

Behaviour appears for training and validation. 
Is that an issue ralated to the number of 28 trainied classes? First time I tried with less classes all curves were nicely colored and labeled. 

Nethertheless really nice work guys, appreciate it thanks.

**Comment by glenn-jocher** [comment]
@schreiterjp yes for datasets with high class counts it's not feasible to provide a legend, so we only show the mean results.

**Comment by glenn-jocher** [comment]
@schreiterjp you might be able to update plots.py to force a legend manually.

**Comment by schreiterjp** [comment]
@glenn-jocher Alright thanks. I`ll try. Would be cool if you still give a legend for the classes underneath the mean value, so the worse performing classes can be still identified.

**Comment by glenn-jocher** [comment]
It goes off screen since it's too long, it's not possible otherwise we'd have bug reports from users.
