### ISSUE TITLE
val stage: only one gpu is working, speed is too slow. how to make all gpu to work?

### ISSUE THREAD

**Issue by lvpchen** [ultralytics/yolov5#9992]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

val stage: only one gpu is working, speed is too slow. how to make all gpu to work?

**Comment by glenn-jocher** [comment]
@lvpchen validation runs on single-GPU, this is expected.

**Comment by lvpchen** [comment]
@glenn-jocher  I know, thank you.

**Comment by glenn-jocher** [comment]
@lvpchen you're welcome! If you have any other questions, feel free to ask.
