### ISSUE TITLE
How to get mask in binary? 

### ISSUE THREAD

**Issue by JerolSOIBAM** [ultralytics/yolov5#9993]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

HI!
I just want to get the mask of the picture where the object is there and the rest of the pixel values to be black.
For example in the image background is "black" and where the leave is "white" in pixel values.
![196708929-5b405743-a1a7-4a9f-918b-7f630be16959](https://user-images.githubusercontent.com/43479556/199216868-ac0bc804-06a6-4be3-9021-75a75f69e65b.png)

**Comment by glenn-jocher** [comment]
you can just take a probability mask and do `mask > 0.5`

**Comment by glenn-jocher** [comment]
@JerolSOIBAM you can find the probability mask in the output of YOLOv5. After you obtain the predictions, you can access the probability mask for each detection. Then, you can apply the thresholding operation `mask > 0.5` to obtain a binary mask. You can refer to the YOLOv5 documentation for more details on accessing and processing the output.
