### ISSUE TITLE
does the training size affect the result?

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#9995]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Assume my dataset size is (416,640) h,w

train with (640,640)  and  train with (416,640) 
Do you think which is better?

I know yolov5 use mosaic to train and validation the result with center padding.
So the valid size is  near (416,640). not (640,640).
Because (640,640) can't effectively extend the image. It has many black information on image.

**Comment by alicera** [comment]
Do you think
 is the mosaic suitable  for rectangle  images training?

**Comment by glenn-jocher** [comment]
@alicera no, they are exclusive, you can either do mosaics or --rect without mosaics

**Comment by alicera** [comment]
What is the limit for --rect without "mosaics"?  
I only know the possible reason is that  
H>W images are not suitable for rectangular training (like training size(416,640) ).  
H>W images will cause many padding information for training size(416,640) with "mosaic"  

Due to the above reason, the mosaic isn't suitable for rectangular

**Comment by glenn-jocher** [comment]
@alicera Generally speaking, it's recommended to use mosaics for good results with YOLOv5, but you can try without mosaics up to a point. Rectangular images with H > W may require excessive padding and might not perform as well. Try different approaches and see what works best for your specific use case. Good luck!
