### ISSUE TITLE
how to caculate FPS?

### ISSUE THREAD

**Issue by woshi3112520** [ultralytics/yolov5#9996]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how to caculate FPS?

### Additional

how to caculate FPS?

**Comment by MartinPedersenpp** [comment]
Not really a yolo question, but more of a general python question.

```
start = time.time()
frame_counter = 0
while True:
    frame = capture_frame_from_cam()
    result = yolomodel(frame)
    frame_counter += 1
    if time.time() - start >= 1:
        print(f"Processed: {frame_counter} in a second")
        frame_counter = 0
        start = time.time()
```

Depending if you are using torch hub or detect.py you can add something like this to your script.
Good luck

**Comment by glenn-jocher** [comment]
@MartinPedersenpp thanks for sharing that code snippet! 🙏 To calculate FPS, you can measure the time it takes to process a certain number of frames and then divide that number by the elapsed time. The code you provided is a great starting point for this. Feel free to integrate it into your script and tweak as needed. Good luck with your project!
