### ISSUE TITLE
How do I use version 6.1 to train the coco dataset?

### ISSUE THREAD

**Issue by LUO77123** [ultralytics/yolov5#9998]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I did not use the weight training coco dataset to directly train the explosion. I don't know why.
![image](https://user-images.githubusercontent.com/87272337/199241581-1a57b044-7983-4d3b-b1e3-cd384a06ba19.png)

### Additional

![image](https://user-images.githubusercontent.com/87272337/199241613-1902663a-5a79-4046-b820-d25eff4653eb.png)

![image](https://user-images.githubusercontent.com/87272337/199241633-b10abba9-e8ea-47c9-87ba-0c7a85e7b2a4.png)

**Comment by glenn-jocher** [comment]
@LUO77123 could be caused by dataset problems or hyperparameter settings. Try reduced LR, longer warmup, check dataset, etc.
